Update Puppet documents
wazuh/wazuh-documentation pull request #2847
Opened 2020-09-02 16:25 UTC by Zenidd

Hello,

This PR updates the puppet documents for the upcoming v4.0 that is about to be released soon. 

Greetings,

JP

2020-09-03 15:59 UTC, manuasir requested changes

2020-09-03 15:59 UTC, manuasir commented on source/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
> +  Frequency that the rootcheck is going to be executed (in seconds).
```suggestion
  How often the rootcheck scan will run (in seconds).
```

2020-09-03 15:59 UTC, manuasir commented on source/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
> +  In this section it can be included a list of policy files to run assessments.
```suggestion
  A list of policies to run assessments can be included in this section.
```

2020-09-03 16:10 UTC, Zenidd commented on source/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
> +  Frequency that the rootcheck is going to be executed (in seconds).
Done on 2faa2ea, thanks !

2020-09-03 16:10 UTC, Zenidd commented on source/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
> +  In this section it can be included a list of policy files to run assessments.
Done on 2faa2ea, thanks !

2020-09-03 16:12 UTC, manuasir approved these changes

2020-09-03 16:31 UTC, xr09 approved these changes
LGTM

2020-10-09 17:07 UTC, davidfmiranda approved these changes
LGTM

2020-10-09 17:07 UTC, merged