Remove allow Redhat option for VDT
wazuh/wazuh-documentation pull request #2911
Opened 2020-09-11 11:25 UTC by chemamartinez

## Description

This PR applies to the documentation changes proposed at https://github.com/wazuh/wazuh/issues/5994.

It removes the deprecated way of configuring an unsupported OS for Redhat feeds. 

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2020-09-11 13:32 UTC, danimegar requested changes

2020-09-11 13:32 UTC, danimegar commented on source/user-manual/capabilities/vulnerability-detection/allow_os.rst
> +          <os allow="Oracle Linux-7">7</allow>
I think this line has to finish in `</os>` instead of `</allow>`

2020-09-11 15:42 UTC, danimegar approved these changes
LGTM!

2020-09-14 09:48 UTC, alberpilot approved these changes
LGTM

2020-09-14 09:48 UTC, merged