Update API configuration hot changes
wazuh/wazuh-documentation pull request #2915
Opened 2020-09-14 12:45 UTC by Selutario

This PR is related to https://github.com/wazuh/wazuh/issues/5993

## Description

Hi team! References to hot-changes when updating the API configuration or the Security configuration through the corresponding endpoints, were removed.

## Checks
- [ ] It compiles without warnings.
- [ ] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

Kind regards,
Selu.

2020-09-16 15:33 UTC, davidjiglesias requested changes

2020-09-16 15:33 UTC, davidjiglesias commented on source/user-manual/api/configuration.rst
> +To apply the changes it is necessary to restart each API whose configuration have changed:
```suggestion
To apply the changes it is necessary to restart each API whose configuration has changed:
```

2020-09-17 09:07 UTC, davidjiglesias approved these changes

2020-09-17 09:08 UTC, davidfmiranda approved these changes
LGTM

2020-09-17 09:09 UTC, merged