wazuh logtest documentation
wazuh/wazuh-documentation pull request #2973
Opened 2020-09-24 20:41 UTC by juliancnn

## Description

Hello team,

This issue is to adapt the logtest documentation. With the new implementation of wazuh-logtest, a new configuration block has been created in the ossec.conf file. Also, logtest is now a thread of analysisd and sessions can be created from the app to use this module.

Best regards,
Julian Morales

## Tasks
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

## Checks
- [ ] It compiles without warnings.
- [ ] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

## Note to the reviewer

This PR includes changes to the `redirect.js` script that need to be included in all production branches.

2020-10-02 03:32 UTC, juliancnn commented
@vikman90 Where should the Wazuh-Logtest documentation be? Temporarily put it in `/user-manual/capabilities/Wazuh-Logtest`

2020-11-11 14:30 UTC, jnasselle requested changes
Brief

- Wazuh Logtest is the whole solution, wazuh-logtest the tool that resides in Wazuh manager
- Change target version to 4.0 to 4.1.0
- Remove references to Wazuh APP until is implemented

2020-11-11 14:30 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +    The logtest core is part of the *Analysis daemon* (in manager). It has a session manager and shares its rules engine with Logtest.
analysis daemon must be ossec-analysisd, it also solves implicit location (the deamon only runs at manager)
Lot of it and its does not exist

2020-11-11 14:30 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +    Interact with Core Logtest, and provide an interface to test the rules and decoders remotely.
Change `test the rules and decoders` to `test rules and decoders` or `test the ruleset`
Also `provide a remote interface` is more accurate

2020-11-11 14:30 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +    Wazuh application for Kibana uses RESTful API to support Logtest from the web interface.
I think this section is not needed until App is ready

2020-11-11 14:30 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +    Interact with Core Logtest to test the rules and decoders locally.
Link to wazuh-logtest tool. Also referring it to be a replacement to ossec-logtest should be helpful. This also implicitly tell the user that resides at manager

2020-11-11 14:30 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +Wazuh API and Wazuh-Logtest Tool connect to the analysisd session manager, this acts as a sandbox with the rules engine, allowing to isolate different users with their own rules and decoders.
analysisd to ossec-analysisd.

2020-11-11 14:30 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +.. thumbnail:: ../images/development/logtest-flow.png
Maybe change Kibana and Wazuh APP to Kibana and Wazuh developer console to access it trough API

2020-11-11 14:30 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +Wazuh-Logtest is based on the use of unique sessions, identified with a “token”. Each session stores its own history of events, rules and decoders loaded.
unique sessions is ok, but i think `isolated` adjetive will be helpful

2020-11-11 14:30 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +When the log evaluation is requested for the first time, the session manager creates a new session, processing and returning the result along with the identification of the new session.
mention `alphanumeric token` as session identification

2020-11-11 14:30 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +Sessions have a default expiration time of 15 minutes. When a session remains idle, with no log processing requests during that period, the idle session collector closes the session.
`idle, with` this comma is not needed

2020-11-11 14:30 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +Idle session collector
This section must be before session lifetime to better understanding of `Session lifetime`

2020-11-11 14:30 UTC, jnasselle commented on source/user-manual/capabilities/wazuh-logtest/index.rst
> +.. versionadded:: 4.0.0
Change it to 4.1.0

2020-11-11 14:30 UTC, jnasselle commented on source/user-manual/capabilities/wazuh-logtest/index.rst
> +The Wazuh-Logtest whole solution incorporates from version 4.0 was designed to replace Ossec-Logtest tool.
Change it to 4.1.0.
Ossel-Logtest to `ossec-logtest`

2020-11-11 14:30 UTC, jnasselle commented on source/user-manual/capabilities/wazuh-logtest/index.rst
> +This solution that allows to test and verify rules locally and remotely is part of the analysisd daemon and they share the same rules engine.
Change analysisd daemon to `ossec-analysisd`

2020-11-11 14:30 UTC, jnasselle commented on source/user-manual/capabilities/wazuh-logtest/logtest-configuration.rst
> +| session_timeout | Time interval in which a client must remain  |                | A number to represent seconds,  |
Is't clean enough the minutes/seconds/hour syntax

2020-11-11 14:30 UTC, jnasselle commented on source/user-manual/reference/ossec-conf/rule_test.rst
> +Here is how to configure the wazuh-logtest module. It allows to test rules and decoders from Wazuh API and Kibana through Wazuh app
Warning. wazuh-logtest may confuse with the tool. In this case we are talking about the whole Wazuh Logtest solution

2020-11-11 14:30 UTC, jnasselle commented on source/user-manual/reference/ossec-conf/rule_test.rst
> +|                    | A number to represent seconds, to represent |
Be more clear about seconds/minute/hour syntax

2020-11-11 14:30 UTC, jnasselle commented on source/user-manual/reference/tools/ossec-logtest.rst
> +.. deprecated:: 4.1
4.1.0

2020-11-12 01:22 UTC, jnasselle approved these changes

2020-11-12 01:54 UTC, jnasselle requested changes

2020-11-12 01:54 UTC, jnasselle commented on source/user-manual/capabilities/wazuh-logtest/index.rst
> +featuring to test and verify the ruleset locally and remotely, sharing the rules engine
change featuring *to* ... for : now allowing  also to test and verify rules and decoders remotely

2020-11-12 01:54 UTC, jnasselle commented on source/development/wazuh-logtest.rst
> +seconds to close them.
Avoid using seconds, because parameter allow minutes and hour specification

2020-11-12 01:54 UTC, jnasselle commented on source/user-manual/capabilities/wazuh-logtest/logtest-faq.rst
> +    - The session has been idle longer than the `session_timeout` defined in the test_rule configuration in ossec.conf.
The section is incorrect. `rule_test` it's the correct one

2020-11-12 01:54 UTC, jnasselle commented on source/user-manual/capabilities/wazuh-logtest/logtest-faq.rst
> +    - The maximum number of sessions has been reached and a new session replaces the session that has been idle the longest.
Use max_session parameter. Link to ossec.conf specs

2020-11-12 01:54 UTC, jnasselle commented on source/user-manual/capabilities/wazuh-logtest/logtest-faq.rst
> +In a Wazuh Cluster, the master node processes the request.
`In a wazuh cluster` is repeated and could be avoided

2020-11-12 01:54 UTC, jnasselle commented on source/user-manual/capabilities/wazuh-logtest/logtest-faq.rst
> +Unlike Analysisd, the counter is not reset every hour, it stays throughout the session
change Analysisd to ossec-analysisd.
About reset time, check this. Remember that this is related with a timer responsable of log rotating, doing it every new hour (i think),i.e the first restart might be after the hour if the process start diferent than 0 minutes of the hour.

2020-11-12 01:54 UTC, jnasselle commented on source/user-manual/reference/ossec-conf/rule_test.rst
> +Here is how to configure the wazuh-logtest module. It allows to test rules and decoders from Wazuh API and :ref:`wazuh-logtest tool <wazuh-logtest>`
Change `wazuh-logtest module` to Wazuh-Logtest solution

2020-11-12 01:54 UTC, jnasselle commented on source/user-manual/reference/ossec-conf/rule_test.rst
> +|                    | A number to represent seconds, to represent |
Change it to` A positive number that should contain a suffix character indicating a time unit, such as, s (seconds), m (minutes), h (hours)`
View string_op.c:wlogtest and LOGTEST_LIMIT_SESSION_TIMEOUT, 
The max value is 365 days

2020-11-12 01:54 UTC, jnasselle commented on source/user-manual/capabilities/wazuh-logtest/logtest-configuration.rst
> +| session_timeout | Time interval in which a client must remain  |                | A positive number that should   |
Change it to` A positive number that should contain a suffix character indicating a time unit, such as, s (seconds), m (minutes), h (hours)`
View string_op.c:wlogtest and LOGTEST_LIMIT_SESSION_TIMEOUT, 
The max value is 365 days

2020-11-12 13:20 UTC, davidfmiranda requested changes
Hello Julian, I've reviewed your PR and LGTM, but I've requested some minor grammar changes. 

Regards,

David

2020-11-12 13:20 UTC, davidfmiranda commented on source/development/wazuh-logtest.rst
> +The below image illustrations how the user logs test flow through the Wazuh environment.
```suggestion
The image illustrations below show how the user logs test flow through the Wazuh environment.
```

2020-11-12 13:20 UTC, davidfmiranda commented on source/user-manual/capabilities/wazuh-logtest/logtest-faq.rst
> +Unlike :ref:`ossec-analysisd <ossec-analysisd>`, the counter is not reset every hour, it stays throughout the session
```suggestion
Unlike :ref:`ossec-analysisd <ossec-analysisd>`, the counter is not reset every hour, it stays throughout the session.
```

2020-11-12 13:20 UTC, davidfmiranda commented on source/user-manual/capabilities/wazuh-logtest/logtest-faq.rst
> +Currently Wazuh-Logtest solution check rules and decoders with syslog and json event format
```suggestion
Currently Wazuh-Logtest solution check rules and decoders with syslog and json event format.
```

2020-11-12 14:44 UTC, jnasselle approved these changes

2020-11-12 16:40 UTC, davidfmiranda approved these changes
LGTM

2020-11-13 10:09 UTC, JcabreraC approved these changes

2020-11-13 10:09 UTC, Lopuiz approved these changes

2020-11-13 20:20 UTC, merged