Change remote upgrading agents via RESTful API documentation
wazuh/wazuh-documentation pull request #3064
Opened 2020-10-21 15:40 UTC by mcarmona99

Hi team,

This PR is related to the issue https://github.com/wazuh/wazuh/issues/5536. This issue changed some API endpoints in order to adapt them to the new upgrade module.

In this PR, I have changed the steps for upgrading agents via the RESTful API. Now these steps and examples are updated according to the new upgrade module.

Regards,
Manuel.

2020-11-06 10:51 UTC, AdriiiPRodri approved these changes

2020-11-09 11:36 UTC, davidjiglesias requested changes
We need to add the appropiate changes to Migration from 3.X for these endpoints in version 4.1.

2020-11-10 09:42 UTC, davidjiglesias requested changes

2020-11-10 09:42 UTC, davidjiglesias commented on source/user-manual/api/equivalence.rst
> +Wazuh API 4.1 introduces several new endpoints and also modifies or removes some of the old ones. The biggest change for all existing endpoints is the new response format. Endpoint responses have bee
```suggestion
Wazuh API v4 introduces several new endpoints and also modifies or removes some of the old ones. The biggest change for all existing endpoints is the new response format. Endpoint responses have been changed according to the new RBAC standard and will no longer have ``items`` and ``totalitems`` fields. Most responses will have the following structure instead:
```

2020-11-10 09:42 UTC, davidjiglesias commented on source/user-manual/api/equivalence.rst
> +The Wazuh API users are not migrated when upgrading the Wazuh API from 3.X to 4.1. There are numerous security changes to the Wazuh API in 4.1 and it is not advisable.
```suggestion
The Wazuh API users are not migrated when upgrading the Wazuh API from 3.X to 4.1. There are numerous security changes to the Wazuh API and it is not advisable.
```

2020-11-10 09:42 UTC, davidjiglesias commented on source/user-manual/api/equivalence.rst
> +Wazuh API 4.1 introduces several changes to existing endpoints. It is therefore important to review those changes when migrating to ``4.1``.
```suggestion
Wazuh API v4 introduced several changes to existing endpoints. It is therefore important to review those changes when migrating to ``4.1``.
```

2020-11-10 09:49 UTC, davidjiglesias requested changes

2020-11-10 09:49 UTC, davidjiglesias commented on source/user-manual/agents/remote-upgrading/upgrading-agent.rst
> +        # curl -k -X GET "http://localhost:55000/agents/upgrade_result?agents_list=002,003&pretty=true" -H  "Authorization: Bearer $TOKEN"
```suggestion
        # curl -k -X GET "https://localhost:55000/agents/upgrade_result?agents_list=002,003&pretty=true" -H  "Authorization: Bearer $TOKEN"
```

2020-11-10 09:49 UTC, davidjiglesias approved these changes

2020-11-10 09:52 UTC, davidjiglesias requested changes
Add changes in endpoints links for RBAC reference

2020-11-10 10:03 UTC, davidjiglesias approved these changes

2020-11-10 12:55 UTC, davidfmiranda approved these changes
LGTM

2020-11-10 12:55 UTC, merged