Add ruleset reference of PCRE2 attribute for expressions
wazuh/wazuh-documentation pull request #3082
Opened 2020-10-26 23:31 UTC by jnasselle

Closes #2907 

## Description

Hi team!
This PR aims to add information regarding to PCRE2 regex type. This consist in the next changes

Rules syntax: 
- [X] Update value and description of options `regex` and `match` at index table 
- [X] Add `type` as optional attribute of `regex` and `match` options section, with their value range an default value
- [X] Check that all references to regular expressions types also mention new pcre2 type
Decoders syntax: 
- [X] Update value and description of options `prematch`, `regex` and `program_name` at index table 
- [X] Add `type` as optional attribute of `prematch`, `regex` and `program_name` options section, with their value range an default value
- [X] Check that all references to regular expressions types also mention new pcre2 type

Regular expression syntax:
-  [ ] Add PCRE2 heading with brief and link to their own documentation
-  [ ] Add samples of new features bring by PCRE2 compared with osregex and osmatch

Other fixes:
-  [X] Change `field` value at index table from `sregex` to `regex`

## Checks
- [X] It compiles without warnings.
- [X] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns. 
- [X] All links works as spected. 

Regards,
Nico

2020-10-30 15:00 UTC, davidfmiranda requested changes
Hello @jnasselle, I've reviewed your PR and LGTM, nevertheless, there is a reference in an index. We must avoid this and use the syntax `Title`_.

Regards,

David

2020-10-30 15:00 UTC, davidfmiranda commented on source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
> +- :ref:`regex_decoders`
```suggestion
- Regex`_

```

2020-10-30 15:00 UTC, davidfmiranda commented on source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
> +- :ref:`regex_decoders`
We should always use this syntax in indices

2020-10-30 15:27 UTC, davidfmiranda approved these changes
LGTM.

2020-11-02 19:00 UTC, juliancnn approved these changes

2020-11-04 15:28 UTC, juliancnn approved these changes

2020-11-05 14:37 UTC, Lopuiz approved these changes

2020-11-05 14:46 UTC, juliancnn approved these changes

2020-11-05 14:51 UTC, JcabreraC approved these changes

2020-11-06 14:17 UTC, davidfmiranda approved these changes
LGTM

2020-11-06 18:01 UTC, merged