Added macOS for vdt and os_patch
wazuh/wazuh-documentation pull request #3089
Opened 2020-10-28 11:47 UTC by MarcelKemp

## Description

Hi team,
This Pull Request is related to issue wazuh/wazuh#5860. I have added a new field "os_patch" inside syscollector. Also, vulnerability detector now supports OS for macOS.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns.

2020-10-30 16:38 UTC, chemamartinez approved these changes

2020-11-04 13:29 UTC, chemamartinez approved these changes
LGTM

2020-11-13 12:42 UTC, chemamartinez approved these changes

2020-11-13 13:11 UTC, davidfmiranda requested changes
Hello @MarcelKemp, I've reviewed your PR and it looks good to me. Nevertheless, I've requested on small change. The release notes file for v4.1.0 must be added to the toctree in the `release-notes > index`.

Regards,

David

2020-11-13 14:14 UTC, davidfmiranda approved these changes
LGTM

2020-11-13 14:14 UTC, merged