Add logtest documentation: API and RBAC references
wazuh/wazuh-documentation pull request #3100
Opened 2020-10-29 16:04 UTC by mcarmona99

Hi team,

This PR is part of https://github.com/wazuh/wazuh/issues/5337. In this PR, I have added some examples of the new PUT logtest API endpoint to the getting started part of the API documentation. I have also included the new rbac logtest reference.

2020-11-06 12:03 UTC, vicferpoy requested changes

2020-11-09 08:13 UTC, vicferpoy approved these changes
LGTM!

2020-11-09 11:30 UTC, davidjiglesias approved these changes

2020-11-09 12:04 UTC, davidfmiranda approved these changes

2020-11-09 12:04 UTC, merged