Add rootcheck to RBAC reference.
wazuh/wazuh-documentation pull request #3120
Opened 2020-11-05 09:07 UTC by Selutario

## Description

Hello team! This PR is related to [#6329](https://github.com/wazuh/wazuh/issues/6329). New actions have been added to API RBAC, so the reference page needed to be updated.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

Regards,
Selu.

2020-11-10 13:28 UTC, davidjiglesias requested changes
We are missing changes to equivalence table. Remember the equivalence table displays the changes from 3.X to 4.X.

Rootcheck endpoints were present in 3.X, so we need to adapt the table after adding them back, some of the old endpoints are still deprecated, but others are not.

2020-11-10 13:28 UTC, davidjiglesias commented on source/user-manual/api/rbac/reference.rst
> +Rootcheck
Also add agent:group (I know it is not present on the others, but a PR has been included to 4.0.1 to add this, so we need to add it to new additions)

2020-11-11 08:58 UTC, davidjiglesias requested changes

2020-11-11 08:58 UTC, davidjiglesias commented on source/user-manual/api/equivalence.rst
> +| Clear rootcheck database of an agent | ``DELETE /rootcheck/{agent_id}``        | :api-ref:`DELETE /rootcheck <operation/api.controllers.rootcheck_controller.delete_rootcheck>`
API 4.1 usage is wrong

2020-11-11 08:58 UTC, davidjiglesias commented on source/user-manual/api/equivalence.rst
> +| Run rootcheck scan in an agent       | ``PUT /rootcheck/{agent_id}``           | :api-ref:`PUT /rootcheck <operation/api.controllers.rootcheck_controller.put_rootcheck>`
API 4.1 usage is wrong

2020-11-11 08:58 UTC, davidjiglesias commented on source/user-manual/api/rbac/reference.rst
> +    - ``agent:id:*``
agent:group:* ??

2020-11-11 08:58 UTC, davidjiglesias commented on source/user-manual/api/rbac/reference.rst
> +    - ``agent:id:*``
agent:group:* ?

2020-11-11 15:40 UTC, davidjiglesias approved these changes

2020-11-11 15:51 UTC, davidfmiranda approved these changes
LGTM

2020-11-11 15:52 UTC, merged