[core-6650] Installing from sources - update based on latest changes
wazuh/wazuh-documentation pull request #3206
Opened 2020-12-01 01:54 UTC by tinachoB

## Description

The aim of these changes are to complement and update the new syscollector model. This one mainly involves changes in the building processes adding certain new libraries to be taking into account in our documentation, primarely, in the `Installing from sources` section. 
A brief description of the epic: This epic aims to the integration of RSync and DBSync in syscollector, this is to make efficient use of the states that are captured today, in turn, it is important to clarify that these changes target the synchronization and do not alter the providers.
**Epic:** https://github.com/wazuh/wazuh/issues/6104
**Epic issue for update documentation:** https://github.com/wazuh/wazuh/issues/6650

To fulfill this mission, the refactoring of syscollector is not an option, but an obligation due to the characteristics and current design, in which there is a lot of coupling, of the functionality (data collection, package creation, message sending)

## Checks
The following validations have been done on each Operating System updated in the documentation:
- [X] OpenSUSE for Manager: https://github.com/wazuh/wazuh/issues/6650#issuecomment-734993348
- [X] Ubuntu for Manager and Agent: https://github.com/wazuh/wazuh/issues/6650#issuecomment-735006037
- [X] CentOS for Manager and Agent: https://github.com/wazuh/wazuh/issues/6650#issuecomment-735810855
- [X] macOS for Agent: https://github.com/wazuh/wazuh/issues/6650#issuecomment-736015428
- [X] Windows for Agent: https://github.com/wazuh/wazuh/issues/6650#issuecomment-736016068
- [ ] Solaris for Agent: WIP

## Note to the reviewer

This PR _should be merged_ once the [Epic 6104](https://github.com/wazuh/wazuh/issues/6104) is completed, tested, validated and merged into the corresponding Wazuh version (v4.1.0)

2021-02-09 11:47 UTC, Dwordcito commented
Hi @davidfmiranda Could you prioritize this issue?

2021-02-11 19:02 UTC, konangc87 requested changes

2021-02-11 19:02 UTC, konangc87 commented on source/user-manual/capabilities/syscollector.rst
> +| **checksum**     | Integrity synchronization value        | 78503709147600c8e0023cf2b9995772280eee30          | All               |
missing item_id?

2021-02-11 19:02 UTC, konangc87 commented on source/user-manual/capabilities/syscollector.rst
> +
ditto

2021-02-11 19:02 UTC, konangc87 commented on source/user-manual/capabilities/syscollector.rst
> +| **checksum**     | Integrity synchronization value | 78503709147600c8e0023cf2b9995772280eee30            | All               |
ditto

2021-02-11 19:02 UTC, konangc87 commented on source/user-manual/capabilities/syscollector.rst
> +| **checksum**     | Integrity synchronization value | 78503709147600c8e0023cf2b9995772280eee30            | All                 |
ditto

2021-02-11 19:02 UTC, konangc87 commented on source/user-manual/capabilities/syscollector.rst
> +| **checksum**     | Integrity synchronization value        | 78503709147600c8e0023cf2b9995772280eee30          | All               |
ditto

2021-02-11 19:04 UTC, tinachoB commented on source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.rst
> +              # make -j$(nproc) && make install
Will do!

2021-02-11 19:04 UTC, tinachoB commented on source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.rst
> +            # cd ..
Will do!

2021-02-11 19:05 UTC, tinachoB commented on source/user-manual/capabilities/syscollector.rst
> +| **checksum**     | Integrity synchronization value        | 78503709147600c8e0023cf2b9995772280eee30          | All               |
Yup. Will add it.

2021-02-11 19:05 UTC, tinachoB commented on source/user-manual/capabilities/syscollector.rst
> +
Yup. Will add it.

2021-02-11 19:05 UTC, tinachoB commented on source/user-manual/capabilities/syscollector.rst
> +| **checksum**     | Integrity synchronization value | 78503709147600c8e0023cf2b9995772280eee30            | All                 |
Yup. Will add it.

2021-02-11 19:05 UTC, tinachoB commented on source/user-manual/capabilities/syscollector.rst
> +| **checksum**     | Integrity synchronization value        | 78503709147600c8e0023cf2b9995772280eee30          | All               |
Yup. Will add it.

2021-02-11 20:02 UTC, konangc87 approved these changes

2021-02-17 13:17 UTC, davidfmiranda approved these changes
LGTM

2021-02-17 14:49 UTC, tinachoB commented
@vikman90 - if you are ok with these changes, please go ahead and merge it! Thank you!

2021-02-17 18:22 UTC, vikman90 approved these changes
Hi team,

Can we find an alter

2021-02-17 18:23 UTC, merged