Changed documentation to use new names of tools
wazuh/wazuh-documentation pull request #3214
Opened 2020-12-04 16:12 UTC by danimegar

## Description

I have replaced ossec-control and ossec-regex by wazuh-control and wazuh-regex from [Tools reference](https://documentation.wazuh.com/4.0/user-manual/reference/tools/index.html). Also, I have removed ossec-logtest, ossec-makelists and other deprecated tools and I checked the appearances of these tools across the whole documentation.
This PR closes #3208  

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

## Note to the reviewer

This PR includes changes to the `redirect.js` script that need to be included in all production branches.

2020-12-10 15:36 UTC, chemamartinez requested changes

2020-12-10 15:36 UTC, chemamartinez commented on source/learning-wazuh/ssh-brute-force.rst
> +    [root@wazuh-manager centos]# /var/ossec/bin/wazuh-logtest -v
`wazuh-logtest` doesn't support the `-v` parameter for verbosity. We have to take this into account to tune this section accordingly.

2020-12-10 15:36 UTC, chemamartinez commented on source/user-manual/reference/tools/wazuh-control.rst
> +The wazuh-control script is used to start, stop, configure, or check on the status of Wazuh processes. This script can enable or disable client-syslog, database logging, agentless configurations, int
Some versions ago the need for enabling client-syslog, database logging, agentless configurations, and integrations were removed. Change this sentence to:

```
The wazuh-control script is used to start, stop, configure, check on the status of Wazuh processes and enable the debug mode.
```

2020-12-10 15:36 UTC, chemamartinez commented on source/user-manual/ruleset/testing.rst
> +    $ /var/ossec/bin/wazuh-logtest -v
`-v` is not an option for the new `wazuh-logtest`

2020-12-11 12:39 UTC, chemamartinez requested changes

2020-12-11 12:39 UTC, chemamartinez commented on source/learning-wazuh/audit-commands.rst
> +#. Note the rule 100200 was evaluated.
Please change this sentence since rule 100200 is fired but a lot of alerts before are also evaluated:

```
#. Verify rule 100200 matches.

2020-12-11 12:39 UTC, chemamartinez commented on source/learning-wazuh/audit-commands.rst
> +Test the log to observe which rules is evaluated
How to observe correct rules are evaluated

2020-12-11 13:08 UTC, chemamartinez approved these changes
LGTM

2020-12-11 13:09 UTC, chemamartinez commented
Adding @davidfmiranda as a reviewer. Please notice that these changes should not be merged before https://github.com/wazuh/wazuh/issues/6766 is done.

Regards.

2021-01-07 17:13 UTC, chemamartinez approved these changes

2021-01-07 17:25 UTC, davidfmiranda approved these changes
LGTM

2021-01-07 17:25 UTC, merged