Add max_fps option to the FIM documentation.
wazuh/wazuh-documentation pull request #3218
Opened 2020-12-09 10:15 UTC by antoniomanuelfr

## Description
Hi team. 
This PR adds a new option for FIM: `max_fps`. This option is described in #3217. 

Closes #3217.

## Checks
- [X] It compiles without warnings.
- [ ] Spelling and grammar. 
- [X] Used impersonal speech. 
- [X] Used uppercase only on nouns.

2021-02-08 12:25 UTC, Molter73 requested changes

2021-02-08 12:25 UTC, Molter73 commented on source/user-manual/reference/ossec-conf/syscheck.rst
> +Sets the maximum number of files scanned per second. It only applies to the scheduled scan. If this option is set to 0, there will be no limit on the number of files scanned per second.
```suggestion
Sets the maximum number of files scanned per second. If this option is set to 0, there will be no limit on the number of files scanned per second.
```

2021-02-08 15:13 UTC, Molter73 approved these changes
LGTM!

2021-02-08 16:07 UTC, davidfmiranda requested changes
Hello @antoniomanuelfr, I've reviewed your PR, and looks good to me. Nevertheless, there is a small typo to be fixed.

Regards,

David

2021-02-08 16:07 UTC, davidfmiranda commented on source/user-manual/reference/ossec-conf/syscheck.rst
> +| **Allowed values** | Integer positive number. 0 mean no limit.               |
```suggestion
| **Allowed values** | Integer positive number. 0 means no limit.              |
```

2021-02-08 16:07 UTC, davidfmiranda commented on source/user-manual/reference/ossec-conf/syscheck.rst
> +| **Allowed values** | Integer positive number. 0 mean no limit.               |
```suggestion
| **Allowed values** | Integer positive number. 0 means no limit.              |
```

2021-02-15 11:13 UTC, davidfmiranda approved these changes
LGTM

2021-02-15 11:14 UTC, merged