Enhancing log analysis with PCRE2
wazuh/wazuh-documentation pull request #3253
Opened 2020-12-21 23:10 UTC by juliancnn

Hi team!
The main purpose of this issue is to move this blog article to the documentation as a use case.

## Description

Endpoint logs contain essential information for early threat detection, hence the importance of analysis. PCRE regex will empower and simplify this task without compromising performance.

## Checks
- [ ] It compiles without warnings.
- [ ] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

## Note to the reviewer

This PR includes changes to the `redirect.js` script that need to be included in all production branches.

2020-12-22 11:53 UTC, jnasselle commented on source/user-manual/ruleset/ruleset-xml-syntax/pcre2.rst
> +- **Static fields**: action, extra_data, hostname, id, location, match, program_name, protocol, user, url, srcport, dstport, status, system_name, extra_data, srcgeoip, dstgeoip
Set reference to fields

2020-12-22 11:53 UTC, jnasselle commented on source/user-manual/ruleset/ruleset-xml-syntax/pcre2.rst
> +- program_name
Add content to this sections. Kinda empty

2020-12-22 11:53 UTC, jnasselle commented on source/user-manual/ruleset/ruleset-xml-syntax/pcre2.rst
> +This post briefly describes the features of this type of regex, its enablement
This is not a post

2020-12-22 11:53 UTC, jnasselle commented on source/user-manual/ruleset/ruleset-xml-syntax/pcre2.rst
> +Compared to OSRegex and OSMatch that are case insensitive, PCRE regex are case sensitive by default. This can be changed by using ``(?i)``.
Link to OSRegex and OSMatch

2020-12-22 11:53 UTC, jnasselle commented on source/user-manual/ruleset/ruleset-xml-syntax/pcre2.rst
> +In addition to the types of characters like ``\w`` to match a `word` character  or ``\d`` to match the digit decimal,
Two spaces before `or` .
It's _decimal digit_ rather than `digit decimal`

2020-12-22 11:53 UTC, jnasselle commented on source/user-manual/ruleset/ruleset-xml-syntax/pcre2.rst
> +Example: Creating a set with the characters backslash (``/``) and hyphen (``-``), the ``\d+[-\/]\d+[-\/]\d+``
Not clear enough

2020-12-22 11:53 UTC, jnasselle commented on source/user-manual/ruleset/ruleset-xml-syntax/pcre2.rst
> +i.e user `FOO` and `foo` are treated like they are the same one from rule perspective.
Change _user_ to _users_

2020-12-23 13:08 UTC, jnasselle approved these changes
LGTM!

2020-12-24 18:29 UTC, davidfmiranda requested changes
Hello @juliancnn, I've reviewed your PR and looks good to me. Nevertheless, I've suggested you some changes.

Regards,

David

2020-12-29 16:48 UTC, davidfmiranda approved these changes
LGTM

2020-12-29 16:48 UTC, merged