Remove AR limitations
wazuh/wazuh-documentation pull request #3353
Opened 2021-02-02 12:58 UTC by Nicogp

## Description
Changes included:
- [ ] Change the FAQ  on how to create a custom script.
- [ ] Rename old scripts(remove .sh).
- [ ] Fix some logs
- [ ] Deprecate <expect> in commands section

## Checks
- [ ] It compiles without warnings.
- [ ] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns.

2021-02-02 19:50 UTC, TomasTurina requested changes

2021-02-02 19:50 UTC, TomasTurina commented on source/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
> +  Name of the executable. WAZUH comes preloaded with disable-account, host-deny, ipfw, pf, route-null, firewall-drop, ipfw_mac, wazuh-slack, restart-wazuh.
Remove `ipfw_mac`.

2021-02-02 19:50 UTC, TomasTurina commented on source/user-manual/capabilities/active-response/how-it-works.rst
> +| ipfw_mac                 | Firewall-drop response script created for the Mac OS          |
Remove this script.

2021-02-02 19:50 UTC, TomasTurina commented on source/user-manual/capabilities/active-response/remediation-configuration.rst
> +In this example, the ``win_rout-null`` command is configured to use the ``route-null.exe`` script.  The active response is configured to initiate the ``win_rout-null`` command on the local host when
Typo: `win_route-null`

2021-02-02 20:48 UTC, Nicogp commented on source/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
> +  Name of the executable. WAZUH comes preloaded with disable-account, host-deny, ipfw, pf, route-null, firewall-drop, ipfw_mac, wazuh-slack, restart-wazuh.
solved

2021-02-02 20:49 UTC, Nicogp commented on source/user-manual/capabilities/active-response/how-it-works.rst
> +| ipfw_mac                 | Firewall-drop response script created for the Mac OS          |
solved

2021-02-02 20:49 UTC, Nicogp commented on source/user-manual/capabilities/active-response/remediation-configuration.rst
> +In this example, the ``win_rout-null`` command is configured to use the ``route-null.exe`` script.  The active response is configured to initiate the ``win_rout-null`` command on the local host when
solved

2021-02-02 21:35 UTC, TomasTurina requested changes

2021-02-02 21:35 UTC, TomasTurina commented on source/user-manual/capabilities/active-response/remediation-configuration.rst
>      <executable>host-deny.sh</executable>
Remove `.sh`.

2021-02-02 21:35 UTC, TomasTurina commented on source/learning-wazuh/shellshock.rst
> +        2021/02/01 20:48:31 /var/ossec/active-response/bin/firewall-drop: {"version":1,"origin":{"name":"","module":"wazuh-execd"},"command":"delete","parameters":{"extra_args":[],"alert":{"timestamp
This log should be 5 minutes after the first one.

2021-02-02 21:35 UTC, TomasTurina commented on source/user-manual/capabilities/active-response/remediation-faq.rst
> +        },
Remove extra tab.

2021-02-02 21:35 UTC, TomasTurina commented on source/user-manual/capabilities/active-response/remediation-faq.rst
> +        },
Remove extra tab.

2021-02-02 21:35 UTC, TomasTurina commented on source/user-manual/capabilities/active-response/remediation-faq.rst
> +                    },
Remove extra tab.

2021-02-02 21:35 UTC, TomasTurina commented on source/user-manual/capabilities/active-response/remediation-faq.rst
> +                },
Remove extra tab.

2021-02-03 13:12 UTC, TomasTurina approved these changes

2021-02-03 13:13 UTC, merged