Adding warning messages to properly set the notify time and the disconnection time
wazuh/wazuh-documentation pull request #3542
Opened 2021-03-03 23:27 UTC by DProvinciani

## Description

This pull request adds some warning messages to keep in mind when configuring the values for the [notify-time](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#notify-time) and [agents-disconnection-time](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#agents-disconnection-time) settings. This prevents the users to run into a configuration that could result in agents being disconnected constantly.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns.

2021-03-04 12:30 UTC, palaciosjeremias approved these changes

2021-03-08 15:18 UTC, vikman90 requested changes

2021-03-08 15:18 UTC, vikman90 commented on source/user-manual/reference/ossec-conf/client.rst
> +  This setting should always be lower than the :ref:`disconnection time <reference_agents_disconnection_time>` configured for the agents in the manager. This allows them to always notify the manager
Should we skip `the`?

2021-03-08 15:18 UTC, vikman90 commented on source/user-manual/reference/ossec-conf/global.rst
> +  This setting should always be greater than the :ref:`notify-time <notify_time>` configured in the agents. This allows them to always notify the manager before it would consider them disconnected.
Same issue as above.

2021-03-08 18:24 UTC, DProvinciani commented on source/user-manual/reference/ossec-conf/client.rst
> +  This setting should always be lower than the :ref:`disconnection time <reference_agents_disconnection_time>` configured for the agents in the manager. This allows them to always notify the manager
Fixed.

2021-03-08 18:24 UTC, DProvinciani commented on source/user-manual/reference/ossec-conf/global.rst
> +  This setting should always be greater than the :ref:`notify-time <notify_time>` configured in the agents. This allows them to always notify the manager before it would consider them disconnected.
Fixed.

2021-03-10 13:16 UTC, vikman90 approved these changes

2021-03-10 13:17 UTC, merged