Remove monitord daemon and expand wmodules monitor module.
wazuh/wazuh-documentation pull request #3792
Opened 2021-05-01 04:58 UTC by Dwordcito

## Description

This issue aims to update the documentation, for this new behavior in the agent, in which there is process unification in wazuh modulesd, then it will be established that it must be modified.

## Checks
- [ ] It compiles without warnings.
- [ ] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

## Note to the reviewer

This PR includes changes to the `redirect.js` script that need to be included in all production branches.

2021-05-04 13:41 UTC, tinachoB approved these changes
LGTM!

2021-05-04 13:52 UTC, konangc87 requested changes

2021-05-04 13:52 UTC, konangc87 commented on source/user-manual/reference/daemons/wazuh-modulesd.rst
> +  The monitor module, looks at agent connectivity, In addition, it rotates and compresses iternal logs daily or when they reach a certain configurable size.
*internal

2021-05-04 13:52 UTC, konangc87 commented on source/user-manual/reference/daemons/wazuh-modulesd.rst
> +  As well, within this module works the ability to send daily and automatic reports, based on specific alerts captured or more general alerts.
maybe it will be better to say: This module is also responsible of sending automatic reports....

2021-05-05 11:46 UTC, konangc87 approved these changes

2021-05-05 15:14 UTC, davidfmiranda requested changes
Hello @Dwordcito, I've reviewed your PR and LGTM. I've made you just a small grammar suggestion.

Regards,

David

2021-05-05 15:14 UTC, davidfmiranda commented on source/user-manual/reference/daemons/wazuh-modulesd.rst
> +  Also, this module is responsible to send daily and automatic reports based on general/specific alerts captured.
```suggestion
  Also, this module is responsible for sending daily and automatic reports based on general/specific alerts captured.
```

2021-05-05 15:16 UTC, davidfmiranda approved these changes
LGTM

2025-06-09 14:52 UTC, closed without merging