Update Vulnerability Detector documentation to include information about Amazon Linux support
wazuh/wazuh-documentation pull request #3796
Opened 2021-05-04 09:43 UTC by alromeros

## Description
|Related issue|
|---|
|#3770|

Hi team,

With the inclusion of a dedicated **Amazon Linux**'s support in the **Vulnerability Detector** module, **Wazuh**'s documentation needs to be updated to include references about this operating system in the correspondent pages.

The main points to cover include:

- [x] The Vulnerability Detector section must include the new feed/provider and the Amazon Linux as a supported platform
- [x] All vulnerability-related usage guides must be updated with information and configuration examples for the new provider. 

Best regards,
Álvaro Romero.

## Checks
- [ ] It compiles without warnings.
- [ ] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns.

2021-05-27 16:25 UTC, chemamartinez requested changes

2021-05-27 16:25 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/vuln-detector.rst
> +|                    |                           |                    |              | Amazon-Linux / 1
In the configuration, values are lowercase:
```
amazon-linux
amazon-linux-2
```

2021-05-27 16:25 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/vuln-detector.rst
> +|                    |                           |                    | alas         | Parameterized link to download the feed file from Wazuh's own repository for `Amazon Linux <https://feed.wazuh.c
This has to be added to the `url` and `path` attributes for `os` instead of the independent options for the other providers.

2021-05-27 16:25 UTC, chemamartinez commented on source/user-manual/capabilities/vulnerability-detection/index.rst
> +of vulnerability feeds indexed by Canonical, Debian, Red Hat, Arch and the National Vulnerability Database.
Include ALAS here

2021-05-27 16:25 UTC, chemamartinez commented on source/user-manual/capabilities/vulnerability-detection/how_it_works.rst
> +- `<https://feed.wazuh.com/>`_: Used to pull ALAS feeds with CVEs for Amazon Linux distributions.
It is repeated for the MSU

2021-05-27 16:32 UTC, chemamartinez approved these changes

2021-05-27 16:41 UTC, davidfmiranda approved these changes
LGTM

2021-11-02 18:23 UTC, Arcapas reviewed
@chemamartinez, please review my suggestions.

2021-11-02 18:23 UTC, Arcapas commented on source/user-manual/capabilities/vulnerability-detection/how_it_works.rst
>  This database can be configured to be updated periodically, ensuring that the solution will check for the very latest CVEs.
```suggestion
This database can be configured to be updated periodically, ensuring that the solution checks for the latest CVEs.
```

2021-11-02 18:23 UTC, Arcapas commented on source/user-manual/capabilities/vulnerability-detection/offline_update.rst
> +The vulnerability feeds for ``Amazon Linux`` systems are currently fetched from Wazuh's own repository as ALAS feeds. To perform an offline update of these feeds, they first have to be downloaded fro
```suggestion
The vulnerability feeds for ``Amazon Linux`` systems are currently fetched from Wazuh's repository as ALAS feeds. To perform an offline update of these feeds, they first have to be downloaded from the corresponding Wazuh repository:
```

2021-11-02 18:41 UTC, Arcapas approved these changes
LGTM

2021-11-03 11:39 UTC, MarVergara approved these changes
LGTM

2021-11-03 11:41 UTC, merged