Update AWS module dependencies for Wazuh agents
wazuh/wazuh-documentation pull request #3841
Opened 2021-05-20 07:52 UTC by CarlosRS9

Hello team,

This PR updates the dependencies for using the AWS module in Wazuh agents. The only real requirement here is the installation of `python3.6` or greater and `boto3 1.13.1` or greater.

To test the required dependencies clean ubuntu and CentOS environments were used. Wazuh agent was installed in both environments and registered in a Wazuh manager. After that, we tried to run the module, resolving any dependency issues one by one.

2021-05-20 13:03 UTC, Selutario requested changes

2021-05-20 13:03 UTC, Selutario commented on source/amazon/services/prerequisites/dependencies.rst
> +  # yum install python3
The repo should also be updated in Centos: 

```suggestion
  # yum update && yum install python3
```

2021-05-20 13:03 UTC, Selutario commented on source/amazon/services/prerequisites/dependencies.rst
> +  # yum install python3-pip
```suggestion
  # yum update && yum install python3-pip
```

2021-05-21 06:19 UTC, Selutario approved these changes

2021-05-21 06:31 UTC, davidjiglesias approved these changes

2021-05-21 07:54 UTC, davidfmiranda approved these changes
LGTM

2021-05-21 07:54 UTC, merged