Add meta description to some pages
wazuh/wazuh-documentation pull request #3853
Opened 2021-05-26 08:28 UTC by PilarQuesada

Hi team, this PR closes #3852 

## Description
I have added a meta description to several pages of the documentation. 

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

Regards!

2021-07-07 17:48 UTC, MarVergara commented on source/docker/docker-installation.rst
> +  :description: Check out this section of the Wazuh documentation to learn more about the Docker installation and how to install the Docker engine and the Docker compose.
```suggestion
  :description: Check out this section of the Wazuh documentation to learn about Docker installation: how to install the Docker engine and the Docker compose. 
```

2021-07-07 17:50 UTC, MarVergara commented on source/installation-guide/more-installation-alternatives/elastic-stack/index.rst
> +  :description: Check out how to install Wazuh with Elastic Stack basic license: deployment types, installation methods, and more.
```suggestion
  :description: Check out how to install Wazuh with Elastic Stack basic license, deployment types, installation methods, and more. 
```

2021-07-07 17:57 UTC, MarVergara commented on source/installation-guide/open-distro/distributed-deployment/step-by-step-installation/wazuh-cluster/wazuh_single_node_cluster.rst
> +  :description: Looking for How to install Wazuh and Filebeat server components in a single node Wazuh cluster?Check out this section and learn how.
```suggestion
  :description: Looking for how to install Wazuh server components and Filebeat in a single node cluster? Check out this section of our documentation.
```

2021-07-07 18:00 UTC, MarVergara commented on source/installation-guide/open-distro/index.rst
> +  :description: Visit our installation guide to get started with Wazuh. In this section, you can learn how to install the Wazuh server.
```suggestion
  :description: Visit our Installation guide to get started with Wazuh. In this section, you can learn how to install the Wazuh server. 
```

2021-07-07 18:00 UTC, MarVergara commented on source/installation-guide/wazuh-agent/deployment_variables/deployment_variables.rst
> +  :description: Learn about the variables that facilitate the deployment of the Wazuh agent on Linux, macOS, Windows and AIX operating systems.
```suggestion
  :description: Learn about the variables that facilitate the deployment of the Wazuh agent on Linux, macOS, Windows, and AIX operating systems.
```

2021-07-07 18:19 UTC, MarVergara commented on source/installation-guide/wazuh-agent/wazuh_agent_package_aix.rst
> +  :description: Learn more about how to install or deploy the Wazuh lightweight agent in AIX in this section of our installation guide.
```suggestion
  :description: Learn how to deploy the Wazuh agent on AIX, using deployment variables that facilitate the task of installing, registering, and configuring the agent. 
```

2021-07-07 18:23 UTC, MarVergara commented on source/installation-guide/wazuh-agent/wazuh_agent_package_hpux.rst
> +  :description: Learn more about how to install or deploy the Wazuh lightweight agent in HP-UX in this section of our installation guide.
```suggestion
  :description: Learn more about how to successfully install the Wazuh agent on HP-UX systems in this section of our Installation guide.
```

2021-07-07 18:25 UTC, MarVergara commented on source/installation-guide/wazuh-agent/wazuh_agent_package_linux.rst
> +  :description: Learn more about how to install or deploy the Wazuh lightweight agent in Linux in this section of our installation guide.
```suggestion
  :description: Learn how to deploy the Wazuh agent on Linux with deployment variables that facilitate the task of installing, registering, and configuring the agent. 
```

2021-07-07 18:27 UTC, MarVergara commented on source/installation-guide/wazuh-agent/wazuh_agent_package_macos.rst
> +  :description: Learn more about how to install or deploy the Wazuh lightweight agent in macOS in this section of our installation guide.
```suggestion
  :description: Learn more about how to successfully install the Wazuh agent on macOS systems in this section of our Installation guide.
```

2021-07-07 18:29 UTC, MarVergara commented on source/installation-guide/wazuh-agent/wazuh_agent_package_solaris.rst
> +  :description: Learn more about how to install or deploy the Wazuh lightweight agent in Solaris 10 i386 in this section of our installation guide.
```suggestion
  :description: Learn more about how to successfully install the Wazuh agent on Solaris systems in this section of our Installation guide.
```

2021-07-07 22:06 UTC, MarVergara requested changes

2021-07-07 22:06 UTC, MarVergara commented on source/user-manual/manager/alert-threshold.rst
> +  :description: The Wazuh manager is the system that analyzes the data received from all registered agents. Find out more about how to define an alert level threshold here.
```suggestion
  :description: The Wazuh manager is the system that analyzes the data received from all registered agents. Find out more about how to define an alert level threshold.
```

2021-07-07 22:06 UTC, MarVergara commented on source/user-manual/reference/ossec-conf/client.rst
> +  :description: Learn more about the client configuration section and its options in this section of the Wazuh user manual.
```suggestion
  :description: Learn more about the client configuration section and its configuring options in this section of the Wazuh user manual. 
```

2021-07-07 22:06 UTC, MarVergara commented on source/user-manual/registering/password-authorization-registration.rst
> +  :description: Check out more about registering Wazuh agents and the registration service with password authorization in our documentation.
```suggestion
  :description: Check out our documentation to learn about registering Wazuh agents and the registration service with password authorization. 
```

2021-07-08 07:18 UTC, PilarQuesada commented on source/user-manual/configuring-cluster/index.rst
> -  :description: A complete user manual about how to configure a Wazuh cluster.
This meta description is way too short. We need a meta description between 120 and 150 characters, @MarVergara

2021-07-08 16:09 UTC, MarVergara commented on source/user-manual/configuring-cluster/index.rst
> +  :description: Learn more about the cluster node configuration in Wazuh: labels, Filebeat, Splunk forwarder installation, and more.
```suggestion
  :description: Learn more about the cluster node configuration in Wazuh: master and worker nodes, labels, Filebeat, Splunk forwarder installation, and more. 
```

2021-07-08 16:30 UTC, MarVergara requested changes

2021-07-08 16:30 UTC, MarVergara commented on source/installation-guide/open-distro/distributed-deployment/step-by-step-installation/elasticsearch-cluster/elasticsearch-multi-node-cluster.rst
> +  :description: Learn more about how to install Elasticsearch in a multi-node cluster for Wazuh in this step-by-step guide.
```suggestion
  :description: Learn how to install Elasticsearch on a multi-node cluster with Wazuh. This deployment type provides high availability and scalability of the product. 
```

2021-07-08 16:30 UTC, MarVergara commented on source/installation-guide/open-distro/distributed-deployment/unattended/unattended-elasticsearch-cluster-installation.rst
> +  :description: Check out how to install Open Distro for Elasticsearch and Open Distro for Kibana using an automated script.
```suggestion
  :description: Check out how to install Open Distro for Elasticsearch and Open Distro for Kibana using a script that automates the installation process.
```

2021-07-08 16:30 UTC, MarVergara commented on source/installation-guide/wazuh-agent/wazuh_agent_package_aix.rst
> +  :description: Learn how to deploy the Wazuh agent on AIX, using deployment variables that facilitate the task of installing, registering, and configuring the agent.
```suggestion
  :description: Learn how to deploy the Wazuh agent on AIX using deployment variables that facilitate the task of installing, registering, and configuring the agent. 
```

2021-07-08 16:30 UTC, MarVergara commented on source/installation-guide/wazuh-agent/wazuh_agent_package_hpux.rst
> +  :description: Learn more about how to successfully install the Wazuh agent on HP-UX systems in this section of our Installation guide.
```suggestion
  :description: Learn more about how to successfully install the Wazuh agent on HP-UX systems in this section of our Installation Guide.
```

2021-07-08 16:30 UTC, MarVergara commented on source/installation-guide/wazuh-agent/wazuh_agent_package_macos.rst
> +  :description: Learn more about how to successfully install the Wazuh agent on macOS systems in this section of our Installation guide.
```suggestion
  :description: Learn more about how to successfully install the Wazuh agent on macOS systems in this section of our Installation Guide.
```

2021-07-08 16:30 UTC, MarVergara commented on source/installation-guide/wazuh-agent/wazuh_agent_package_solaris.rst
> +  :description: Learn more about how to successfully install the Wazuh agent on Solaris systems in this section of our Installation guide.
```suggestion
  :description: Learn more about how to successfully install the Wazuh agent on Solaris systems in this section of our Installation Guide.
```

2021-07-08 16:30 UTC, MarVergara commented on source/installation-guide/wazuh-agent/wazuh_agent_package_windows.rst
> +  :description: Learn more about how to successfully install the Wazuh agent on Windows systems in this section of our Installation guide.
```suggestion
  :description: Learn more about how to successfully install the Wazuh agent on Windows systems in this section of our Installation Guide.
```

2021-07-08 16:30 UTC, MarVergara commented on source/user-manual/reference/ossec-conf/client.rst
> +  :description: Learn more about the client configuration section and its configuring options in this section of the Wazuh user manual.
```suggestion
  :description: Learn more about client configuration, connection to the manager, and its configuring options in this section of the Wazuh user manual. 
```

2021-07-11 01:42 UTC, santiago-bassett commented on source/amazon/index.rst
> +  :description: Using Wazuh to monitor AWS? Learn how Wazuh helps to increase the security of AWS infrastructure in this section of our documentation.
don't use rhetorical questions in our documentation

2021-07-11 01:44 UTC, santiago-bassett commented on source/docker/docker-installation.rst
> +  :description: Check out this section of the Wazuh documentation to learn about Docker installation: how to install the Docker engine and the Docker compose.
This section does not show how to install Docker compose. Instead it shows how to install the Wazuh solution using Docker compose for the deployment of the Wazuh manager and central components.

2021-07-11 01:45 UTC, santiago-bassett commented on source/getting-started/use_cases/index.rst
> +  :description: Looking to see how the Wazuh capabilities work? Check out some common use cases of Wazuh in this section of our documentation.
Same here, do not use rhetorical questions

2021-07-13 19:46 UTC, MarVergara approved these changes

2021-07-13 19:58 UTC, MarVergara commented on source/amazon/index.rst
> +  :description: Learn how Wazuh helps to increase the security of AWS infrastructure in this section of our documentation.
```suggestion
  :description: Learn how Wazuh helps to increase the security of AWS infrastructure, monitoring AWS instances and AWS services, in this section of our documentation. 
```

2021-07-14 06:51 UTC, merged