Add Firewall Route Logging documentation for the GCP module
wazuh/wazuh-documentation pull request #3912
Opened 2021-06-04 14:10 UTC by CarlosRS9

Hello team,

This PR closes wazuh/wazuh#8714.

This PR adds the documentation page required for theFirewall Route Logging logs for GCP. This new page briefly explains what is Firewall Route Logging, how to enable it and how to export their logs to Pub/Sub via sink.

Regards.

2021-06-07 10:15 UTC, vicferpoy requested changes

2021-06-07 10:15 UTC, vicferpoy commented on source/gcp/supported-services/firewall.rst
> +Firewall Rules Logging can be enabled in the Firewall in the Google Cloud Console. Follow its `official documentation <https://cloud.google.com/vpc/docs/using-firewall-rules-logging#enable>`__ for th
Add a noun after `Firewall`.

2021-06-07 14:07 UTC, CarlosRS9 commented on source/gcp/supported-services/firewall.rst
> +Firewall Rules Logging can be enabled in the Firewall in the Google Cloud Console. Follow its `official documentation <https://cloud.google.com/vpc/docs/using-firewall-rules-logging#enable>`__ for th
Done

2021-06-09 07:53 UTC, davidjiglesias approved these changes

2021-06-09 07:56 UTC, vicferpoy approved these changes
LGTM!

2021-06-09 08:49 UTC, davidfmiranda approved these changes
LGTM

2021-06-09 08:49 UTC, merged