Changing click here Docu 3.13 - Download packages
wazuh/wazuh-documentation pull request #4314
Opened 2021-09-13 17:14 UTC by luiscontrerasdo

## Description

Hello Team!

This PR closes it #4313 

Hi, Team!

Proposing new text for the click here hyperlink text. For all options under: 

_Installation guide -> Installing Wazuh server -> Distro Name -> Distro Name from packages_

Adding the Wazuh repository section:

**Current text:**  If you want to download the wazuh-manager package directly, or check the compatible versions, click [here](https://documentation.wazuh.com/3.10/installation-guide/packages-list/index.html#packages).

**Proposed text:**  You can download the [wazuh-manager package ](https://documentation.wazuh.com/3.10/installation-guide/packages-list/index.html#packages) directly, or check the [compatible versions](https://documentation.wazuh.com/3.10/installation-guide/packages-list/index.html#packages).

Regards,

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2021-09-13 17:17 UTC, vicmansilla approved these changes

2021-09-20 19:20 UTC, MarVergara requested changes
LGTM 👍 after accepting changes we discussed beforehand.

2021-09-20 19:20 UTC, MarVergara commented on source/installation-guide/installing-wazuh-manager/linux/amazon/wazuh_server_packages_amazon.rst
> +The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the :ref:`wazuh-manager package <packages>`  directly, or check the :ref:`compatible versions <packa
```suggestion
The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the wazuh-manager package directly or check the compatible versions in the :ref:`Packages list <packages>` section.
```

2021-09-20 19:20 UTC, MarVergara commented on source/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_packages_centos.rst
> +The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the :ref:`wazuh-manager package <packages>`  directly, or check the :ref:`compatible versions <packa
```suggestion
The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the wazuh-manager package directly or check the compatible versions in the :ref:`Packages list <packages>` section.
```

2021-09-20 19:20 UTC, MarVergara commented on source/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_packages_deb.rst
> +The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the :ref:`wazuh-manager package <packages>`  directly, or check the :ref:`compatible versions <packa
```suggestion
The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the wazuh-manager package directly or check the compatible versions in the :ref:`Packages list <packages>` section.
```

2021-09-20 19:20 UTC, MarVergara commented on source/installation-guide/installing-wazuh-manager/linux/fedora/wazuh_server_packages_fedora.rst
> +The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the :ref:`wazuh-manager package <packages>`  directly, or check the :ref:`compatible versions <packa
```suggestion
The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the wazuh-manager package directly or check the compatible versions in the :ref:`Packages list <packages>` section.
```

2021-09-20 19:20 UTC, MarVergara commented on source/installation-guide/installing-wazuh-manager/linux/opensuse/wazuh_server_packages_opensuse.rst
> +The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the :ref:`wazuh-manager package <packages>`  directly, or check the :ref:`compatible versions <packa
```suggestion
The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the wazuh-manager package directly or check the compatible versions in the :ref:`Packages list <packages>` section.
```

2021-09-20 19:20 UTC, MarVergara commented on source/installation-guide/installing-wazuh-manager/linux/oracle/wazuh_server_packages_oracle.rst
> +The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the :ref:`wazuh-manager package <packages>`  directly, or check the :ref:`compatible versions <packa
```suggestion
The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the wazuh-manager package directly or check the compatible versions in the :ref:`Packages list <packages>` section.
```

2021-09-20 19:20 UTC, MarVergara commented on source/installation-guide/installing-wazuh-manager/linux/rhel/wazuh_server_packages_rhel.rst
> +The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the :ref:`wazuh-manager package <packages>`  directly, or check the :ref:`compatible versions <packa
```suggestion
The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the wazuh-manager package directly or check the compatible versions in the :ref:`Packages list <packages>` section.
```

2021-09-20 19:20 UTC, MarVergara commented on source/installation-guide/installing-wazuh-manager/linux/suse/wazuh_server_packages_suse.rst
> +The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the :ref:`wazuh-manager package <packages>`  directly, or check the :ref:`compatible versions <packa
```suggestion
The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the wazuh-manager package directly or check the compatible versions in the :ref:`Packages list <packages>` section.
```

2021-09-20 19:20 UTC, MarVergara commented on source/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_packages_ubuntu.rst
> +The first step to setting up Wazuh is to add the Wazuh repository to your server. You can download the :ref:`wazuh-manager package <packages>`  directly, or check the :ref:`compatible versions <packa
```suggestion
The first step to setting up Wazuh is to add the Wazuh repository to your server. YYou can download the wazuh-manager package directly or check the compatible versions in the :ref:`Packages list <packages>` section.
```

2021-09-21 18:50 UTC, MarVergara approved these changes

2021-09-21 18:50 UTC, merged