Documented aws module's new role_session_duration parameter
wazuh/wazuh-documentation pull request #4328
Opened 2021-09-15 08:52 UTC by noise-kngdm

## Description
In this PR has been added information regarding the new parameter of the AWS integration module requested in [this issue](https://github.com/wazuh/wazuh/issues/9086).
I have also added information about some of the script's error codes that weren't in the troubleshooting reference, apart from the new ones added.

The results of the changes are the following:
![image](https://user-images.githubusercontent.com/72474806/133401902-f803e6b0-59bd-4661-a80e-063227f68e18.png)
![image](https://user-images.githubusercontent.com/72474806/133402191-2684c92f-3783-4613-a292-b6881e2e09bf.png)
![image](https://user-images.githubusercontent.com/72474806/133402291-91ed3393-aef5-4b4d-a1a4-4fe7baa7ac3a.png)
![image](https://user-images.githubusercontent.com/72474806/133402436-ba7e688f-eb35-4449-b1e7-a53afb527a85.png)

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2021-09-21 07:55 UTC, CarlosRS9 requested changes

2021-09-21 07:55 UTC, CarlosRS9 commented on source/user-manual/reference/ossec-conf/wodle-s3.rst
> +| **Allowed values** | Numbers between 900 and 3600  |
```suggestion
| **Allowed values** | Number of seconds between 900 and 3600  |
```
Remember to adapt the table size after this change

2021-09-23 14:35 UTC, davidjiglesias approved these changes

2021-09-23 15:58 UTC, MarVergara approved these changes
LGTM

2021-09-23 15:58 UTC, merged