Logcollector IP refresh time.
wazuh/wazuh-documentation pull request #4334
Opened 2021-09-16 05:40 UTC by Dwordcito

## Description
This change documents a new internal option for logcollector, basically the option indicates how often the IP is refreshed.

## Checks
- [x] It compiles without warnings.
- [ ] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

## Note to the reviewer

This PR includes changes to the internal options page.

2021-09-16 13:08 UTC, tinachoB approved these changes
LGTM

2021-09-16 13:09 UTC, jnasselle requested changes

2021-09-16 13:09 UTC, jnasselle commented on source/user-manual/reference/internal-options.rst
> ++------------------------------------------+---------------+----------------------------------------------------------------------------+
I think that the next suggestions will be useful
- Link to out_format option
- Warning block
Output preview:
![Screenshot from 2021-09-16 10-08-21](https://user-images.githubusercontent.com/1791430/133617788-8e6727d3-8966-46b0-839d-3618650571db.png)

```suggestion
+------------------------------------------+---------------+----------------------------------------------------------------------------+
| **logcollector.ip_update_interval**      | Description   | IP update interval, in seconds. This specifies how often the system        |
|                                          |               | IP is obtained when the                                                    |
|                                          |               | :ref:`out_format<ossec_localfile_out_format>` option is used.              |
|                                          |               |                                                                            |
|                                          |               | .. versionadded:: 4.3                                                      |
+                                          +---------------+----------------------------------------------------------------------------+
|                                          | Default value | 60                                                                         |
+                                          +---------------+----------------------------------------------------------------------------+
|                                          | Allowed values| 0: Obtain the IP on demand.                                                |
|                                          |               |                                                                            |
|                                          |               | .. warning:: Systems with extensive routing tables                         |
|                                          |               |    can suffer from high CPU usage                                          |
+                                          +               +----------------------------------------------------------------------------+
|                                          |               | Any other integer between 1 and 3600.                                      |
+------------------------------------------+---------------+----------------------------------------------------------------------------+
```

2021-09-16 14:44 UTC, jnasselle approved these changes

2021-09-21 15:07 UTC, MarVergara requested changes
LGTM from my side after applying the changes I requested.

2021-09-21 18:34 UTC, MarVergara approved these changes
LGTM

2021-09-21 18:34 UTC, merged