Add information about the use of AWS FIPS endpoints
wazuh/wazuh-documentation pull request #4389
Opened 2021-09-23 17:15 UTC by noise-kngdm

## Description
We add information regarding the possibility of using FIPS endpoints with the AWS integration modules after the request made in [this issue](https://github.com/wazuh/wazuh/issues/9087).

The results of the changes are the following:
![image](https://user-images.githubusercontent.com/72474806/134553200-53fc01db-638e-4f52-9883-f00df0ffa050.png)
![image](https://user-images.githubusercontent.com/72474806/134553250-0ad4b8f2-d82b-49eb-9112-da2b2b9684d5.png)
![image](https://user-images.githubusercontent.com/72474806/134553329-11360e83-b748-4e26-a358-9559a78a49b6.png)
![image](https://user-images.githubusercontent.com/72474806/134553352-b310d388-fc3f-4d83-9298-40d733ea1101.png)

## Checks
- [ ] It compiles without warnings.
- [ ] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

## Note to the reviewer

This PR includes changes to the `redirect.js` script that need to be included in all production branches.

2021-09-28 08:25 UTC, CarlosRS9 requested changes

2021-09-28 08:25 UTC, CarlosRS9 commented on source/user-manual/reference/ossec-conf/wodle-s3.rst
> +The VPC endpoint URL for the required AWS Service to be used to download the data from it. Check the :ref:`Considerations for configuration <amazon_considerations>` page to learn more about VPC and F
```suggestion
The endpoint URL for the required AWS Service to be used to download the data from it. Check the :ref:`Considerations for configuration <amazon_considerations>` page to learn more about VPC and FIPS endpoints.
```

2021-09-28 08:25 UTC, CarlosRS9 commented on source/amazon/services/prerequisites/considerations.rst
> +Wazuh supports the use of AWS FIPS endpoints for users that need to comply with the `Federal Information Processing Standard (FIPS) Publication 140-2 <https://csrc.nist.gov/publications/detail/fips/1
```suggestion
Wazuh supports the use of AWS FIPS endpoints to comply with the `Federal Information Processing Standard (FIPS) Publication 140-2 <https://csrc.nist.gov/publications/detail/fips/140/2/final>`_. Depending on the service and region of choice, a different endpoint must be taken from the `AWS FIPS endpoints list <https://aws.amazon.com/compliance/fips/>`_. Once chosen the desired endpoint, it must be specified in the ``ossec.conf`` file using the ``service_endpoint`` tag.
```

2021-09-29 07:36 UTC, davidjiglesias approved these changes

2021-09-29 17:22 UTC, s-ocando commented on source/amazon/services/prerequisites/considerations.rst
> +Wazuh supports the use of AWS FIPS endpoints to comply with the `Federal Information Processing Standard (FIPS) Publication 140-2 <https://csrc.nist.gov/publications/detail/fips/140/2/final>`_. Depen
```suggestion
Wazuh supports the use of AWS FIPS endpoints to comply with the `Federal Information Processing Standard (FIPS) Publication 140-2 <https://csrc.nist.gov/publications/detail/fips/140/2/final>`_. Depending on the service and region of choice, a different endpoint must be selected from the `AWS FIPS endpoints list <https://aws.amazon.com/compliance/fips/>`_. Specify the selected endpoint in the ``ossec.conf`` file using the ``service_endpoint`` tag.
```

2021-09-29 17:22 UTC, s-ocando commented on source/amazon/services/prerequisites/considerations.rst
> +An example of a valid configuration would be the following:
```suggestion
The following is an example of a valid configuration.
```

2021-09-30 15:58 UTC, s-ocando approved these changes
LGTM

2021-09-30 15:59 UTC, merged