Migrate Agent Key Polling to Authd module
wazuh/wazuh-documentation pull request #4461
Opened 2021-10-14 16:06 UTC by juanmanuelug

## Description
|Related issue|
|---|
|[#4422](https://github.com/wazuh/wazuh-documentation/issues/4422)|

Hi team,

With the port of the Agent Key Polling module to the Authd module, Wazuh´s needs to be updated to remove the outdated references to the Key polling module and add the needed references to the Authd documentation.

The main points to cover include:

- [x] Modify the description, the general diagram and the section [How it works](https://documentation.wazuh.com/current/user-manual/capabilities/agent-key-polling.html).
- [x] Remove the [agent-key-polling references in wazuh-modulesd](https://documentation.wazuh.com/current/user-manual/reference/daemons/wazuh-modulesd.html) and add them in authd.
- [x] Modify the [configuration](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-agent-key-polling.html) with the one added in authd.
- [x] Remove agent-key-polling [configuration reference](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/index.html) .
- [x] Updated redirects.js

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns.

2021-11-18 08:36 UTC, chemamartinez requested changes

2021-11-18 08:44 UTC, chemamartinez approved these changes

2021-11-18 09:29 UTC, alromeros approved these changes
LGTM!

2022-01-25 10:32 UTC, chemamartinez commented
Do not merge this pull request until `develop` is referring to version 4.4.

2022-04-20 10:13 UTC, chemamartinez commented
The core development was already merged https://github.com/wazuh/wazuh/pull/10865.

2022-09-05 15:14 UTC, s-ocando reviewed
Please review the following suggestions.

2022-09-05 15:14 UTC, s-ocando commented on source/user-manual/agents/key-request.rst
> +When fetching by IP address, the manager will retrieve the agent key by querying his IP address. So the input parameters that the program will receive are as the following:
```suggestion
When fetching by IP address, the manager retrieves the agent key by querying his IP address. The input parameters that the program receives are as the following:
```

2022-09-05 15:14 UTC, s-ocando commented on source/user-manual/agents/key-request.rst
>  When polling by ID, the manager will retrieve the agent key by querying its ID. So the input parameters that the program will receive are as the following:
```suggestion
When polling by ID, the manager retrieves the agent key by querying its ID. The input parameters that the program receives are as the following:
```

2022-09-05 15:14 UTC, s-ocando commented on source/user-manual/agents/key-request.rst
> +The format in which the program will receive the data is ``option:value``, where option can be ``id`` or ``ip`` depending on the fetching type.
```suggestion
The format in which the program receives the data is ``option:value``, where option can be ``id`` or ``ip`` depending on the fetching type.
```

2022-09-06 07:14 UTC, s-ocando approved these changes

2022-09-06 07:16 UTC, merged