Add meta description to some pages
wazuh/wazuh-documentation pull request #4534
Opened 2021-11-11 14:21 UTC by PilarQuesada

Hi team, this PR closes #4533 

## Description
I have added a meta description to several pages of the documentation. 

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

Regards!

2021-11-15 18:47 UTC, Arcapas commented on source/amazon/services/prerequisites/considerations.rst
> +  :description: In this section we show you some considerations that must be taken into account when configuring the Wazuh module for AWS.
```suggestion
  :description: In this section, we show you some considerations that must be taken into account when configuring the Wazuh module for AWS.
```

2021-11-15 18:52 UTC, Arcapas commented on source/deploying-with-ansible/roles/wazuh-filebeat.rst
> +  :description: Filebeat can be used in conjunction with Wazuh Manager to send events and alerts to Elasticsearch. Learn how to customize the installation here.
```suggestion
  :description: Filebeat is used in conjunction with Wazuh Manager to send events and alerts to Elasticsearch. Learn how to customize the installation here.
```

2021-11-15 18:57 UTC, Arcapas commented on source/development/packaging/index.rst
> +  :description: Learn more about how to generate your own Wazuh packages for different platforms, such as Debian, macOS, Windows, Splunk App and others.
```suggestion
  :description: Learn more about how to generate your own Wazuh packages for different platforms, such as Debian, macOS, Windows, Splunk App, and others.
```

2021-11-15 18:58 UTC, Arcapas commented on source/development/packaging/index.rst
> +  :description: Learn more about how to generate your own Wazuh packages for different platforms, such as Debian, macOS, Windows, Splunk App and others.
```suggestion
  :description: Learn more about how to generate your own Wazuh packages for different platforms, such as Debian, macOS, Windows, Splunk App, and others.
```

2021-11-15 19:04 UTC, Arcapas commented on source/docker/upgrade-guide.rst
> +  :description: Docker is an open source project that automates the deployment of different applications inside software containers. Learn more about the upgrade guide here.
```suggestion
  :description: Docker, an open source project that automates the deployment of different applications inside software containers. Learn more about it here. 
```

2021-11-15 19:10 UTC, Arcapas commented on source/pci-dss/file-integrity-monitoring.rst
> +  :description: Wazuh helps to implement PCI DSS by performing file integrity checking, among other capabilities. Check out some use cases in this section of our documentation.
```suggestion
  :description: Wazuh helps to implement PCI DSS by performing file integrity checking, among other capabilities. Check out some use cases in this section.
```

2021-11-16 11:00 UTC, Arcapas commented on source/pci-dss/rootkit-detection.rst
> +  :description: PCI DSS is a proprietary information security standard for organizations that handle branded credit cards. Learn more about rootkit detection to use Wazuh for PCI DSS compliance.
```suggestion
  :description: Wazuh rootkit detection helps you to meet PCI DSS requirements related to intrusions and malware in general. Learn more about this subject here.
```

2021-11-16 11:12 UTC, Arcapas commented on source/user-manual/capabilities/agentless-monitoring/agentless-configuration.rst
> +  :description: Learn more about the agentless monitoring configuration: integrity check BSD, integrity check Linux, generic diff, and pix config. Learn more here.
```suggestion
  :description: Learn how agentless monitoring can help you monitor systems with no agent via SSH, such as routers, firewalls, switches, and Linux/BSD systems.  
```

2021-11-16 11:29 UTC, Arcapas commented on source/user-manual/capabilities/wazuh-logtest/how-it-works.rst
> +  :description: The Wazuh-Logtest whole solution was designed to replace ossec-logtest, now allowing to test and verify rules and decoders remotely. Learn how it works here.
```suggestion
  :description: The Wazuh-Logtest solution was designed to replace ossec-logtest. It allows to test and verify rules and decoders remotely. Learn how it works here. 
```

2021-11-16 11:31 UTC, Arcapas commented on source/user-manual/capabilities/wazuh-logtest/index.rst
> +  :description: The Wazuh-Logtest whole solution was designed to replace ossec-logtest, now allowing to test and verify rules and decoders remotely. Learn more about it here.
```suggestion
  :description: The Wazuh-Logtest solution was designed to replace ossec-logtest. It allows to test and verify rules and decoders remotely. Learn how it works here. 
```

2021-11-16 12:11 UTC, Arcapas commented on source/user-manual/capabilities/wazuh-logtest/logtest-configuration.rst
> +  :description: The Wazuh-Logtest whole solution was designed to replace ossec-logtest, now allowing to test and verify rules and decoders remotely. Learn more about it here.
```suggestion
  :description: The Wazuh-Logtest solution was designed to replace ossec-logtest. It allows to test and verify rules and decoders remotely. Learn how it works here. 
```

2021-11-16 12:25 UTC, Arcapas commented on source/user-manual/kibana-app/features/settings.rst
> +  :description: The Wazuh Kibana plugin gives you a quick view of your cluster, agents and alerts. Learn more about the Settings page in this section. This page allows you to configure and customize
```suggestion
  :description: The Wazuh Kibana plugin gives you a quick view of your agents, alerts, and cluster. Learn more about the Settings page in this section. 
```

2021-11-16 13:24 UTC, Arcapas commented on source/user-manual/reference/ossec-conf/commands.rst
> +  :description: Learn more about the command configuration section. Check out the options and a sample configuration in this section of our documentation.
```suggestion
  :description: In the command configuration section, a command is defined that will be used by one or more active responses. Check out the options here.  
```

2021-11-16 13:24 UTC, Arcapas commented on source/user-manual/reference/ossec-conf/commands.rst
> +  :description: Learn more about the command configuration section. Check out the options and a sample configuration in this section of our documentation.
```suggestion
  :description: In the command configuration section, a command is defined that will be used by one or more active responses. Check out the options here.  
```

2021-11-16 13:26 UTC, Arcapas commented on source/user-manual/reference/ossec-conf/email_alerts.rst
> +  :description: Check out more about the local configuration of Wazuh. In this section, you can learn more about the email options configured in the <global> section.
```suggestion
  :description: Check out more about the local configuration of Wazuh. You can learn more about the email options configured in the <global> section in this section. 
```

2021-11-16 13:28 UTC, Arcapas commented on source/user-manual/reference/ossec-conf/email_alerts.rst
> +  :description: Check out more about the local configuration of Wazuh. You can learn more about the email options configured in the <global> section in this section.
```suggestion
  :description: Check out more about the local configuration of Wazuh. You can learn more about the email options configured in the <global> section here. 
```

2021-11-16 13:32 UTC, Arcapas commented on source/user-manual/reference/ossec-conf/reports.rst
> +  :description: Learn more about the different options for the configuration of daily reports based on alerts in this section of the Wazuh documentation.
```suggestion
  :description: Learn more about the different options for configuring daily reports based on alerts in this section of the Wazuh documentation.  
```

2021-11-16 13:33 UTC, Arcapas commented on source/user-manual/reference/ossec-conf/reports.rst
> +  :description: Learn more about the different options for the configuration of daily reports based on alerts in this section of the Wazuh documentation.
```suggestion
  :description: Learn more about the different options for configuring daily reports based on alerts in this section of the Wazuh documentation.  
```

2021-11-16 13:41 UTC, Arcapas approved these changes
LGTM

2021-11-25 11:13 UTC, MarVergara commented on source/deploying-with-ansible/reference.rst
> +  :description: Ansible is an open source platform designed for automating tasks. Learn more about the variable references in this section.
```suggestion
  :description: Ansible is an open source platform designed for automating tasks. Learn more about the variable references in this section of the Wazuh documentation.
```

2021-11-25 11:14 UTC, MarVergara commented on source/deploying-with-ansible/roles/wazuh-filebeat.rst
> +  :description: Filebeat is used in conjunction with Wazuh Manager to send events and alerts to Elasticsearch. Learn how to customize the installation here.
```suggestion
  :description: Filebeat is used in conjunction with the Wazuh manager to send events and alerts to Elasticsearch. Learn how to customize the installation here.
```

2021-11-25 11:29 UTC, MarVergara commented on source/development/makefile.rst
> +  :description: This section contains instructions to customize the installation from Wazuh by compiling the source code before executing the installation script.
```suggestion
  :description: This section contains instructions to customize the installation of Wazuh by compiling the source code before executing the installation script. 
```

2021-11-25 12:23 UTC, MarVergara commented on source/development/packaging/index.rst
> +  :description: Learn more about how to generate your own Wazuh packages for different platforms, such as Debian, macOS, Windows, Splunk App, and others.
```suggestion
  :description: Learn more about how to generate your own Wazuh packages for different platforms, such as Debian, macOS, Windows, Splunk app, and others.
```

2021-11-25 13:12 UTC, MarVergara commented on source/user-manual/capabilities/wazuh-logtest/index.rst
> +  :description: The Wazuh-Logtest solution was designed to replace ossec-logtest. It allows to test and verify rules and decoders remotely. Learn how it works here.
```suggestion
  :description: The Wazuh-Logtest solution was designed to replace ossec-logtest. It allows you to test and verify rules and decoders remotely. Learn more about it here. 
```

2021-11-25 13:13 UTC, MarVergara commented on source/user-manual/capabilities/wazuh-logtest/logtest-configuration.rst
> +  :description: The Wazuh-Logtest solution was designed to replace ossec-logtest. It allows to test and verify rules and decoders remotely. Learn how it works here.
```suggestion
  :description: The Wazuh-Logtest solution was designed to replace ossec-logtest. It allows you to test and verify rules and decoders remotely. Learn how it works here. 
```

2021-11-25 13:15 UTC, MarVergara commented on source/user-manual/kibana-app/features/settings.rst
> +  :description: The Wazuh Kibana plugin gives you a quick view of your agents, alerts, and cluster. Learn more about the Settings page in this section.
```suggestion
  :description: The Wazuh Kibana plugin gives you a quick view of your agents, alerts, and cluster. Learn how to configure its features in this section. 
```

2021-11-25 13:17 UTC, MarVergara commented on source/user-manual/reference/ossec-conf/agentless.rst
> +  :description: The agentless monitoring allows you to run integrity checks on systems without an agent installed. Check out this section of the Wazuh documentation.
```suggestion
  :description: Wazuh agentless monitoring allows you to run integrity checks on systems without an agent installed. Check out this section of the documentation. 
```

2021-11-25 13:20 UTC, MarVergara commented on source/user-manual/reference/ossec-conf/commands.rst
> +  :description: In the command configuration section, a command is defined that will be used by one or more active responses. Check out the options here.
```suggestion
  :description: Wazuh allows you to configure commands to be used by one or more active responses. Check out the options in this section of the documentation. 
```

2021-11-25 13:31 UTC, MarVergara commented on source/user-manual/reference/ossec-conf/integration.rst
> +  :description: Learn how to configure the manager to connect Wazuh to external APIs. Check out the options, optional filters, and a configuration example.
```suggestion
  :description: Learn how to configure the manager to connect Wazuh to external APIs. Check out the options, optional filters, and configuration examples. 
```

2021-11-25 13:41 UTC, MarVergara commented on source/user-manual/reference/ossec-conf/sca.rst
> +  :description: Learn more about the configuration of the Security Configuration Assessment module. Check out the options and a simple configuration in this section.
```suggestion
  :description: Learn more about the configuration of the Security Configuration Assessment module in the Wazuh documentation. Check out the options and a sample configuration. 
```

2021-11-25 13:52 UTC, MarVergara commented on source/user-manual/reference/tools/index.rst
> +  :description: Check out our user manual to find out how to configure and use each of the Wazuh components. In this section, you can learn more about the tools.
```suggestion
  :description: Check out our User manual to see the available tools and their supported installations for configuring and using each of the Wazuh components. 
```

2021-11-25 14:14 UTC, MarVergara requested changes
@Arcapas, 
I leave some comments below that need attention before approving this PR.
Could you please take a look at them?
Thank you!

2021-11-25 14:14 UTC, MarVergara commented on source/user-manual/reference/ossec-conf/email_alerts.rst
> +  :description: Check out more about the local configuration of Wazuh. You can learn more about the email options configured in the <global> section here.
I'd rewrite this meta. The second sentence is not descriptive enough and the meaning is not clear.

2021-11-25 14:14 UTC, MarVergara commented on source/user-manual/reference/ossec-conf/wodle-command.rst
> +  :description: Learn more about the Wazuh local configuration, including configuration sections and supported installations, in this section of our documentation.
I'd rewrite this meta since the content is not consistent with the topic of this section.

2021-11-25 15:13 UTC, Arcapas commented on source/docker/upgrade-guide.rst
> +  :description: Docker, an open source project that automates the deployment of different applications inside software containers. Learn more about it here.
Sentence changed by:

.. meta::
  :description: With Docker, you can automate the deployment of applications inside containers. Learn about the upgrade of a cluster running version previous to 4.0 here.

2021-11-26 11:52 UTC, MarVergara commented on source/user-manual/reference/ossec-conf/sca.rst
> +  :description: Learn more about the configuration of the Security Configuration Assessment module in the Wazuh documentation. Check out the options and a sample configuration.
```suggestion
  :description: Learn more about the configuration of the Security Configuration Assessment module. Check out the options and a sample configuration in this section.
```

2021-11-26 13:40 UTC, MarVergara approved these changes

2021-11-26 14:04 UTC, MarVergara approved these changes
LGTM

2021-11-26 15:07 UTC, merged