Fix AWS load balancers `Path to logs` value and add footnote
wazuh/wazuh-documentation pull request #4633
Opened 2021-11-24 12:13 UTC by noise-kngdm

| Related issue|
|--|
|Closes #4512|

## Description
In this PR we fix the `Path to logs` value of the `ALB`, `NLB`, and  `CLB` buckets in the `amazon/services/supported-services/index.html` page. We also add a footnote explaining the meaning of that column. The results of the additions are the following:
![fixed path](https://user-images.githubusercontent.com/72474806/143235924-9b53a211-a53f-4370-86ce-0dbf5c2969e6.png)
![footnote](https://user-images.githubusercontent.com/72474806/143235952-4eaad955-33da-4141-96e3-9c10605361c4.png)

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2021-12-16 16:37 UTC, CarlosRS9 requested changes

2021-12-16 16:37 UTC, CarlosRS9 commented on source/amazon/services/supported-services/index.rst
> +.. [#path]
Remove this and instead expand the paragraph before the table, adding a similar explanation for the path column

2021-12-16 17:00 UTC, CarlosRS9 approved these changes

2021-12-17 09:54 UTC, davidjiglesias approved these changes

2022-01-13 10:16 UTC, s-ocando approved these changes
LGTM

2022-01-13 10:16 UTC, merged