Update all references to the changed API configuration parameters
wazuh/wazuh-documentation pull request #4684
Opened 2021-12-20 15:58 UTC by vicferpoy

## Description

As part of https://github.com/wazuh/wazuh/issues/11409, we have changed some options of the API configuration:

- `logs > path`: Deprecated
- `https > key`: Changed
- `https > cert`: Changed
- `https > ca`: Changed

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2021-12-20 16:39 UTC, mcarmona99 approved these changes
LGTM

2021-12-27 11:22 UTC, davidjiglesias requested changes

2021-12-27 11:22 UTC, davidjiglesias commented on source/user-manual/api/getting-started.rst
> +- The Wazuh API log is stored on the manager as ``/var/ossec/logs/api.log`` (the verbosity level can be changed in the Wazuh API configuration file). The Wazuh API logs are rotated daily. Rotated log
```suggestion
- The Wazuh API log is stored on the manager as ``/var/ossec/logs/api.log`` (the verbosity level can be changed in the Wazuh API configuration file). The Wazuh API logs are rotated daily. Rotated logs are stored in ``WAZUH_PATH/logs/api/<year>/<month>`` and compressed using ``gzip``.
```

2021-12-27 11:41 UTC, davidjiglesias approved these changes

2022-01-12 09:08 UTC, s-ocando approved these changes
LGTM

2022-01-12 09:09 UTC, merged