Update agent-groups information in cluster docu
wazuh/wazuh-documentation pull request #4923
Opened 2022-03-10 09:28 UTC by Selutario

| Related issue |
|--|
| Closes #4606 |

## Description

This PR adds information about the new `agent-groups` sync tasks in the cluster, which were developed at 
- https://github.com/wazuh/wazuh/issues/10771

## Checks
- [x] It compiles without warnings.
- [ ] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2022-03-11 14:40 UTC, yanazaeva approved these changes
LGTM

2022-03-14 08:22 UTC, davidjiglesias approved these changes

2022-04-26 12:29 UTC, AdriiiPRodri requested changes
This image https://github.com/wazuh/wazuh-documentation/blob/af51377a36568ab031aa604d3a4b3db1dee1c568/source/images/manual/cluster/cluster_flow.png seems to have a background, unlike the previous one, is this correct for dark mode?

2022-04-26 12:29 UTC, AdriiiPRodri commented on source/development/wazuh-cluster.rst
>  | ``sendsync``      | Master      | - Arguments<Dict>     | Receive a message from a worker node destined for the specified daemon of the master node.      |
We should add the new agent-groups commands

2022-05-06 15:16 UTC, merged