source/user-manual/capabilities: update CIS-CAT documents to support both v3 and v4
wazuh/wazuh-documentation pull request #4976
Opened 2022-03-30 06:37 UTC by hustliyilin

Signed-off-by: YiLin.Li <YiLin.Li@linux.alibaba.com>

## Description

## Checks
- [ ] It compiles without warnings.
- [ ] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [ ] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

## Note to the reviewer

This PR includes changes to the `redirect.js` script that need to be included in all production branches.

2022-04-04 08:20 UTC, vikman90 requested changes
@hustliyilin Thank you so much for this PR. 

I've made some suggestions for minor changes. Please review them and apply them if you agree.

Cheers!

2022-04-04 08:43 UTC, hustliyilin commented
> @hustliyilin Thank you so much for this PR.
> 
> I've made some suggestions for minor changes. Please review them and apply them if you agree.
> 
> Cheers!

Hi @vikman90 ,

Thank you very much. I already modified the codes according to your review.

2022-04-04 08:51 UTC, vikman90 approved these changes
Thank you @hustliyilin.
We're just awaiting another review by @s-ocando, then we will merge both PRs!

Thank you very much for your contribution!
Best regards.

2022-04-20 11:59 UTC, vikman90 requested changes
Hi @hustliyilin, we have this feedback from @s-ocando. Please take a look on that and fix it if you agree.

Best regards.

2022-04-20 11:59 UTC, vikman90 commented on source/user-manual/reference/ossec-conf/wodle-ciscat.rst
> +| `ciscat_binary`_     | Any valid path                                             |
Seems like if the allowed values column was switched.

```suggestion
| `ciscat_path`_       | Any valid path                                             |
+----------------------+------------------------------------------------------------+
| `ciscat_binary`_     | CIS-CAT.sh, CIS-CAT.BAT, Assessor-CLI.sh, Assessor-CLI.bat |
```

2022-04-20 14:19 UTC, hustliyilin commented
> Hi @hustliyilin, we have this feedback from @s-ocando. Please take a look on that and fix it if you agree.
> 
> Best regards.

Hi @vikman90 ,

Thank you very much. I already modified the codes according to your review and rebased to the newest base branch to fix the conflicts.

2022-04-20 14:51 UTC, vikman90 approved these changes
Looks good to me!

2022-04-20 16:14 UTC, hustliyilin commented
> Looks good to me!

Thanks  very much @vikman90 ! Cloud you review it again @s-ocando ? Thanks a lot.

2022-04-20 18:39 UTC, s-ocando approved these changes
LGTM. Thank you very much @hustliyilin for your contribution!

2022-04-20 18:39 UTC, merged