4.3.0 Getting started enhancement
wazuh/wazuh-documentation pull request #5002
Opened 2022-03-31 16:25 UTC by Arcapas

This PR aims to perform a 4.3.0 Getting started enhancement:

## Tasks:

- [x] Work on the branch `4.3.0-getting-started-enhancement-v1.0`
- [x] Perform the tasks listed on Stage 1 of issue #4989

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

Regards,
Damian Furfuro

2022-04-12 19:37 UTC, javimed requested changes

2022-04-12 19:37 UTC, javimed commented on source/getting-started/use-cases/log-analysis.rst
> +Rules include a ``match`` field used to define the pattern that the rule search. They also have a ``level`` field that specifies the priority of the resulting alerts. Besides, rules enrich events wit
```suggestion
Rules include a ``match`` field used to define the pattern that the rule looks for. They also have a ``level`` field that specifies the priority of the resulting alerts. Besides, rules enrich events with technique identifiers from the MITRE ATT&CK framework and mappings to regulatory compliance controls.
```

2022-04-12 19:37 UTC, javimed commented on source/getting-started/use-cases/regulatory-compliance.rst
> +The Wazuh platform is often used to meet the technical aspects of regulatory compliance standards. Wazuh uses its SIEM capabilities to centralize, analyze, and enrich security data and provide securi
```suggestion
Wazuh uses its SIEM capabilities to centralize, analyze and enrich security data. In addition, it provides security controls, such as intrusion detection, configuration assessment, log analysis, and vulnerability detection, to meet the technical aspects of regulatory compliance standards.
```

2022-04-13 11:37 UTC, Arcapas reviewed
LGTM

2022-04-13 13:08 UTC, javimed commented on source/getting-started/components/wazuh-server.rst
> +- **Analysis engine:** This is the server component that performs the data analysis. It employs decoders to identify the information processing type (Windows events, SSHD logs, web server logs, and o
```suggestion
- **Analysis engine:** This is the server component that performs the data analysis. It employs decoders to identify the type of information in process (Windows events, SSHD logs, web server logs, and others). These decoders also extract relevant data elements from the log messages, such as source IP address, event ID, or username. Then, by using rules, the engine identifies specific patterns in the decoded events that could trigger alerts and possibly even call for automated countermeasures, like banning an IP address on the firewall, for example.
```

2022-04-13 13:48 UTC, merged