Core dump guide for GNU/Linux
wazuh/wazuh-documentation pull request #5161
Opened 2022-05-03 13:32 UTC by jnasselle

|Related issue|
|---|
| Closes #4911 |
## Description

This PR aims to create a Development Guide for Core dumps on GNU/Linux.

## Checks
- [X] It compiles without warnings.
- [x] Spelling and grammar. 
- [ ] Used impersonal speech. 
- [] Used uppercase only on nouns. 
- [x] ~Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).~

2022-05-06 15:20 UTC, HanesSciarrone requested changes

2022-05-06 15:20 UTC, HanesSciarrone commented on source/development/core-dumps-generation.rst
> +
IMHO I would create a new section about how to use GDB with the debugging information in separate files.

2022-05-12 16:18 UTC, MiguelazoDS commented on source/development/core-dumps-generation.rst
> +Since GNU/Linux distributions might use different approaches, the first step is to determine what is being used and therefore apply some modifications to be able to capture Wazuh coredumps.
`core dumps` instead of `coredumps`.

2022-05-12 16:18 UTC, MiguelazoDS commented on source/development/core-dumps-generation.rst
> +Apport service should be also started to capture coredumps
core dumps instead of coredumps.

2022-05-12 16:22 UTC, MiguelazoDS commented on source/development/core-dumps-generation.rst
> +- Naming of core dump files: create dumps using default ``core.pid`` or templatized core dumps filenames using substitutions.
I think the proper term is `templetized`

2022-05-17 14:04 UTC, HanesSciarrone approved these changes

2022-05-18 03:17 UTC, Dwordcito commented on source/development/core-dumps-generation.rst
> +resource limit you need to change is the "cores" one, which represents the maximum size of core dumps our process is
```suggestion
resource limit you need to change is the "cores" one, which represents the maximum size of core dumps our process 
```

2022-05-18 03:17 UTC, Dwordcito commented on source/development/core-dumps-generation.rst
>  To enable core dumps in macOS, you need to change the resource limits of a process using `ulimit`.  In this case, the
```suggestion
To enable core dumps on macOS, you need to change the resource limits of a process using `ulimit`.  In this case, the
```

2022-05-18 03:17 UTC, Dwordcito commented on source/development/core-dumps-generation.rst
> +Debugging symbols are created separately by default and they are available to download at our
```suggestion
Debugging symbols are created separately by default, and they are available to download at our
```

2022-05-18 13:13 UTC, jnasselle commented on source/development/core-dumps-generation.rst
> +resource limit you need to change is the "cores" one, which represents the maximum size of core dumps our process is
The full line needs that `is`
```
In this case, the
resource limit you need to change is the "cores" one, which represents the maximum size of core dumps our process is allowed to generate.
```

2022-05-18 13:30 UTC, Dwordcito approved these changes

2022-05-18 15:52 UTC, MiguelazoDS approved these changes

2022-05-19 12:07 UTC, merged