Remove API endpoints equivalence table from `Migrating from the Wazuh API 3.X`
wazuh/wazuh-documentation pull request #5217
Opened 2022-05-10 11:37 UTC by mcarmona99

## Description

This PR closes https://github.com/wazuh/wazuh-documentation/issues/5210.

In this pull request, I have removed the equivalence table from the `Migrating from the Wazuh API 3.X` section.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2022-05-10 13:53 UTC, vicferpoy requested changes
Missing changes on `redirect.js`.

> **EDIT:** It was not necessary. The page will remain.

2022-05-10 14:06 UTC, vicferpoy approved these changes
LGTM

2022-05-11 06:40 UTC, s-ocando commented on source/user-manual/api/equivalence.rst
> +However, it is easy to create new users and assign the administrator role to them with the following API requests (substitute <username> and <password>):
```suggestion
However, it is easy to create new users and assign them the administrator role with the following API requests (substitute <username> and <password>):
```

2022-05-11 06:43 UTC, s-ocando approved these changes
LGTM

2022-05-11 06:43 UTC, merged