Improve CPE Helper with new update field
wazuh/wazuh-documentation pull request #5369
Opened 2022-06-23 12:47 UTC by MarcelKemp

## Description

|Related issue|
|---|
|closes #5295|

After adding the update field in the CPE Helper, it has been necessary to update the Wazuh documentation to include the new options, variables and entries, reflecting the new functionalities.

To do so, the following points have been implemented:

- [x] Include in the "**_CPE Helper Schema_**" section the new optional field `update`, both for source and translation.
- [x] Add the two new options: `set_update_if_product_matches` and `set_update_only_if_product_matches`. In the "**_Translation types_**" section.
- [x] Adding a section reflecting the example of the software product "Microsoft Exchange Server", where the added functionalities are used (translation with the use of the `update` field, use of the variable `$UPDATE` extracted from the regex using the action `set_update_if_product_match` and example of a vulnerability _CVE-2022-23277_ affected by the package).

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns.

2022-07-07 12:14 UTC, chemamartinez requested changes

2022-07-07 12:14 UTC, chemamartinez commented on source/user-manual/capabilities/vulnerability-detection/cpe-helper.rst
> +Where we can observe, that in the CPEs the version and update fields are specified with generic versions that do not allow us
I'd try to reorganize this sentence to make it sound less colloquial. In addition, I don't understand the `generic versions` meaning, they seem specific versions.

2022-07-07 12:14 UTC, chemamartinez commented on source/user-manual/capabilities/vulnerability-detection/cpe-helper.rst
> +where we can know the patches that fix the vulnerability for the *Microsoft Exchange Server* product.
```suggestion
where we can find the patches that fix the vulnerability for the *Microsoft Exchange Server* product.
```

2022-07-07 12:14 UTC, chemamartinez commented on source/user-manual/capabilities/vulnerability-detection/cpe-helper.rst
> +As in the previous use case, we will activate the ``check_hotfix`` action to automate this search,
```suggestion
As explained in the previous use case, we have to include the ``check_hotfix`` action to automate this search,
```

2022-07-07 12:14 UTC, chemamartinez commented on source/user-manual/capabilities/vulnerability-detection/cpe-helper.rst
> +in addition to following the same guide used for the other use cases explained.
```suggestion
as well as following the same guide used for the previous use case.
```

2022-07-07 12:14 UTC, chemamartinez commented on source/user-manual/capabilities/vulnerability-detection/cpe-helper.rst
> +  the ``set_update_if_product_match`` option to add the *update* field to differentiate between the CPEs, as there will be
three `to` in the same sentence is difficult to read, let's try something like:
```
In this case, we need to add the ``set_update_if_product_match`` action so the *update* field is included in the CPE to match the one provided by the NVD

2022-07-07 12:14 UTC, chemamartinez commented on source/user-manual/capabilities/vulnerability-detection/cpe-helper.rst
> +  Alert example using this dictionary entry:
```suggestion
Once applied the entry in the CPE helper and the scanner detects it, its vulnerabilities are reported:
```

2022-07-07 12:14 UTC, chemamartinez commented on source/user-manual/capabilities/vulnerability-detection/cpe-helper.rst
> +  The resulting dictionary entry, including more versions of *Microsoft Exchange Server*:
```suggestion
Here we have the CPE helper entry needed to detect vulnerabilities of the *Microsoft Exchange Server* program:
```

2022-07-08 14:57 UTC, chemamartinez approved these changes

2022-09-13 15:43 UTC, chemamartinez approved these changes

2022-09-14 21:06 UTC, javimed commented
Further work specified in https://github.com/wazuh/wazuh-documentation/issues/5581

2022-09-15 07:27 UTC, chemamartinez approved these changes
LGTM!

2022-09-15 14:01 UTC, javimed approved these changes

2022-09-16 09:17 UTC, merged