Documentation SemRush issues: July 2022 v3
wazuh/wazuh-documentation pull request #5453
Opened 2022-07-08 17:27 UTC by Arcapas

## Description
This PR aims to list and correct the Wazuh documentation SemRush issues for July 2022.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2022-07-08 17:45 UTC, Arcapas reviewed
LGTM

2022-08-09 18:34 UTC, javimed requested changes

2022-08-09 18:34 UTC, javimed commented on source/deployment-options/splunk/splunk-app.rst
> +   :description: Splunk for Wazuh installation guide.
```suggestion
   :description: Wazuh installation guide for Splunk.
```

2022-08-09 18:34 UTC, javimed commented on source/deployment-options/splunk/splunk-polling.rst
> +   :description: Splunk for Wazuh installation guide
```suggestion
   :description: Learn how to customize the polling of the agents status data in a Wazuh for Splunk installation in this section of the documentation.
```

2022-08-09 18:34 UTC, javimed commented on source/deployment-options/splunk/splunk-rbac.rst
> +   :description: Create and map users in the Wazuh app for Splunk
```suggestion
   :description: Create and map users in a Wazuh with Splunk installation.
```

2022-08-09 18:34 UTC, javimed commented on source/deployment-options/splunk/splunk-reverse-proxy.rst
> +   :description: Splunk for Wazuh installation guide
```suggestion
   :description: Learn how to place Splunk web behind a proxy with an NGINX setup in this section of the documentation.
```

2022-08-09 18:34 UTC, javimed commented on source/deployment-options/splunk/splunk-wazuh.rst
> +   :description: Learn how to install Elastic Stack for using Wazuh on Debian
```suggestion
   :description: Install the Wazuh manager for a Wazuh with Splunk installation
```

2022-08-09 18:34 UTC, javimed commented on source/getting-started/use-cases/file-integrity.rst
> +   :description: File Integrity Monitoring is one of the key capabilities of Wazuh. In this section, we show you an example of an alert generated when a monitored file changes. Check it out here.
```suggestion
   :description: Check an example of an alert generated when a monitored file changes using the FIM capability in this section of the documentation.
```

2022-08-09 18:34 UTC, javimed commented on source/installation-guide/wazuh-indexer/index.rst
> +   :description: Wazuh is a free, open source, and enterprise-ready security monitoring solution for threat detection, integrity monitoring, incident response and compliance.
```suggestion
   :description: The Wazuh indexer indexes and stores alerts generated by the Wazuh server and provides near real-time data search and analytics capabilities.
```

2022-08-09 19:28 UTC, javimed approved these changes

2022-08-09 19:28 UTC, merged