Add section to explain how the manager certificates are generated.
wazuh/wazuh-documentation pull request #5461
Opened 2022-07-12 07:22 UTC by antoniomanuelfr

## Description
Hello team!

Authd is now able to generate the manager certificate even if openssl is not installed on the system. This PR adds the new options added and explain how to generate the certificates.

# Closes 5457

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

## Note to the reviewer

This PR includes changes to the `redirect.js` script that need to be included in all production branches.

2022-07-12 11:23 UTC, chemamartinez requested changes

2022-07-12 11:23 UTC, chemamartinez commented on source/user-manual/reference/daemons/wazuh-authd.rst
> +.. versionadded:: 5.0
This is not needed since the documentation has a version selector

2022-07-12 11:23 UTC, chemamartinez commented on source/user-manual/reference/daemons/wazuh-authd.rst
> +``wazuh-authd`` is able to generate the manager certificates even if openssl is not installed on the system. The parameters of the certificate are specified in the CLI:
```suggestion
``wazuh-authd`` is able to generate X.509 certificates even if OpenSSL is not installed on the system. The parameters of the certificate are specified in the CLI:
```

2022-07-12 11:23 UTC, chemamartinez commented on source/user-manual/reference/daemons/wazuh-authd.rst
> +If one of the parameters related with the certificate generation is missing, an error will be triggered and the certificate generation will be aborted.
```suggestion
If any of the parameters related to the certificate generation is missing, an error will be triggered and the certificates are not generated.
```

2022-07-12 11:23 UTC, chemamartinez commented on source/user-manual/reference/daemons/wazuh-authd.rst
> +
Include a brief explanation of what these certificates are for in Wazuh.

2022-07-12 11:23 UTC, chemamartinez commented on source/user-manual/reference/daemons/wazuh-authd.rst
> +| **-K**           | Path to store the manager certificate key.                                                            |
Let's avoid talking about `manager certificate`. This tool can be used to generate an X.509 certificate for any purpose, even the default one is to create the certs for the manager.

2022-07-12 11:23 UTC, chemamartinez commented on source/user-manual/reference/daemons/wazuh-authd.rst
> +| **-S**           | Subject of the manager certificate.                                                                   |
From the OpenSSL documentation, we could specify the required format:
```
The arg must be formatted as /type0=value0/type1=value1/type2=....  Keyword characters may be escaped by \ (backslash), and whitespace is retained.  Empty values
           are permitted, but the corresponding type will not be included in the request.
```

2022-08-02 09:51 UTC, chemamartinez approved these changes
LGTM

2022-09-23 10:45 UTC, s-ocando approved these changes

2022-09-23 10:45 UTC, merged