Upgrade guide meta-descriptions
wazuh/wazuh-documentation pull request #5518
Opened 2022-08-11 18:24 UTC by Arcapas

## Description
This PR aims to list and correct the Wazuh documentation SemRush issues for July 2022.

## Tasks
- [x] Review the following sections of the documentation searching for missing meta-descriptions:
    - [x] Upgrade guide
    - [ ] Cloud service
    - [ ] Cloud security
    - [ ] Container security 
    
## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2022-08-26 18:09 UTC, Arcapas reviewed
LGTM

2022-09-05 22:17 UTC, javimed requested changes

2022-09-05 22:17 UTC, javimed commented on source/amazon/services/supported-services/server-access.rst
> +  :description: Amazon S3 Server Access Logging provides detailed records for the requests that are made to a bucket. Learn more about it in this section.
```suggestion
  :description: Amazon S3 Server Access Logging provides detailed records for the requests that are made to a bucket. Learn more about Wazuh and Amazon S3 Server access logging in this section.
```

2022-09-05 22:17 UTC, javimed commented on source/amazon/services/supported-services/trusted-advisor.rst
> +  :description: AWS Trusted Advisor is an online resource to help users reduce costs, increase performance, and improve security. Learn more about it in this section.
```suggestion
  :description: AWS Trusted Advisor is an online resource to help users reduce costs, increase performance, and improve security. Learn more about Wazuh and AWS Trusted Advisor in this section.
```

2022-09-05 22:17 UTC, javimed commented on source/amazon/services/supported-services/vpc.rst
> +  :description: Amazon VPC lets users provision a logically isolated section of the AWS Cloud where they can launch AWS resources. Learn more about it in this section.
```suggestion
  :description: Amazon VPC lets users provision a logically isolated section of the AWS Cloud where they can launch AWS resources. Learn more about Wazuh and Amazon VPC in this section.
```

2022-09-05 22:17 UTC, javimed commented on source/amazon/services/supported-services/waf.rst
> +  :description: Amazon WAF is a web application firewall that helps protect your web applications from common web exploits. Learn more about it in this section.
```suggestion
  :description: Amazon WAF is a web application firewall that helps protect your web applications from common web exploits. Learn more about Wazuh and Amazon WAF in this section.
```

2022-09-15 22:50 UTC, javimed commented on source/github/index.rst
> +  :description: Discover how Wazuh can help you to monitor your GitHub organizations. Check out this section of our documentation to learn more about it.
```suggestion
  :description: Discover how Wazuh helps you to monitor your GitHub organizations. Check out this section of our documentation to learn more about it. 
```

2022-09-15 22:50 UTC, javimed commented on source/office365/index.rst
> +  :description: Discover how Wazuh can help you monitor the Office 365 audit log for your organization. Learn more about it in this section of our documentation.
```suggestion
  :description: Discover how Wazuh helps you monitor the Office 365 audit log for your organization. Learn more about it in this section of our documentation.
```

2022-09-15 22:50 UTC, javimed commented on source/upgrade-guide/legacy/upgrading-agent/index.rst
> +
```suggestion
```

2022-09-16 15:07 UTC, javimed approved these changes

2022-09-16 15:08 UTC, merged