Add new API log rotation option based on file size
wazuh/wazuh-documentation pull request #5545
Opened 2022-08-29 08:39 UTC by vicferpoy

## Description

This PR adds the new API option to set log rotation based on file size.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

Regards,
Víctor

2022-09-01 07:01 UTC, mcarmona99 approved these changes
LGTM

2022-09-07 10:36 UTC, davidjiglesias requested changes
Size says 1m in one side and 1M on the other, are both correct? 

Also, I would put enabled: false in the example, as that is the default value

2022-09-07 15:30 UTC, vicferpoy commented
@davidjiglesias 

> K/k for kilobytes, M/m for megabytes.

2022-09-08 06:59 UTC, davidjiglesias approved these changes

2022-09-08 07:53 UTC, s-ocando approved these changes

2022-09-08 07:53 UTC, merged