Change the wrong image in the Cloud security section in 4.2
wazuh/wazuh-documentation pull request #5567
Opened 2022-09-06 15:51 UTC by Arcapas

## Description
This PR aims to change the wrong image in the `Cloud security` section in version 4.2.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2022-09-06 17:38 UTC, javimed approved these changes

2022-09-12 15:02 UTC, vicferpoy approved these changes

2022-09-15 20:41 UTC, javimed requested changes

2022-09-15 20:41 UTC, javimed commented on source/gcp/prerequisites/pubsub.rst
> +#. Push the **CREATE SINK** button.
```suggestion
#. Click the **CREATE SINK** button.
```

2022-09-21 14:35 UTC, javimed approved these changes

2022-09-21 14:44 UTC, merged