Wazuh 4.3.8 release notes and versions update
wazuh/wazuh-documentation pull request #5568
Opened 2022-09-06 17:37 UTC by Arcapas

## Description

This PR includes the Wazuh 4.3.8 release notes and versions update.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

## Note to the reviewer

This PR includes changes to the `redirect.js` script that need to be included in all production branches.

2022-09-15 20:37 UTC, javimed requested changes

2022-09-15 20:37 UTC, javimed commented on source/release-notes/release-4-3-8.rst
> +`#14825 <https://github.com/wazuh/wazuh/pull/14825>`_             A performance problem related to the synchronization of files through the cluster is fixed. Avoiding ``wazuh-remoted`` from cleaning
```suggestion
`#14825 <https://github.com/wazuh/wazuh/pull/14825>`_             A performance problem when synchronizing files through the cluster is fixed. The multigroup folder in worker nodes is no longer cleaned upon node restart.
```

2022-09-15 20:37 UTC, javimed commented on source/release-notes/release-4-3-8.rst
> +`#14772 <https://github.com/wazuh/wazuh/pull/14772>`_             The rule skipped in ``wazuh-analysisd`` when the option ``if_sid`` is invalid is fixed.
```suggestion
`#14772 <https://github.com/wazuh/wazuh/pull/14772>`_             A problem when using an invalid syntax with the if_sid label is fixed. Now the rule is ignored if the listed if_sid rules are not separated by ` ` or `,`.
```

2022-09-15 20:37 UTC, javimed commented on source/release-notes/release-4-3-8.rst
> +`#1806 <https://github.com/wazuh/wazuh-packages/pull/1806>`__     An error in the ``wazuh-dashboard`` API is fixed.
```suggestion
`#1806 <https://github.com/wazuh/wazuh-packages/pull/1806>`__     An error in the ``wazuh-dashboard`` API with some specific passwords is fixed.
```

2022-09-19 08:16 UTC, s-ocando approved these changes

2022-09-19 09:12 UTC, merged