Added new settings to logcollector module, ignore and restrict
wazuh/wazuh-documentation pull request #5571
Opened 2022-09-07 12:48 UTC by jotacarma90

## Description

This PR is to add the description of the two new settings in the logcollector reference. Added description, example cases and allowed value.
Issue related: https://github.com/wazuh/wazuh/issues/5628
PR related: https://github.com/wazuh/wazuh/pull/14782

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [ ] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2022-09-07 20:10 UTC, branchnetconsulting commented
I'd recommend clarifying what happens if multiple `<restrict_log>` lines or multiple `<ignore_log>` lines are used in the same `<localfile>` section.  Will the regexes for the matching tag lines just be concatenated or will the separate matching tag lines be interpreted as being in an OR relationship?  

It would also be good to state that if `<restrict_log>` and `<ignore_log>` are both used in the same `<localfile>` section, that `<ignore_log>` takes precedence when the ignore and restrict pattern both match the same line (assuming that is the behavior).

2022-09-19 11:52 UTC, chemamartinez requested changes

2022-09-19 11:52 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +- `ignore_log`_
```suggestion
- `ignore`_
```
Please apply this suggestion to the whole PR.

2022-09-19 11:52 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +- `restrict_log`_
```suggestion
- `restrict`_
```

2022-09-22 12:57 UTC, jotacarma90 commented
Hi @branchnetconsulting 
Indeed we should clarify some points, I have updated the documentation and implemented some new features:
- Choose the type of regex expression (osregex, osmatch, pcre2. The default is pcre2).
- Possibility to use ignore and restrict multiple times (OR for ignore, AND for restrict).
- In case any ignore expression and any restrict expression are identical, no log will be processed. I have clarified it also in the docu.

Thank you very much!

2022-09-29 15:39 UTC, chemamartinez requested changes

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +This allows you to configure a pcre2 expression to ignore specific log lines. Multiple expressions can be configured by repeating the ignore label. The log will be ignored as soon as one of the expre
- Better using impersonal sentences (avoid using `This allows you`).
- pcre2 is uppercase
- Let's simplify the description
```suggestion
Specify a regular expression to ignore log lines or command outputs when matching. Whether several `ignore` labels are defined, entries are ignored when matching any of the specified ones.
```

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +|                    | `pcre2 <regex.html#pcre2-syntax>`_ expression.                |
```suggestion
|                    | `PCRE2 <regex.html#pcre2-syntax>`_ expression.                |
```

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +The attribute type is optional.
```suggestion
Use the `type` attribute to define the regular expression type. By default, PCRE2 is applied.
```

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +  For formats that group multiple lines, the entire group will be counted as a single log to check if it should be restricted.
Better use present than future.
```suggestion
  For formats that group multiple lines, the entire group is treated as a single log when evaluating the regex.
```

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +  The ignore label is checked before the restrict label, so if you set identical expressions for both settings, no log will be processed.
```suggestion
  Whether the same log entry matches an ignore and also a restrict configured for the same `localfile`, the entry is discarded. In other words, the `ignore` has precedence over `restrict`. Said that, if the same expression is defined in both `ignore` and `restrict`, no log will be processed for that `localfile`.
```

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +  On Windows, the ``eventchannel`` format already provides a way to restrict logs through queries, so this setting ``does not apply`` to this format.
```suggestion
  The `eventchannel` format already provides a way to filter logs through queries. Therefore, `ignore` and `restrict` settings don't apply to this format.
```

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +.. note::
These three notes are duplicated, it is cleaner if we add it only once at the end of the `restrict` section.

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +This allows you to configure a pcre2 expression to restrict specific log lines, avoiding to generate alerts for those logs that do not match. Multiple expressions can be configured by repeating the r
```suggestion
Specify a regular expression to restrict processed log lines or command outputs. Whether several `restrict` labels are defined, entries are processed when matching all of them.
```

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +|                    | `pcre2 <regex.html#pcre2-syntax>`_ expression.                |
```suggestion
|                    | `PCRE2 <regex.html#pcre2-syntax>`_ expression.                |
```

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +The attribute type is optional.
```suggestion
Use the `type` attribute to define the regular expression type. By default, PCRE2 is applied.
```

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> ++-------------+-----------------------------------------+-------------+---------------+
Use this table format:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/29475387/193076056-4eea389a-0ce8-45ee-a7e9-501c7059f462.png">

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +      <restrict type="osregex">username_\.+</restrict>
Change the type of this `restrict` to show that types can be different in the same `localfile`.

2022-09-29 15:39 UTC, chemamartinez commented on source/user-manual/reference/ossec-conf/localfile.rst
> +      <ignore type="osregex">type=\.+_CHANGE</ignore>
Change the type of this `ignore` to show that types can be different in the same `localfile`.

2022-11-11 14:20 UTC, chemamartinez approved these changes
LGTM!

2023-01-05 13:32 UTC, Arcapas approved these changes
LGTM

2023-01-10 14:49 UTC, merged