Add Reparse section to GCP and Azure and modify the AWS one
wazuh/wazuh-documentation pull request #5577
Opened 2022-09-09 19:07 UTC by fdalmaup

| Related issue |
|----|
| Closes #4902 |

## Description

This PR closes the issue #4902. It adds the `Reparse` section in the `Considerations for configuration` page of the Azure and GCP modules. It also modifies the `Reparse` section in the AWS module documentation, removing the previous note about the `--reparse` option not being available for CloudWatch Logs.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2022-09-14 10:51 UTC, CarlosRS9 requested changes

2022-09-14 10:51 UTC, CarlosRS9 commented on source/azure/activity-services/prerequisites/considerations.rst
> +  # ./azure-logs --log_analytics --la_auth_path credentials_example --la_tenant_domain 'wazuh.example.domain' --la_tag azure-activity --la_query "AzureActivity" --workspace example-workspace --la_tim
```suggestion
  # /var/ossec/wodles/azure/azure-logs --log_analytics --la_auth_path credentials_example --la_tenant_domain 'wazuh.example.domain' --la_tag azure-activity --la_query "AzureActivity" --workspace example-workspace --la_time_offset 50d --debug 2 --reparse
```

2022-09-14 14:06 UTC, CarlosRS9 approved these changes

2022-09-22 21:41 UTC, javimed approved these changes

2022-09-23 13:31 UTC, javimed approved these changes

2022-09-23 13:33 UTC, merged