Add changes to add the new setting in SCA
wazuh/wazuh-documentation pull request #5653
Opened 2022-10-04 18:05 UTC by FrancoRivero

## Description
Hi team, this pull-request is to modify the SCA documentation as we have added a new setting that makes it possible to add rules using the `PCRE2` engine to detect and resolve regex checks.
Regards

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns.

Closes #5652

2023-01-05 08:28 UTC, chemamartinez commented on source/user-manual/capabilities/sec-config-assessment/creating-custom-policies.rst
> +.. note::
We can merge both notes and explain this easier.

2023-01-05 09:54 UTC, chemamartinez approved these changes
LGTM

2023-01-11 18:37 UTC, javimed requested changes

2023-01-11 18:37 UTC, javimed commented on source/user-manual/capabilities/sec-config-assessment/creating-custom-policies.rst
> +.. note::
```suggestion
.. note::

```

2023-01-11 18:37 UTC, javimed commented on source/user-manual/capabilities/sec-config-assessment/creating-custom-policies.rst
> +
```suggestion
```

2023-01-11 18:37 UTC, javimed commented on source/user-manual/capabilities/sec-config-assessment/creating-custom-policies.rst
> +  If the **regex_type** is configured for a particular check, it overwrites the regex engine applied for the whole policy.
```suggestion
   If you set a *regex_type*, it overrides the regex engine type defined in the policy.
```

2023-01-12 13:45 UTC, javimed approved these changes
LGTM

2023-01-12 13:45 UTC, merged