Added extra documentation for Windows Audit Policies in Syscheck whodata
wazuh/wazuh-documentation pull request #5676
Opened 2022-10-19 14:43 UTC by jotacarma90

## Description
Hey team, this PR is to go deeper into the Windows whodata section of syscheck.
Detailing more the configurations that are necessary for the correct functioning of whodata.
It also improved the description of how this module works, explaining how Wazuh can detect these changes and act accordingly, reconfiguring directories in real-time mode.
Improved section of Manual configuring Audit Policies.

## Checks
- [ ] Compiles without warnings.
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2022-11-11 15:37 UTC, chemamartinez requested changes

2022-11-11 15:37 UTC, chemamartinez commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +For the correct operation of this auditing subsystem, it is necessary to have configured some Local Audit Policies and the SACLs of each configured directory from which to receive these events. Wazuh
```suggestion
For the correct operation of the who-data feature, it is necessary to have configured some Local Audit Policies as well as the SACLs of each monitored directory. Wazuh automatically performs this task when the tag ``whodata="yes"`` is declared within the ``directories`` statement in the ``ossec.conf`` file:
```

2022-11-11 15:37 UTC, chemamartinez commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +However, other processes could modify some of these configurations, preventing syscheck from receiving the necessary information. In this case the directories configured in whodata mode will be recon
```suggestion
Even though FIM configures the needed Local Audit Policies and SASLs when launched. Other services may change this configuration preventing who-data from receiving the monitored events. In this case, FIM detects this configuration change and switches all the directories configured with who-data to real-time mode. The two available mechanisms to detect these configuration changes are:
```

2022-11-11 15:37 UTC, chemamartinez commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +#. Periodically, Wazuh checks that the Audit Policies and the SACLs are configured as expected. It is possible to modify this interval, see :ref:`the configuration section of windows_audit_interval<r
```suggestion
#. Periodically, Wazuh checks that the Audit Policies and the SACLs are configured as expected. It is possible to modify the frequency of this verification with :ref:`windows_audit_interval<reference_ossec_syscheck_windows_audit_interval>`.
```

2022-11-11 15:55 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +For the correct operation of this auditing subsystem, it is necessary to have configured some Local Audit Policies and the SACLs of each configured directory from which to receive these events. Wazuh
Done

2022-11-11 15:56 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +However, other processes could modify some of these configurations, preventing syscheck from receiving the necessary information. In this case the directories configured in whodata mode will be recon
Done

2022-11-11 15:56 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +#. Periodically, Wazuh checks that the Audit Policies and the SACLs are configured as expected. It is possible to modify this interval, see :ref:`the configuration section of windows_audit_interval<r
Done

2022-11-11 16:03 UTC, chemamartinez approved these changes

2022-12-14 21:02 UTC, javimed requested changes

2022-12-14 21:02 UTC, javimed commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +SACLs of each directory can be checked and modified through its Properties, Security tab, and clicking on Advanced:
```suggestion
You can check and modify SACLs of each directory through **Properties**, selecting the **Security** tab, and clicking on **Advanced**:
```

2022-12-14 21:02 UTC, javimed commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +In the Auditing tab it is necessary to have a Success entry:
```suggestion
In the Auditing tab it's necessary to have a *Success* entry:
```

2022-12-14 21:02 UTC, javimed commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +It can be created by adding these advanced permissions:
```suggestion
You can create it by adding these advanced permissions:
```

2022-12-15 10:13 UTC, jotacarma90 commented on source/user-manual/reference/ossec-conf/syscheck.rst
> +Sets the frequency in seconds with which the Windows agent will check that the Local Audit Policies and the SACLs of the directories monitored in whodata mode are correct.
Done

2022-12-15 10:14 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +The who-data monitoring functionality uses the Microsoft Windows auditing subsystem to get the related information about who made modifications in a monitored directory. These changes produce audit e
Done

2022-12-15 10:17 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +For the correct operation of the who-data feature, it is necessary to have configured some Local Audit Policies as well as the SACLs of each monitored directory. Wazuh automatically performs this tas
Done

2022-12-15 10:17 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +Even though FIM configures the needed Local Audit Policies and SASLs when launched, other services may change this configuration preventing who-data from receiving the monitored events. In this case,
Done

2022-12-15 10:17 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +#. Windows generates specific events (ID 4719) when one of the Audit Policies is modified (Success removed).
Done

2022-12-15 10:18 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows.rst
> +#. Periodically, Wazuh checks that the Audit Policies and the SACLs are configured as expected. It is possible to modify the frequency of this verification with :ref:`windows_audit_interval<reference
Done

2022-12-15 10:18 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Done

2022-12-15 10:18 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +Go to ``Security Settings -> Advanced Audit Policy Configuration`` and configure to Success the following policies:
Done

2022-12-15 10:19 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +1) Object Access -> Audit File System
Done

2022-12-15 10:19 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +2) Object Access -> Audit Handle Manipulation
Done

2022-12-15 10:20 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +These policies are part of the Audit Object Access category, so another possibility is to configure the entire category to Success in ``Security Settings -> Local Policies -> Audit Policy``,
Done

2022-12-15 10:21 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +In the Auditing tab it is necessary to have a Success entry:
Done

2022-12-15 10:30 UTC, jotacarma90 commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +It can be created by adding these advanced permissions:
Done

2022-12-15 14:08 UTC, javimed approved these changes

2022-12-15 14:08 UTC, javimed commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +If your system doesn't allow configuring subcategories through *Advanced Audit Policy Configuration*, you can configure to *Success* the entire category. These policies are part of the *Audit object
```suggestion
If your system doesn't allow configuring subcategories through *Advanced Audit Policy Configuration*, you can configure to *Success* the entire category. These policies are part of the *Audit object access* category. Go to **Security Settings** -> **Local Policies** -> **Audit Policy** and configure this category.
```

2022-12-15 14:30 UTC, javimed approved these changes

2022-12-15 14:30 UTC, javimed commented on source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
> +^^^^^^^^^^^^^^^^
```suggestion
----------------
```

2022-12-15 14:31 UTC, merged