Update documentation about System32 directory in FIM
wazuh/wazuh-documentation pull request #5765
Opened 2022-11-21 14:58 UTC by GabrielEValenzuela

## Description

This PR is related with the issue of core [#14796](https://github.com/wazuh/wazuh/issues/14796) and PR [#15438](https://github.com/wazuh/wazuh/pull/15438)

## Checks
- [ ] Compiles without warnings.
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2022-12-21 10:38 UTC, jotacarma90 commented on source/user-manual/capabilities/file-integrity/fim-configuration.rst
> +To configure directories within the Windows directory (Also known as ``%WINDIR%``), it is necessary to take into account that in 64-bit architecture systems, there are two special folders: ``System32
```suggestion
To configure Windows special directory ``%WINDIR%\system32``, it is necessary to take into account that in 64-bit architecture systems: 
1) **System32** is reserved for those 64-bit DLLs.
2) **SysWOW64** for all 32-bit DLLs.

```

2022-12-21 10:38 UTC, jotacarma90 commented on source/user-manual/capabilities/file-integrity/fim-configuration.rst
> +From version 4.4.0 of Wazuh, this redirection has been disabled and it is possible to access directly to ``System32``, so those configurations that have as monitoring directory ``%WINDIR%/Sysnative``
```suggestion
From version 4.4.0 of Wazuh, this redirection has been disabled and it is possible to access directly to ``System32``, so monitoring directories ``%WINDIR%/System32`` or ``%WINDIR%/Sysnative`` will be equivalent, and the path shown in the alerts will be ``%WINDIR%/System32``.
```

2023-01-05 10:15 UTC, jotacarma90 approved these changes
LGTM

2023-01-05 13:09 UTC, chemamartinez requested changes

2023-01-05 13:40 UTC, GabrielEValenzuela commented on source/user-manual/capabilities/file-integrity/fim-configuration.rst
> +From version 4.4.0 of Wazuh, this redirection has been disabled and it is possible to access directly to ``System32``, so monitoring directories ``%WINDIR%/System32`` or ``%WINDIR%/Sysnative`` will b
Done!

2023-01-05 14:50 UTC, chemamartinez approved these changes

2023-01-23 12:46 UTC, javimed commented on source/user-manual/capabilities/file-integrity/fim-configuration.rst
> +But this redirection has been disabled and you can access ``System32`` directly. Monitoring ``%WINDIR%/System32`` and ``%WINDIR%/Sysnative`` directories is equivalent and Wazuh shows the path ``%WIND
```suggestion
But we disabled this redirection and you can access ``System32`` directly. Monitoring ``%WINDIR%/System32`` and ``%WINDIR%/Sysnative`` directories is equivalent and Wazuh shows the path ``%WINDIR%/System32`` in the alerts. ``SysWOW64`` is a different directory. To monitor ``%WINDIR%/SysWOW64``, you must add it to the ``ossec.conf`` configuration file.
```

2023-01-23 14:47 UTC, javimed approved these changes

2023-01-23 14:48 UTC, merged