Create release notes template
wazuh/wazuh-documentation pull request #5840
Opened 2022-12-22 18:25 UTC by Arcapas

## Description
This issue aims to create the Wazuh v4.4 release notes and versions update throughout the documentation.

## Checks
- [ ] Compiles without warnings.
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2023-01-11 19:17 UTC, javimed requested changes

2023-01-11 19:17 UTC, javimed commented on source/release-notes/release-4-4-0.rst
> +- Expanded operating systems support with Alpine Linux agent
```suggestion
- Alpine Linux agent to expand the operating systems supported
```

2023-01-11 19:17 UTC, javimed commented on source/release-notes/release-4-4-0.rst
> +SUSE agents now natively support vulnerabilities detection. Wazuh added full support for SUSE Linux Enterprise Server and Desktop 11, 12, and 15 operating systems. The vulnerability Detector now scan
```suggestion
SUSE agents now natively support vulnerabilities detection. Wazuh added full support for SUSE Linux Enterprise Server and Desktop operating systems versions 11, 12, and 15. The vulnerability Detector now scans the programs identified by ``syscollector``, looking to report vulnerabilities described in the `SUSE OVAL <https://www.suse.com/support/security/oval/>`_ and the `NVD <https://nvd.nist.gov/>`_ databases.
```

2023-01-11 19:17 UTC, javimed commented on source/release-notes/release-4-4-0.rst
> +Wazuh 4.4.0 adds support for Alpine Linux. As Alpine Linux is a distribution that has gained great popularity among Linux users, we saw the need for the Wazuh agent to support Alpine Linux and ensure
```suggestion
Wazuh 4.4.0 adds support for Alpine Linux. As Alpine Linux is a distribution that has gained great popularity among Linux users, we saw the need for the Wazuh agent to support Alpine Linux and ensure the proper support for this distribution. We generated Alpine Linux installers to make it easier to install and thus spare users from having to compile the source code locally.
```

2023-01-11 19:17 UTC, javimed commented on source/release-notes/release-4-4-0.rst
> +      :title: This new version adds support for Alpine Linux
```suggestion
      :title: Wazuh 4.4.0 adds support for Alpine Linux
```

2023-01-11 19:17 UTC, javimed commented on source/release-notes/release-4-4-0.rst
> +Wazuh indexer and dashboard bump to OpenSearch 2.4.1. The Wazuh indexer and the Wazuh dashboard are based on OpenSearch, an open source search and analytics project derived from Elasticsearch and Kib
```suggestion
Wazuh indexer and dashboard based on the latest OpenSearch 2.4.1. The Wazuh indexer and the Wazuh dashboard are based on OpenSearch, an open source search and analytics project derived from Elasticsearch and Kibana. We generated and tested the ``wazuh-indexer`` Debian and RPM packages with OpenSearch 2.4.1 and the ``wazuh-dashboard`` Debian and RPM packages with OpenSearch dashboards 2.4.1. With this bump to the latest version, we avoid earlier version vulnerabilities, have all OpenSearch new functionalities, and are up to date with the OpenSearch project development.
```

2023-01-11 19:17 UTC, javimed commented on source/release-notes/release-4-4-0.rst
> +Wazuh added support for Azure Integration in Linux agents. Now this integration can run for both agents and managers. We modified the packages generation process to support Azure in those agents inst
```suggestion
Wazuh added support for Azure Integration in Linux agents. Now this integration can run for both agents and managers. We modified the packages generation process to support Azure in those agents that are installed using the WPK packages. Each new WPK package contains all the updated binaries and source code, and the installer updates all files and binaries to support Azure integration.
```

2023-01-11 19:17 UTC, javimed commented on source/release-notes/release-4-4-0.rst
> +      :title: This new version adds support Azure Integration in Linux agents
```suggestion
      :title: Wazuh 4.4.0 adds support for the Azure Integration in Linux agents
```

2023-01-12 14:27 UTC, Arcapas commented on source/_static/js/redirects.js
> +  '/release-notes/release-4-4-0.html',
Yes, I'll do it.

2023-01-12 21:01 UTC, merged