Support AlmaLinux in Vulnerability Detector
wazuh/wazuh-documentation pull request #5904
Opened 2023-02-02 21:06 UTC by mateocervilla

|Related issue|
|---|
|#5901|

## Description

This PR adds the new support implemented for AlmaLinux in Vulnerability Detector. 
This change must be applied with the changes performed in wazuh/wazuh#10774.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns.

2023-02-15 12:57 UTC, lexzz commented
@MarcelKemp When will this feature be available in Wazuh? Thank you in advance!

2023-02-20 12:28 UTC, MarcelKemp commented
Hi @lexzz, Vulnerability Detector support for AlmaLinux is planned to be available for Wazuh **`v4.5`**.

2023-08-10 13:11 UTC, javimed requested changes

2023-08-10 13:11 UTC, javimed commented on source/user-manual/capabilities/vulnerability-detection/offline-update.rst
> +Currently, the AlmaLinux vulnerabilities are fetched from one OVAL file for each supported AlmaLinux version.
```suggestion
Currently, the module fetches AlmaLinux vulnerabilities from one OVAL file for each supported AlmaLinux version.
```

2023-08-10 13:11 UTC, javimed commented on source/user-manual/capabilities/vulnerability-detection/offline-update.rst
> +Feeds can be fetched from a custom repository using the `url` attribute for each supported OS, as shown in this example:
```suggestion
To fetch feeds from a custom repository you can use the ``url`` attribute for each supported OS, as shown in this example:
```

2023-08-10 13:13 UTC, javimed approved these changes

2023-08-10 13:28 UTC, merged