Added AWS native GuardDuty integration documentation
wazuh/wazuh-documentation pull request #5917
Opened 2023-02-10 13:33 UTC by EduLeon12

## Description

GuardDuty implementation now supports native integration to S3 buckets, replacing the current one which requires AWS Kinesis/Firehose/CloudWatch integration to send related logs.

Documentation has been updated to include a step by step guide on how to enable it.

## Checks
- [ ] Compiles without warnings.
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2023-02-14 13:33 UTC, nico-stefani requested changes
Please add an entry to https://documentation.wazuh.com/current/amazon/services/supported-services/index.html. Because the path for native logs is different.

2023-02-22 13:19 UTC, nico-stefani requested changes

2023-02-22 13:19 UTC, nico-stefani commented on source/amazon/services/supported-services/index.rst
> +| Amazon       | :ref:`GuardDuty Native <amazon_guardduty_native>`        | bucket                | guardduty      | <bucket_name>/<prefix>/<year>/<month>/<day>/<hh>
```suggestion
| Amazon       | :ref:`GuardDuty Native <amazon_guardduty_native>`        | bucket                | guardduty      | <bucket_name>/<prefix>/AWSLogs/<suffix>/<account_id>/GuardDuty/<region>/<year>/<month>/<day>                                                                 |
```

2023-02-22 14:49 UTC, nico-stefani approved these changes
LGTM

2023-03-01 09:37 UTC, davidjiglesias approved these changes

2023-03-03 21:00 UTC, EduLeon12 commented
File updated to comply with new guidelines and requested changes

2023-03-08 16:17 UTC, s-ocando approved these changes

2023-03-08 17:22 UTC, merged