Added Note block to increase visibility of feature for cloud services
wazuh/wazuh-documentation pull request #6010
Opened 2023-03-31 17:27 UTC by EduLeon12

|Related issue|
|---|
|Closes #4988 |

## Description

As described in #4988, there was no documentation regarding the feature to enable the _Security Information_  dashboard not only in AWS but in all Cloud modules sections that support this feature.

Documentation has been updated to enhance the visibility of this feature to the user.

## Checks
- [x] Compiles without warnings.
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2023-04-03 13:14 UTC, nico-stefani requested changes

2023-04-03 13:14 UTC, nico-stefani commented on source/amazon/services/prerequisites/considerations.rst
> +
The note has little visibility inside of **FIPS endpoints**. I suggest adding a new section with this content.

2023-04-03 13:14 UTC, nico-stefani commented on source/gcp/prerequisites/considerations.rst
> +
Like in AWS, the note here has a lack of visibility. I suggest adding a new section with this content.

2023-04-04 14:46 UTC, nico-stefani approved these changes
LGTM

2023-05-10 11:21 UTC, s-ocando reviewed
Hi @EduLeon12, 

Please review my suggestions and if you agree, apply them in all the corresponding cases.

2023-05-10 11:21 UTC, s-ocando commented on source/amazon/services/prerequisites/considerations.rst
> +   Once the configuration is complete, you can enable the `Security Information` visualization feature in the **Wazuh Dashboard**. You can read more about it `here <https://documentation.wazuh.com/cu
```suggestion
Once the configuration is complete, you can enable the corresponding Security Information Management module on the Wazuh Dashboard. To learn more, see the`modules <https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/settings.html#modules>`_ section.
```

2023-05-10 11:21 UTC, s-ocando commented on source/amazon/services/prerequisites/considerations.rst
> +   Once the configuration is complete, you can enable the `Security Information` visualization feature in the **Wazuh Dashboard**. You can read more about it `here <https://documentation.wazuh.com/cu
Consider adding the corresponding screenshot to make it more appealing to users. For example:

![image](https://github.com/wazuh/wazuh-documentation/assets/61882981/a370f92d-5600-4878-adbf-76bac86b7290)

2023-05-11 16:00 UTC, EduLeon12 commented
Hi @s-ocando.

All changes have been addressed and dashboard screenshot added to every service.

Will wait for your review again.

Thank You.

2023-05-23 11:27 UTC, s-ocando approved these changes

2023-05-30 10:49 UTC, davidjiglesias approved these changes

2023-05-30 10:57 UTC, merged