Refactored and standarized the Python dependencies section for cloud and docker modules
wazuh/wazuh-documentation pull request #6232
Opened 2023-07-11 16:04 UTC by EduLeon12

|Related issue|
|---|
|Closes #6081 |

## Description

As explained in #6081, Having a Python dependencies section for each cloud and docker-listener module caused an issue because upgrading python version and not updating the documentation in each section caused a dependency issue.

The agent section was changed to have only one Python dependencies section and modules were changed to reference to it. 

## Checks
- [x] Compiles without warnings.
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2023-07-11 16:05 UTC, EduLeon12 commented
## Update

For issues caused by master branch renaming, a new branch and PR has been created.

The original branch, PR, and its comments can be found [here](https://github.com/wazuh/wazuh-documentation/pull/6118).

2023-07-11 17:06 UTC, nico-stefani requested changes

2023-07-11 17:23 UTC, EduLeon12 commented on source/azure/activity-services/prerequisites/dependencies.rst
>    # pip3 install azure-storage-blob==2.1.0 azure-storage-common==2.1.0 azure-common==1.1.25 cryptography==3.3.2 cffi==1.14.4 pycparser==2.20 six==1.14.0 python-dateutil==2.8.1 requests==2.25.1 certif
Only Direct dependencies are listed.

Dependencies such as pytz and SQLAlchemy are needed for the module to run but are not subdependencies of the cloud provider client library

2023-07-11 17:26 UTC, EduLeon12 commented on source/gcp/prerequisites/dependencies.rst
> +  # pip3 install google-cloud-core==1.7.1 google-cloud-pubsub==2.7.1 google-cloud-storage==1.39.0 pytz==2020.1 setuptools==65.5.1
setuptools is listed to avoid vulnerability issue found here:

- https://github.com/wazuh/wazuh/issues/17743

2023-07-11 17:39 UTC, EduLeon12 commented on source/user-manual/agents/cloud-and-container-monitoring.rst
> +- :doc:`Docker listener dependencies </user-manual/agents/container-security/monitoring-docker>`
Done

2023-07-11 17:39 UTC, EduLeon12 commented on source/user-manual/agents/cloud-and-container-monitoring.rst
> +See the :doc:`Cloud security </monitoring>` and :doc:`Container security </container-security/index>` sections to learn more.
Done

2023-07-11 18:27 UTC, nico-stefani commented on source/azure/activity-services/prerequisites/dependencies.rst
>    # pip3 install azure-storage-blob==2.1.0 azure-storage-common==2.1.0 azure-common==1.1.25 cryptography==3.3.2 cffi==1.14.4 pycparser==2.20 six==1.14.0 python-dateutil==2.8.1 requests==2.25.1 certif
Yes, it's ok for `pytz` and `SQLAlchemy`. But, why you are including more than the original change [here](https://github.com/wazuh/wazuh-documentation/pull/6118/files#diff-260dd09ea6b0af257579d7fc129c51a95ca553950d71e723e88d5e79d0121ba5R29)?

2023-07-12 15:15 UTC, EduLeon12 commented on source/azure/activity-services/prerequisites/dependencies.rst
>    # pip3 install azure-storage-blob==2.1.0 azure-storage-common==2.1.0 azure-common==1.1.25 cryptography==3.3.2 cffi==1.14.4 pycparser==2.20 six==1.14.0 python-dateutil==2.8.1 requests==2.25.1 certif
I did not migrate from the previous branch correctly,  Just removed the dependencies.

2023-07-12 15:18 UTC, EduLeon12 commented
## Update

After Discussing with the team the upgrade of setuptools package will be done in this PR.

Related Issue:
- [setuptools upgrade](https://github.com/wazuh/wazuh/issues/17743)

2023-07-12 15:50 UTC, nico-stefani approved these changes
LGTM!

2023-07-13 12:08 UTC, Selutario commented on source/user-manual/agents/cloud-and-container-monitoring.rst
Thinking about this more closely, I think the first item listed in the issue https://github.com/wazuh/wazuh-documentation/issues/6081#issue-1695862005 is not fixed yet:

> - Centralize the Python reference on a single page, avoiding the problem which led to this issue.

The dependency sections of all the wodles are still listing the range of Python versions we support, while this new page isn't giving really useful information about it. I think the initial intention behind said point was only needing to change information about the agents' Python version in one place, instead of updating it in 3-4 different pages, which is already achieved by using `PYTHON_CLOUD_CONTAINERS_` variable.

Therefore, I would choose one of these two options:
- Remove this new section and keep the Python version range on each dependencies page.
- Include the information about the Python versions' range or/and anything related here, while on the other pages, make a simple reference to this new section.

2023-07-18 12:17 UTC, Selutario requested changes

2023-07-18 12:17 UTC, Selutario commented on source/amazon/services/prerequisites/dependencies.rst
> +  # pip3 install boto3==1.17.85
Pyarrow is also required:
```
# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 3 -s 2022-JAN-26 -p dev -r us-east-1
ERROR: pyarrow module is required.
```

2023-09-01 16:13 UTC, javimed commented on source/cloud-security/azure/activity-services/prerequisites/dependencies.rst
>    The Azure monitoring module can be configured in the Wazuh manager (which also behaves as an agent) or directly in a Wazuh agent.
Shall we keep this note?

2023-09-01 16:13 UTC, javimed commented on source/cloud-security/gcp/prerequisites/dependencies.rst
>    The GCP module can be configured in both the Wazuh manager and the agent. The choice merely depends on where you want to reach the GCP services from.
Shall we keep this note?

2023-09-01 17:38 UTC, javimed approved these changes

2023-09-01 23:10 UTC, merged