Add Maltiverse integration section
wazuh/wazuh-documentation pull request #6257
Opened 2023-07-20 12:51 UTC by fdalmaup

## Description
Closes #6216. It adds the `Maltiverse` native integration section in the `Integration with external APIs` page of the documentation and the corresponding `integration` reference. 

## Checks
- [ ] Compiles without warnings.
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

2023-07-20 13:19 UTC, GGP1 approved these changes
The instructions, syntax and spelling is correct, the links are pointed to the right resources and the styling of the content matches the rest of the content

![maltiverse](https://github.com/wazuh/wazuh-documentation/assets/51374959/c2349012-97ef-4330-8d80-b8fcf04e6df3)

LGTM

2023-07-20 13:23 UTC, GGP1 commented on source/user-manual/manager/manual-integration.rst
> +         <api_key>MALTIVERSE_AUTH_TOKEN</api_key>
Just as a comment, the other sections add a comment where values should be replaced, like 

```
<api_key>API_KEY</api_key> <!-- Replace with your VirusTotal API key -->
```

I don't think it's necessary but perhaps we should add it to be consistent with the rest of the page

2023-07-20 14:57 UTC, Selutario requested changes

2023-07-20 15:51 UTC, Selutario approved these changes

2023-07-20 20:03 UTC, javimed requested changes

2023-07-20 20:03 UTC, javimed commented on source/user-manual/reference/ossec-conf/integration.rst
> +.. note:: This option must be set to ``json`` for Slack, VirusTotal, Shuffle and Maltiverse integrations.
```suggestion
.. note:: This option must be set to ``json`` for Slack, VirusTotal, Shuffle, and Maltiverse integrations.
```

2023-07-21 16:07 UTC, javimed commented on source/user-manual/manager/manual-integration.rst
> +`Maltiverse <https://whatis.maltiverse.com/>`__ is an open and collaborative platform for indexing and searching Indicators of Compromise (IoCs). It works as a broker for Threat intelligence sources.
```suggestion
`Maltiverse <https://whatis.maltiverse.com/>`__ is an open and collaborative platform for indexing and searching Indicators of Compromise (IoCs). It works as a broker for Threat intelligence sources. Maltiverse aggregates information from more than a hundred different public, private and community sources.

This integration identifies IoCs in Wazuh alerts via the Maltiverse API. It generates new alerts enriched with Maltiverse data. The Maltiverse data fields are based on the threat taxonomy of the ECS standard (Elastic Common Schema).
```

2023-07-21 18:56 UTC, javimed commented on source/user-manual/manager/manual-integration.rst
> +This integration identifies IoCs in Wazuh alerts via the Maltiverse API and generates new enriched ones inserting new fields, following the threat taxonomy of the ECS standard (Elastic Common Schema)
```suggestion
This integration identifies IoCs in Wazuh alerts via the Maltiverse API. It generates new alerts enriched with Maltiverse data. The Maltiverse data fields are based on the threat taxonomy of the ECS standard (Elastic Common Schema).
```

2023-07-21 18:56 UTC, javimed approved these changes
LGTM

2023-08-02 13:00 UTC, merged