Wazuh Cloud: Documentation for the new pricing model
wazuh/wazuh-documentation pull request #6258
Opened 2023-07-20 16:15 UTC by jesuslinares

This is a refactoring of the current documentation to include the new pricing model (unreleased).

I would like to keep this PR as a draft to facilitate the reviews.

Thanks.

2023-07-26 10:33 UTC, Spades0 reviewed
I left a few suggestions, LGTM after addressing them

2023-08-01 14:29 UTC, jesuslinares commented
Everything is ready to be merged, but we need to wait until the new pricing model is released before we can publish it.

2023-12-04 21:54 UTC, javimed requested changes
I think this documents update is meant to be out for 4.7. Therefore, the PR base branch must be changed to `4.7`.

Also, please consider the suggestions left so far.

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/sign-up-trial.rst
> +      .. note:: During the 14-day trial period, some settings are limited, but they do not prevent you from gaining insight into the Wazuh Cloud platform. All restrictions are removed after you make
```suggestion
      .. note:: Thoughout the 14-day trial period, some settings are limited. However, they do not prevent you from exploring and using the Wazuh Cloud platform. All restrictions are removed after you make the initial payment.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/sign-up-trial.rst
> +Once the environment is ready, access the :ref:`Wazuh WUI <cloud_wui_access>` and enroll the Wazuh agents.
```suggestion
Once the environment is ready, access the :ref:`Wazuh dashboard <cloud_wui_access>` and enroll the Wazuh agents.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/starting-faq.rst
> +Wazuh Cloud provides a comprehensive solution by hosting and managing all Wazuh components within a single integrated platform. With just a few clicks, you can effortlessly create your environment an
```suggestion
Wazuh Cloud provides a comprehensive solution by hosting and managing all Wazuh components within a single integrated platform. Wazuh cloud allows you to create your environment and enroll Wazuh agents. By leveraging Wazuh, you gain access to security capabilities, including Security Information and Event Management (SIEM) and Extended Detection and Response (XDR).
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/starting-faq.rst
> +Every environment includes support after the first payment. You can contact the Wazuh team anytime through the Help section on your Wazuh Cloud Console. You can also fill out `this form <https://wazu
```suggestion
Every environment includes support after the initial payment. You can contact the Wazuh team anytime through the Help section on your Wazuh Cloud Console. You can also fill out `this form <https://wazuh.com/cloud/#subscription>`_ to get help from the Wazuh team.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/starting-faq.rst
> +A profile refers to predefined settings that you can choose from when configuring your Wazuh Cloud environment. We have three profiles available: Small, Medium, and Large. These profiles provide read
```suggestion
A profile refers to predefined settings available for configuring your Wazuh Cloud environment. We offer three profiles: Small, Medium, and Large. They provide ready-to-use environment templates that cater to different needs and requirements. If none of these predefined profiles meet your specific requirements, you can configure your settings individually.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/starting-faq.rst
> +A setting in the context of Wazuh Cloud refers to each configuration option available for a cloud environment. These settings determine the limitations and capabilities of an environment. For example
```suggestion
In the context of Wazuh Cloud, a setting  refers to each configuration option available for a cloud environment. These settings determine the limitations and functionalities of an environment. For example, the "Active Agents" setting specifies the maximum number of active agents allowed in your environment. Note that the settings chosen for an environment directly impact its pricing, as they affect the resources allocated and functionalities available.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/starting-faq.rst
> +The indexed data, previously known as hot storage, includes the data available on the Wazuh WUI, which corresponds to the information indexed by Wazuh. This information becomes searchable and analyza
```suggestion
The indexed data, previously known as hot storage, includes the data available on the Wazuh dashboard, which corresponds to the information Wazuh indexed. This information becomes searchable and analyzable as soon as Wazuh ingests and indexes the events sent by the agents.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/starting-faq.rst
> +This Wazuh generated data is archived in an AWS S3 bucket for long-term storage purposes. Unlike the indexed data, this data is not searchable or analyzable. It simply consists of a collection of com
```suggestion
The data generated by Wazuh is archived in an AWS S3 bucket for long-term storage purposes. Unlike the indexed data, this archived data is not searchable or analyzable. It simply consists of a collection of compressed files. For more information, please see the :ref:`Archived data <cloud_your_environment_accessing_archived_data>` section.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/starting-faq.rst
> +The concept of a tier, which represents the size limitation, in bytes, of the indexed data (formerly known as hot storage), is no longer used. It has been replaced by the *indexed data size* setting.
```suggestion
The term *tier* is no longer used. It has been replaced by the *indexed data size* setting. It represented the size limitation, in bytes, of the indexed data, formerly known as *hot storage*.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/starting-faq.rst
> +When the selected **indexed data size** is reached, the oldest events will be automatically removed from your index regardless of the **index data time**. This data is available in archived data for
```suggestion
When the selected **indexed data size** is reached, Wazuh automatically removes the oldest events from your index, regardless of the **index data time**. You can access this data in archived data. See the :ref:`Archived data <cloud_your_environment_accessing_archived_data>` section to learn more about data logging and storage.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/starting-faq.rst
> +Data rotation is determined by two conditions: the indexed data time and the indexed data size. For instance, if you have set a 3-month indexed data time and a 100GB indexed data size, and you consum
```suggestion
Data rotation is determined by two conditions:

-  Indexed data time
-  Indexed data size

For example, you might have set a 3-month indexed data time and a 100 GB indexed data size. If you consumed the entire 100 GB within the first month, the data starts rotating.

Similarly, you might have not utilized all 100 GB. However, the data from the first month rotates by the fourth month even if only 20 GB is used.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/getting-started/starting-faq.rst
> +If you send more events per second than allowed by the **data ingestion rate** setting, events start queuing, and if the queue becomes full, the incoming events will be discarded, which may lead to p
```suggestion
If you send more events per second than allowed by the **data ingestion rate** setting, events start queuing, and if the queue becomes full, the incoming events get discarded, which might lead to potential event loss.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/glossary.rst
> +Archived data (formerly known as cold storage)
```suggestion
Archived data
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/glossary.rst
> +It is the data containing the output generated by Wazuh, such as alerts or archives. It is an AWS S3 bucket to store your logs for a longer time and meet compliance requirements.
```suggestion
Formerly known as cold storage, it's the data containing the output generated by Wazuh, such as alerts and archives. It's an AWS S3 bucket to store your logs for a longer time and meet compliance requirements.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/glossary.rst
> +
```suggestion
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/glossary.rst
> +Indexed data (formerly known as hot storage)
```suggestion
Indexed data
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/glossary.rst
>  It is the data available on the Wazuh WUI corresponding to the information indexed by Wazuh. This information is available as soon as Wazuh ingests and indexes the events sent by the agents, making t
```suggestion
Formerly known as hot storage, it's the data available on the Wazuh dashboard corresponding to the information indexed by Wazuh. This information is available as soon as Wazuh ingests and indexes the events sent by the agents, making the data searchable and analyzable.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/glossary.rst
> +The concept of a tier, which represents the size limitation, in bytes, of the indexed data (formerly known as hot storage), is no longer used. It has been replaced by the *indexed data size* setting.
```suggestion
The term *tier* is no longer used. It has been replaced by the *indexed data size* setting. It represented the size limitation, in bytes, of the indexed data, formerly known as *hot storage*.
```

2023-12-04 21:54 UTC, javimed commented on source/cloud-service/glossary.rst
> +A setting in the context of Wazuh Cloud refers to each of the configuration options available for a cloud environment. These settings define the limitations, capabilities, and pricing of the environm
```suggestion
In the context of Wazuh Cloud, a setting  refers to each configuration option available for a cloud environment. These settings determine the limitations, functionalities, and pricing of an environment.
```

2023-12-05 20:33 UTC, javimed requested changes
The `source/_static/js/redirects.js` file needs to be updated to reflect the new and removed pages. Please consider the additional suggestions from the latest review as well.

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +This basic setting defines the maximum number of active Wazuh agents that the environment can support. Please note that while it is possible to register an unlimited number of Wazuh agents, the numbe
```suggestion
This basic setting sets the maximum count of active Wazuh agents that the environment can support. Please note that while registering an unlimited number of Wazuh agents is possible, the active agent count is limited by this setting.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +If the maximum number of active agents is reached, the environment may start to malfunction, causing instability with agent connections. While the system can tolerate temporarily exceeding the limit
```suggestion
If the maximum number of active agents is reached, the environment might start to malfunction, causing instability with agent connections. Although the system can temporarily handle exceeding the active agent limit, appropriate measures will be taken if the situation persists.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +
```suggestion
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +The indexed data, previously known as hot storage, includes the data available on the Wazuh WUI, which corresponds to the information indexed by Wazuh. This information becomes searchable and analyza
```suggestion
The indexed data was previously known as hot storage. It includes the data available on the Wazuh dashboard, which corresponds to the information indexed by Wazuh. This information becomes searchable and analyzable as soon as Wazuh ingests and indexes the events sent by the agents.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +- Indexed data time: It determines the maximum duration for which data remains indexed. This is a basic setting.
```suggestion
-  **Indexed data time**: This basic setting defines the maximum duration for which data remains indexed.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +- Indexed data size: It defines the maximum size, in bytes, of the indexed data. This setting is equivalent to what was previously called a "tier." This is an advanced setting, and the interface prov
```suggestion
-  **Indexed data size**: This advanced setting defines the maximum size, in bytes, of the indexed data. it was formerly referred to as a "tier". The interface offers a suggestion when selecting the Indexed data time.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +- Indexed data size: It defines the maximum size, in bytes, of the indexed data. This setting is equivalent to what was previously called a "tier." This is an advanced setting, and the interface prov
It's not quite clear what the "... suggestion when selecting the Indexed data time." is all about.

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +Data remains indexed until either the indexed data time or the indexed data size is reached. In other words, once either of the settings' values is reached, data rotation will occur (removing the old
```suggestion
Data remains indexed until either the indexed data time or the indexed data size is reached. Upon reaching either setting value, data rotation initiates, removing the oldest data, until the conditions of these settings are met.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +This basic setting, previously known as cold storage, determines the duration for which the analyzed data generated by Wazuh is stored in an AWS S3 bucket for long-term storage purposes. Unlike the i
```suggestion
This basic setting, previously known as cold storage, defines the duration for which the analyzed data generated by Wazuh is stored in an AWS S3 bucket for long-term storage purposes. Unlike the indexed data, this data isn't searchable or analyzable. It simply consists of a collection of compressed files.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +When the specified time is reached, data outside that time range will be deleted.
```suggestion
When the specified time is reached, data beyond that time range will be deleted.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +It represents the maximum number of events per second (EPS) that the environment can analyze. This is an advanced setting, and the interface provides a suggestion when selecting the Active agents set
```suggestion
It represents the maximum number of events per second (EPS) that the environment can analyze. This is an advanced setting, and the interface provides a suggestion when selecting the ``Active agents`` setting.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +If the ingestion rate is exceeded, events will start to queue. However, if the queue becomes full, the incoming events will be discarded, which may lead to potential event loss. The queuing mechanism
```suggestion
If the ingestion rate is exceeded, events begin queuing. However, if the queue becomes full, wazuh discards the incoming events, which might lead to event loss. The cloud service automatically manages the queuing mechanism, ensuring optimal resource utilization.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +The environment will be configured with the `limits eps option <https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#limits>`_ using the following parameters:
```suggestion
The environment is configured with the `limits eps option <https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#limits>`_ using the following parameters:
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +The number of server nodes is automatically determined by the cloud service based on the workload. For instance, if the Data ingestion rate setting is 900 EPS and there is a cluster of 2 nodes at the
```suggestion
The cloud service automatically determines the number of server nodes  based on the workload. For instance, if the ``Data ingestion rate`` setting is ``900`` EPS and the current cluster consists of 2 nodes, each node can process up to 450 events per second.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +Managing your environment settings is crucial to meeting your evolving needs and optimizing the performance of your cloud environment. While some settings can be determined upfront, such as the numbe
```suggestion
Managing your environment settings is crucial to meet your evolving needs and optimize the performance of your cloud environment. While some settings can be determined upfront, such as the number of active agents, indexed data time, archived data, and support type, note that these requirements might change over time.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +Additionally, advanced settings may be more challenging to determine in advance. While the interface provides recommendations based on our experience, your specific workload may differ. That's why we
```suggestion
Advanced settings might be more challenging to determine in advance. While the interface provides recommendations based on our experience, your specific workload might differ. Hence, we recommend deploying, monitoring, and adjusting the settings as needed to align with your evolving requirements.
```

2023-12-05 20:33 UTC, javimed commented on source/cloud-service/your-environment/settings.rst
> +- Upgrading a setting: If you need to raise a setting, you will be charged a prorated amount based on the remaining time in your billing cycle. The change will be implemented immediately after the pa
```suggestion
-  **Upgrading a setting**: If you need to raise a setting, you will be charged a prorated amount based on the remaining time in your billing cycle. The change will be implemented immediately after the payment is made. Please note that your next billing cycle will reflect the increased cost of the enhancement.
```

2024-01-09 17:49 UTC, jesuslinares commented on source/cloud-service/your-environment/technical-faq.rst
> +If the maximum number of active agents is reached, the environment may start to malfunction, causing instability with agent connections. While the system can tolerate temporarily exceeding the limit
We will leave that undefined.

2024-01-10 17:41 UTC, jesuslinares commented on source/cloud-service/archived-data/configuration.rst
> +  Files with a ``.log`` extension are never sent to archived data.
It is just a generic way to say it.

2024-01-11 12:23 UTC, jesuslinares commented
Suggestion are reviewed and 4.7 branch is merged.

Thanks @javimed!

2024-01-16 15:11 UTC, merged