Add agent version filter option
wazuh/wazuh-documentation pull request #6312
Opened 2023-08-07 15:02 UTC by GGP1

|Parent issue|Source issue|Related issue | Related PR|
|---|---|---|---|
| https://github.com/wazuh/wazuh/issues/18138 | https://github.com/wazuh/wazuh/issues/11011 | https://github.com/wazuh/wazuh/issues/18139 | https://github.com/wazuh/wazuh/pull/18212 |

## Description

Added the `agents -> allow_higher_versions -> allow` option to the API configuration documentation page.

> I used the default value and range indicated in https://github.com/wazuh/wazuh/issues/18138

### Screenshots

![schema](https://github.com/wazuh/wazuh-documentation/assets/51374959/66d5a6c1-338e-4c12-94f9-6e92c02bbfdf)

![config](https://github.com/wazuh/wazuh-documentation/assets/51374959/753f59c6-5dcb-4e53-9331-9f5fd0844f0c)

2023-08-08 07:46 UTC, Selutario requested changes
The table is malformed:
![image](https://github.com/wazuh/wazuh-documentation/assets/23361101/cbdcc5a5-8cbf-4c6d-811f-d036518fbb9c)
![image](https://github.com/wazuh/wazuh-documentation/assets/23361101/28c824ed-28d4-454b-8d59-21602dfb1148)

2023-08-08 07:46 UTC, Selutario commented on source/user-manual/api/configuration.rst
> +| allow      | yes, no              | yes          | Allow uploading configurations accepting higher agent versions through the Wazuh API. Setting this option to ``false`` prevents uploading ``ossec.
```suggestion
| allow      | yes, true, no, false | true          | Allow uploading configurations accepting higher agent versions through the Wazuh API. Setting this option to ``false`` prevents uploading ``ossec.conf`` files that contain the ``<agents><allow_higher_versions>`` section with value ``yes`` inside the :ref:`global tag <reference_ossec_global>`.                                       |
```

2023-08-10 13:34 UTC, s-ocando commented on source/user-manual/api/configuration.rst
> +| allow      | yes, true, no, false | true          | Allow uploading configurations accepting higher agent versions through the Wazuh API. Setting this option to ``false`` prevents uploading ``ossec
```suggestion
| allow      | yes, true, no, false | true          | Allow uploading configurations that accept higher agent versions through the Wazuh API. Setting this option to ``false`` prevents uploading ``ossec.conf`` files that contain the ``<agents><allow_higher_versions>`` section with the ``yes`` value inside the :ref:`global tag <reference_ossec_global>`.                                 |
```

2023-08-11 07:12 UTC, Selutario requested changes

2023-08-11 07:12 UTC, Selutario commented on source/user-manual/api/configuration.rst
> +| allow      | yes, true, no, false | true          | Allow uploading configurations that accept higher agent versions through the Wazuh API. Setting this option to ``false`` prevents uploading ``oss
After the last changes made [here](https://github.com/wazuh/wazuh/pull/18342), this part needs to be updated:

```suggestion
| allow      | yes, true, no, false | true          | Allow uploading configurations that accept higher agent versions through the Wazuh API. Setting this option to ``false`` prevents uploading ``ossec.conf`` files that contain the ``<allow_higher_versions>`` section with the ``yes`` value inside the :ref:`auth <reference_ossec_auth>` or :ref:`remote <reference_ossec_remote>` tags.  |
```

2023-08-11 07:21 UTC, s-ocando approved these changes

2023-08-11 07:25 UTC, Selutario approved these changes

2023-08-11 07:29 UTC, merged