Add <allow_higher_versions> to 'remote' and 'auth' sections
wazuh/wazuh-documentation pull request #6333
Opened 2023-08-10 20:54 UTC by nbertoldo

## Description

As requested in #6284 the documentation for the remote and auth configuration sections are updated with new `agents/allow_higher_versions` options.

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-08-10 20:56 UTC, nmkoremblum approved these changes
LGTM

2023-08-10 21:18 UTC, javimed approved these changes

2023-08-10 21:18 UTC, javimed commented on source/user-manual/reference/ossec-conf/auth.rst
> +Accept agents with a higher version than the current manager.
```suggestion
Accept agents with a later version than the current manager.
```

2023-08-10 21:18 UTC, javimed commented on source/user-manual/reference/ossec-conf/auth.rst
> +  This option only works when **connection** is set to ``secure``.
```suggestion

   This option only works when **connection** is set to ``secure``.
```

2023-08-10 21:18 UTC, javimed commented on source/user-manual/reference/ossec-conf/remote.rst
> +Accept agents with a higher version than the current manager.
```suggestion
Accept agents with a later version than the current manager.
```

2023-08-10 21:18 UTC, javimed commented on source/user-manual/reference/ossec-conf/remote.rst
> +  This option only works when **connection** is set to ``secure``.
```suggestion

   This option only works when **connection** is set to ``secure``.
```

2023-08-11 08:25 UTC, vikman90 requested changes
~We're missing the JSON configuration report.~
Please disregard this comment.

2023-08-11 13:04 UTC, vikman90 approved these changes

2023-08-11 17:15 UTC, merged