Remove deprecated plain text auth references for wodles
wazuh/wazuh-documentation pull request #6405
Opened 2023-08-30 20:01 UTC by nico-stefani

## Description

This PR closes #6363. Removes the plain text authentication references for AWS and Azure wodles configurations.

## Checks
### Docs building
- [ ] Compiles without warnings.

Actually, there are some warnings in the base branch `5.0`.

<details><summary>Build Output</summary>
<p>

```bash
(wdocs) ➜  wazuh-documentation git:(5.0) make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v3.4.3
loading translations [en-US]... not available for built-in messages
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 691 source files that are out of date
updating environment: 0 added, 6 changed, 0 removed
reading sources... [100%] user-manual/reference/ossec-conf/wodle-s3
Copying static files for wazuh-doc-images...[100%] img/loading.gif
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user-manual/wazuh-dashboard/troubleshooting
/home/nstefani/git/wazuh-documentation/source/amazon/services/supported-services/trusted-advisor.rst:187: WARNING: undefined label: reference_ossec_conf
/home/nstefani/git/wazuh-documentation/source/deployment-options/deploying-with-ansible/reference.rst:162: WARNING: unknown document: /user-manual/reference/ossec-conf/logging
/home/nstefani/git/wazuh-documentation/source/deployment-options/deploying-with-ansible/reference.rst:513: WARNING: unknown document: /user-manual/reference/ossec-conf/labels
/home/nstefani/git/wazuh-documentation/source/deployment-options/deploying-with-ansible/reference.rst:1215: WARNING: unknown document: /user-manual/reference/ossec-conf/labels
/home/nstefani/git/wazuh-documentation/source/deployment-options/deploying-with-ansible/reference.rst:1228: WARNING: unknown document: /user-manual/reference/ossec-conf/active-response
/home/nstefani/git/wazuh-documentation/source/deployment-options/deploying-with-ansible/reference.rst:1241: WARNING: unknown document: /user-manual/reference/ossec-conf/logging
/home/nstefani/git/wazuh-documentation/source/user-manual/capabilities/active-response/custom-active-response-scripts.rst:9: WARNING: unknown document: /user-manual/reference/ossec-conf/active-response
/home/nstefani/git/wazuh-documentation/source/user-manual/capabilities/active-response/how-to-configure.rst:72: WARNING: unknown document: /user-manual/reference/ossec-conf/active-response
/home/nstefani/git/wazuh-documentation/source/user-manual/capabilities/file-integrity/basic-settings.rst:11: WARNING: unknown document: /user-manual/reference/ossec-conf/index
/home/nstefani/git/wazuh-documentation/source/user-manual/capabilities/file-integrity/how-to-configure-fim.rst:11: WARNING: unknown document: /user-manual/reference/ossec-conf/index
/home/nstefani/git/wazuh-documentation/source/user-manual/capabilities/file-integrity/how-to-configure-fim.rst:41: WARNING: unknown document: /user-manual/reference/ossec-conf/index
/home/nstefani/git/wazuh-documentation/source/user-manual/capabilities/file-integrity/windows-registry-monitoring.rst:37: WARNING: undefined label: reference_agent_conf
/home/nstefani/git/wazuh-documentation/source/user-manual/capabilities/malware-detection/rootkits-behavior-detection.rst:113: WARNING: unknown document: ../../reference/ossec-conf/index
/home/nstefani/git/wazuh-documentation/source/user-manual/capabilities/malware-detection/virus-total-integration.rst:87: WARNING: unknown document: /user-manual/reference/ossec-conf/index
/home/nstefani/git/wazuh-documentation/source/user-manual/capabilities/vulnerability-detection/configuring-scans.rst:23: WARNING: unknown document: /user-manual/reference/ossec-conf/index
/home/nstefani/git/wazuh-documentation/source/user-manual/ruleset/testing.rst:28: WARNING: unknown document: /user-manual/reference/ossec-conf/index
generating indices... done
writing additional pages... not_found moved-content search done
copying images... [100%] user-manual/wazuh-dashboard/../../images/kibana-app/features/settings/about.png
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 16 warnings.
```

</p>
</details> 

### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-08-31 18:14 UTC, GGP1 approved these changes
LGTM

2023-09-25 08:23 UTC, Selutario requested changes
The release type for this issue is `patch`, in this PR we should only remove the examples since it makes no sense to show examples of something that we do not recommend using.

Removing all mentions to credentials in configuration could be done in a different PR in the future.

2023-09-25 08:23 UTC, Selutario commented on source/amazon/services/prerequisites/credentials.rst
> -  </bucket>
According to what I said above, this should remain in order to be merged in a `path` version, so only examples should be removed.

2023-09-25 08:23 UTC, Selutario commented on source/azure/activity-services/prerequisites/credentials.rst
> -Inserting the credentials into the configuration
Same with this, we will need to remove it in 5.0.0, but we should stop showing examples before.

2023-09-25 08:23 UTC, Selutario commented on source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
Only examples should be removed for now. If you prefer, you can open a new issue for it and assign this PR to the new issue. Then, create a PR for the original issue (https://github.com/wazuh/wazuh-documentation/issues/6363) only for removing examples.

2024-02-21 12:35 UTC, GGP1 requested changes

2024-02-21 12:35 UTC, GGP1 commented on source/cloud-security/azure/activity-services/prerequisites/credentials.rst
>  It is possible to store the credentials in a file for authentication as long as the file content follows the `field = value` format explained below.
Now that the `Authentication options` title was removed, this subtitle lacks some context. I would suggest doing something like

```
Authentication
---------------

To authenticate, store the credentials in a file whose content follows the `field = value` format explained below.
```

2024-02-21 14:11 UTC, GGP1 approved these changes
LGTM

2024-02-26 11:08 UTC, Selutario approved these changes

2024-02-27 14:54 UTC, javimed requested changes

2024-02-27 14:54 UTC, javimed commented on source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
> +Path of the file that contains the application identifier and the application key for authentication in order to use the Azure Log Analytics API.
```suggestion
File path containing the application identifier and key for authentication. This is necessary to use the Azure Log Analytics API.
```

2024-02-27 14:54 UTC, javimed commented on source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
> +Path of the file that contains the application identifier and the application key for authentication in order to use the AAD Graph API.
```suggestion
File path containing the application identifier and key for authentication. This is necessary to use the AAD Graph API.
```

2024-02-27 14:54 UTC, javimed commented on source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
> +Path of the file that contains the account name and the account key for authentication.
```suggestion
File path containing the account name and key for authentication.
```

2024-02-29 20:39 UTC, javimed approved these changes
LGTM

2024-02-29 20:40 UTC, merged