Add support for Amazon Linux 2023 in Vulnerability Detector
wazuh/wazuh-documentation pull request #6446
Opened 2023-09-06 20:52 UTC by Leoquicenoz

## Description

|Related issue|
|---|
|#6366|

With the addition of a new version (`Amazon Linux 2023`) to the **Amazon Linux** support in the **Vulnerability Detector** module, **Wazuh**'s documentation needs to be updated to include references about this new OS version in the correspondent pages.

The main points to cover include:

- [x] The Vulnerability Detector section must include the new feed and the Amazon Linux 2022 as a supported platform
- [x] All vulnerability-related usage guides must be updated with information and configuration examples for the new OS version. 

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns.

2023-09-07 13:06 UTC, mateocervilla requested changes

2023-09-07 13:06 UTC, mateocervilla commented on source/user-manual/reference/ossec-conf/vuln-detector.rst
> +|                    |                           |                    |              +-----------------------------------------------------------------------------------------------------------------
```suggestion
|                    |                           |                    |              +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

2023-09-07 13:06 UTC, mateocervilla commented on source/user-manual/reference/ossec-conf/vuln-detector.rst
> +|                    |                           |                    |              | amazon-linux-2022 / 2022
```suggestion
|                    |                           |                    |              | amazon-linux-2022 / 2022                                                                                                                                                                                                                                                  |
```

2023-09-19 18:44 UTC, MarcelKemp requested changes
Add what is supported and missing from Amazon Linux in the following files:
- `source/deployment-options/deploying-with-ansible/reference.rst`
- `source/user-manual/capabilities/vulnerability-detection/configuring-scans.rst`
- `source/user-manual/capabilities/vulnerability-detection/how-it-works.rst`

2023-09-20 12:06 UTC, MarcelKemp approved these changes

2023-09-20 21:09 UTC, javimed reviewed
What if we also add a local path in this sample offline configuration:

- https://github.com/wazuh/wazuh-documentation/pull/6446/files#diff-bb9d48338874e2ba0c70be0cfd88ba34a0eef3e863218c947ee87305845238d1R509-R510

2023-09-21 11:22 UTC, javimed approved these changes

2023-09-21 13:29 UTC, merged