Email App version for Shuffle
wazuh/wazuh-documentation pull request #6502
Opened 2023-09-13 12:31 UTC by RamosFe

## Description
Adds a specific version for the `Email App` used in the Shuffle Integration.

2023-09-13 15:21 UTC, javiersanchz approved these changes

2023-09-14 10:10 UTC, Selutario approved these changes

2023-09-14 15:43 UTC, javimed requested changes
What about rather specifying it within step #1? Something like this:

1. Go to Shuffle and make a Workflow **using the Email app. Select version `1.0.1` for it**.

2. Set Recipients and Subject in the email configuration. Put `$exec` in the Body to include the alert information.

2023-09-18 12:15 UTC, RamosFe commented
> What about rather specifying it within step #1? Something like this:
> 
> 1. Go to Shuffle and make a Workflow **using the Email app. Select version `1.0.1` for it**.
> 2. Set Recipients and Subject in the email configuration. Put `$exec` in the Body to include the alert information.

Changed documentation:
https://github.com/wazuh/wazuh-documentation/blob/9f273b7eed4a9c4c928a826a214588f9726de579/source/user-manual/manager/manual-integration.rst?plain=1#L150-L152

2023-09-18 12:59 UTC, javimed approved these changes

2023-09-18 12:59 UTC, merged