Fix in GCP configuration examples
wazuh/wazuh-documentation pull request #6509
Opened 2023-09-14 10:48 UTC by javiersanchz

## Description

Correction has been made to the GPC configuration example, empty spaces were removed, and the `<project_id>` and `<subscription_name>` fields were also deleted from `<gcp-bucket>` since they are specific to `pubsub`, as mentioned in  #6482 

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-09-14 12:31 UTC, fdalmaup requested changes

2023-09-14 15:05 UTC, fdalmaup approved these changes
LGTM!

2023-09-15 11:14 UTC, Selutario requested changes
There is also a wrong example in the [Configuration example](https://github.com/wazuh/wazuh-documentation/blob/feature/6482-errors-gcp-configuration-examples/source/user-manual/reference/ossec-conf/gcp-bucket.rst#configuration-example) section of the `Local configuration (ossec.conf) > gcp-bucket` page.

Please, update it too.

2023-09-15 11:59 UTC, Selutario approved these changes

2023-09-15 15:16 UTC, javimed approved these changes

2023-09-15 15:17 UTC, merged