Change python 3.11 pyarrow dependency version
wazuh/wazuh-documentation pull request #6513
Opened 2023-09-15 16:59 UTC by GGP1

## Description

Closes https://github.com/wazuh/wazuh-documentation/issues/6470.

Updates the pyarrow dependency version to `13.0.0` for the installation carried out in python 3.11 and removes indirect dependencies.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-09-18 11:00 UTC, javiersanchz requested changes
It seems that the changes made are correct. However, conflicts must be resolved before this pull request can be merged

2023-09-18 13:07 UTC, mhamra approved these changes
Issue reviewed. The investigation is proper, and the modifications to the documentation are correct.

2023-09-18 13:13 UTC, javiersanchz approved these changes

2023-09-19 11:43 UTC, Selutario approved these changes

2023-09-19 12:35 UTC, javimed approved these changes

2023-09-19 12:35 UTC, merged