Rename Azure Active Directory to Microsoft Entra ID
wazuh/wazuh-documentation pull request #6592
Opened 2023-10-03 19:48 UTC by GGP1

## Description

Updated the Azure Active Directory terminology according to Microsoft's new [glossary](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/new-name#glossary-of-updated-terminology). 

Following their [decision](https://devblogs.microsoft.com/identity/aad-rebrand/), I haven't updated directory names, URLs or file names to avoid breaking links to the documentation.

Furthermore, the Azure Active Directory Graph API is deprecated but it is still operational and shouldn't be changed.

## Checks
### Docs building
- [x] Compiles without warnings.

<details><summary>build</summary>

```console
Running Sphinx v7.0.1
loading translations [en-US]... not available for built-in messages
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] cloud-security/azure/activity-services/active-directory/index                                                                                             
Copying static files for wazuh-doc-images...[100%] img/loading.gif                                                                                                                  
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                                      
generating indices... done
writing additional pages... not_found moved-content search done
copying images... [100%] images/cloud-security/azure/aad-graph-intro.png                                                                                                            
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in home/python/build/html.
[sphinx-autobuild] Serving on http://0.0.0.0:8000
```

</details>

### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-10-04 17:23 UTC, GGP1 commented on source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
> +Key to the application we will use for authentication and to be able to use the Azure Active Directory Graph API. It must be used next to the ``application_id`` option obligatorily. Incompatible with
As I mentioned in the PR description, the Azure Active Directory Graph API is still operational and it is different from the Microsoft Graph API

2023-10-06 11:06 UTC, Selutario requested changes
LGTM. However, since Microsoft already renamed their service, the sooner we update our documentation the better. Therefore, we should merge this change in [4.5](https://github.com/wazuh/wazuh-documentation/tree/4.5), which is the production branch.

2023-11-06 14:00 UTC, Selutario commented
Sorry @GGP1, we published 4.6.0 and this was not approved & merged in 4.5, so it needs to be rebased (again) to 4.6. Let me know as soon as it is ready again so I approve it.

2023-11-07 11:15 UTC, Selutario approved these changes

2023-11-07 16:37 UTC, javimed reviewed
Please also consider changing this if applicable

![image](https://github.com/wazuh/wazuh-documentation/assets/47069802/559e6a95-e38f-477b-aa46-a0389e1db87d)

2023-11-07 16:37 UTC, javimed commented on source/user-manual/user-administration/index.rst
>  In the LDAP integration section, you can find instructions on how to integrate Wazuh with LDAP/Active Directory to authenticate and authorize users.
Please consider the following "Active Directory" occurrences, if applicable:

- Up here, where it says "_LDAP/**Active Directory** to authenticate and authorize users_".
- In RBAC `/user-manual/user-administration/rbac` section.
- In the new LDAP `/user-manual/user-administration/ldap` section.
-  In `/user-manual/user-administration/single-sign-on/` sections. Please consider a url change and redirection for the `azure-active-directory` page.

2023-11-08 14:59 UTC, javimed approved these changes

2023-11-08 18:09 UTC, merged