Add update_check config reference
wazuh/wazuh-documentation pull request #6673
Opened 2023-10-23 14:17 UTC by nico-stefani

## Description

This PR closes #6641. Adds reference for the new configuration (`update_check`) in the `global` section of the `ossec.conf`. 

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-10-24 20:27 UTC, fdalmaup approved these changes
LGTM!

2023-10-26 09:23 UTC, Selutario requested changes

2023-10-26 09:23 UTC, Selutario commented on source/user-manual/reference/ossec-conf/global.rst
> +This toggles whether to query an external service to retrieve any available update from the dashboard.
```suggestion
This toggles whether to query the external Wazuh CTI service to retrieve the available Wazuh updates.
```

2023-10-26 15:07 UTC, Selutario approved these changes

2023-10-26 19:55 UTC, javimed commented on source/user-manual/reference/ossec-conf/global.rst
> +This toggles whether to query the external Wazuh CTI service to retrieve the available Wazuh updates.
```suggestion
This setting toggles whether to query the external Wazuh Cyber Threat Intelligence (CTI) service for any available Wazuh updates.
```

2023-10-27 12:55 UTC, javimed approved these changes

2023-10-27 12:56 UTC, merged