Adds missing RBAC References.
wazuh/wazuh-documentation pull request #6693
Opened 2023-10-27 14:22 UTC by RamosFe

Issue: https://github.com/wazuh/wazuh-documentation/issues/6422

## Description
Adds PUT /decoders/files/{filename} and PUT /rules/files/{filename} missing RBAC policies.

2023-10-30 13:03 UTC, GGP1 requested changes

2023-10-30 13:03 UTC, GGP1 commented on source/user-manual/api/rbac/reference.rst
> +- :api-ref:`PUT /rules/files/{filename} <operation/api.controllers.rule_controller.put_file>` (`*:*`_)
The reference should be under `rules:update`

2023-10-30 15:55 UTC, GGP1 approved these changes
LGTM

2023-11-10 10:44 UTC, Selutario requested changes
LGTM, but since the `release type` is `patch`, this should not be targeting `master` branch. 
![image](https://github.com/wazuh/wazuh-documentation/assets/23361101/5394152b-185e-462b-a682-1c1a95b2e7c9)

Change the base branch to 4.7.1 or even 4.6 (so it takes effect almost instantly)

2023-11-10 13:07 UTC, Selutario approved these changes

2023-11-10 20:45 UTC, javimed approved these changes

2023-11-10 20:45 UTC, merged