Modify bucket popfsenselicies template
wazuh/wazuh-documentation pull request #6769
Opened 2023-11-17 14:34 UTC by fdalmaup

## Description
Closes #6733. It enhances the `Policy configuration` section of the different types of buckets to clarify how the policy for fetching logs should be modified.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-11-17 17:31 UTC, GGP1 requested changes

2023-11-17 17:49 UTC, GGP1 approved these changes

2023-11-20 16:53 UTC, Selutario approved these changes

2023-11-21 12:31 UTC, javimed requested changes

2023-11-21 12:31 UTC, javimed commented on source/_templates/cloud/amazon/bucket_policies.rst
> +.. note:: ``<bucket-name>`` is a placeholder, replace it with the name of the bucket where you want to fetch the logs from.
```suggestion
.. note:: ``<bucket-name>`` is a placeholder. Replace it with the actual name of the bucket from which you want to retrieve logs.
```

2023-11-21 12:31 UTC, javimed commented on source/_templates/cloud/amazon/bucket_policies.rst
We could  highlight each `<bucket-name>` line where the user needs to replace with the bucket name

```
.. code-block:: json
   :emphasize-lines: 12,13

```

and

```
.. code-block:: json
   :emphasize-lines: 13,14

   {
```

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/3c0950e8-5533-47a0-ac83-c8d5b87178bc)

2023-11-22 17:47 UTC, javimed approved these changes

2023-11-22 17:49 UTC, merged