Change custom branding top logo configuration
wazuh/wazuh-documentation pull request #6779
Opened 2023-11-22 18:41 UTC by asteriscos

## Description
Hi team, this pull request changes the custom branding configuration. It changes a few descriptions and adds a new way to change the top header logo in the `opensearch_dashboards.yml` configuration.

Closes #6774 

![custom-branding-settings-health-check](https://github.com/wazuh/wazuh-documentation/assets/9343732/371b3d99-92ed-4b7d-952d-5c93b062fdf7)

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-11-23 07:29 UTC, Desvelao commented on source/user-manual/wazuh-dashboard/custom-branding.rst
> +To customize the `Wazuh dashboard home logo` in the top header, you have to edit the file ``/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml`` and add the URL of the default and dark theme
**nitpick**: The configuration file in the `.rpm`, and `.deb` is located at `/etc/wazuh-dashboard/opensearch_dashboards.yml` (see https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html#configuring-the-wazuh-dashboard) while the Docker distribution could have using the `/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml` (see https://github.com/wazuh/wazuh-docker/blob/4.8.0/build-docker-images/wazuh-dashboard/config/entrypoint.sh#L20). We should review it.

2023-11-24 12:39 UTC, Desvelao approved these changes
LGTM!

2023-11-24 17:50 UTC, javimed requested changes

2023-11-24 17:50 UTC, javimed commented on source/images/kibana-app/features/white-labeling/custom-branding-settings-health-check.png
We could add a square surrounding the logo image we're customizing

2023-11-24 17:50 UTC, javimed commented on source/images/kibana-app/features/white-labeling/custom-branding-settings-loading.png
We could add a square surrounding the logo image we're customizing

2023-11-24 19:19 UTC, asteriscos commented on source/images/kibana-app/features/white-labeling/custom-branding-settings-loading.png
done!

2023-11-24 19:19 UTC, asteriscos commented on source/images/kibana-app/features/white-labeling/custom-branding-settings-health-check.png
done!

2023-11-24 20:25 UTC, javimed approved these changes

2023-11-24 20:25 UTC, merged