Add AWS Cloudtrail policies reference in PoC
wazuh/wazuh-documentation pull request #6785
Opened 2023-11-23 15:28 UTC by fdalmaup

## Description

Closes #6768. It adds a reference to the AWS policies prerequisite in the `Monitoring AWS infrastructure` PoC page to avoid any permissions problem that may arise if the user does not check the `AWS CloudTrail` service page of the documentation.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-11-23 17:25 UTC, GGP1 approved these changes
LGTM

2023-11-24 12:43 UTC, Selutario approved these changes

2023-12-01 12:34 UTC, javimed requested changes

2023-12-01 12:34 UTC, javimed commented on source/proof-of-concept-guide/aws-infrastructure-monitoring.rst
> +| Amazon CloudTrail  | AWS Cloudtrail, like all other supported AWS services, requires setting the :ref:`necessary policies <policy_cloudtrail>` for the user's permissions, and providing a valid auth
```suggestion
| Amazon CloudTrail  | AWS Cloudtrail, like all other supported AWS services, requires setting the :ref:`necessary policies <policy_cloudtrail>` for user permissions and providing a valid authentication method. In this PoC, we use the :ref:`profile authentication <aws_profile>` method.   |
```

2023-12-01 12:56 UTC, javimed approved these changes

2023-12-01 12:56 UTC, merged