Update urllib3 library version
wazuh/wazuh-documentation pull request #6824
Opened 2023-12-01 16:34 UTC by GGP1

## Description

Adds the `urllib3==1.26.18` library to be compatible with the `docker` version used.

> Used 4.7.2 as the base branch because it's the version used in production and this needs to be fixed as soon as possible.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-12-01 18:38 UTC, fdalmaup requested changes
Since the dependencies in our [requirements.txt](https://github.com/wazuh/wazuh/blob/4.7.2/framework/requirements.txt#L26) file force the version to be `docker==4.2.0` and `urllib3==1.26.5`, if we change the documentation to be `docker==6.1.1` we would need to modify these in the embedded interpreter to keep consistency. 

An alternative to this could be adding the `urllib3==1.26.5` version in the docs commands to limit the searched `urllib` since it is required to be `>=1.21.1`, and open an issue to upgrade `docker` for a minor version. Also, consider that an update on the `urllib3` dependency is currently [ongoing](https://github.com/wazuh/wazuh/issues/20001).

2023-12-01 19:12 UTC, fdalmaup approved these changes
LGTM!

2023-12-04 12:32 UTC, Selutario reviewed
As @fdalmaup mentioned, urllib3 is being [upgraded](https://github.com/wazuh/wazuh/issues/20001) to `1.26.18` to fix some vulnerabilities. 

Since said change is just a patch, there should be no compatibility issues, but can you ensure that this is the case and, if so, use said version in the docu as well? This way we prevent users from installing a version with known vulnerabilities (`1.26.5`). 

It would also be nice to open a new issue to upgrade the docker version in the future, both in the embedded python and in the documentation for agents.

2023-12-04 15:32 UTC, Selutario approved these changes

2023-12-06 13:30 UTC, javimed approved these changes

2023-12-06 13:31 UTC, merged