Modify Azure Storage container name and remove path
wazuh/wazuh-documentation pull request #6835
Opened 2023-12-07 15:22 UTC by fdalmaup

## Description

Closes #6563. Removes the use of the `container/path` option and changes the `container name` in the Azure Storage use case to keep consistency with the values shown in the images. This option is not mandatory, so the user can learn about it in the [Azure module](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-azure-logs.html) reference.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-12-07 17:50 UTC, GGP1 requested changes
The issue reported that the field `<path>` had no clear definition but it is explained in the [reference page](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-azure-logs.html#storage-container-path) mentioned just below the example. An option could be to use `<path>path-to-logs</path>` but removing it is also a okay.

2023-12-07 17:50 UTC, GGP1 commented on source/cloud-security/azure/activity-services/services/storage.rst
> +Applying the following configuration, the integration will be executed every day using a credentials file for authentication. The contents of the ``insights-logs-auditlogs`` will be processed, downlo
```suggestion
Applying the following configuration, the integration will be executed every day using a credentials file for authentication. The ``insights-logs-auditlogs`` container content will be processed, downloading every blob available with the ``.json`` extension from the last ``24 hours``. The content for these blobs is expected to be in ``json_inline`` format.
```

2023-12-07 17:50 UTC, GGP1 commented on source/cloud-security/azure/activity-services/services/storage.rst
> +Thanks to the following rules, already included in Wazuh ruleset by default, it is possible to monitor the infrastructure activity and get the related alerts:
```suggestion
Thanks to the following rules, already included in the default Wazuh ruleset, it is possible to monitor the infrastructure activity and obtain related alerts:
```

2023-12-07 18:18 UTC, GGP1 approved these changes
LGTM

2023-12-15 11:31 UTC, Selutario approved these changes

2023-12-18 16:15 UTC, javimed approved these changes

2023-12-18 16:16 UTC, merged