Update GCP credentials docs
wazuh/wazuh-documentation pull request #6837
Opened 2023-12-07 16:18 UTC by GGP1

## Description

Improves the GCP credentials documentation by adding a new section explaining how to create a custom role for the gcp-bucket module and a service account creation image.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-12-07 19:08 UTC, fdalmaup requested changes

2023-12-07 19:08 UTC, fdalmaup commented on source/cloud-security/gcp/prerequisites/credentials.rst
> +    :width: 100%
```suggestion
To do so, follow these steps:

1. Go to the **Roles** section and click on **Create Role**.
2. Once you have chosen a name, click on **Add Permissions**.
3. On the search bar type **Storage Legacy Bucket Writer** and assign the following permissions:

   - ``storage.bucket.get``
   - ``storage.objects.create``
   - ``storage.objects.delete``
   - ``storage.objects.list``

.. thumbnail:: /images/cloud-security/gcp/gcp-bucket-role.png
    :align: center
    :width: 100%

4. Click on **Create**.
```

Also, the different fields could be highlighted in the image.


```

2023-12-11 12:31 UTC, GGP1 commented on source/cloud-security/gcp/prerequisites/credentials.rst
> +4. Click on **Create**.
In the previous suggestion the 4th point was below the image but it didn't look so good once compiled, so I included this point below the other ones

![screenshot](https://github.com/wazuh/wazuh-documentation/assets/51374959/1bc86cc8-ec27-4d27-b7e9-b5e313d9d4cc)

2023-12-12 14:26 UTC, fdalmaup approved these changes
LGTM!

2023-12-14 17:32 UTC, Selutario approved these changes

2023-12-14 21:18 UTC, javimed requested changes

2023-12-14 21:18 UTC, javimed commented on source/cloud-security/gcp/prerequisites/credentials.rst
> +The ``gcp-bucket`` module requires permissions to access storage buckets and objects. These permissions were originally assigned using the **Storage Legacy Bucket Writer** role, but it is no longer a
Originally... but it is no longer available..? When? What does all this mean?

2023-12-14 21:18 UTC, javimed commented on source/cloud-security/gcp/prerequisites/credentials.rst
> +To do so, follow these steps:
```suggestion
To create the new role, follow these steps:
```

2023-12-14 21:18 UTC, javimed commented on source/cloud-security/gcp/prerequisites/credentials.rst
> +1. Go to the **Roles** section and click on **Create Role**.
```suggestion
#. Go to the **Roles** section and click on **Create Role**.
```

2023-12-14 21:18 UTC, javimed commented on source/cloud-security/gcp/prerequisites/credentials.rst
> +2. Choose a name and click on **Add Permissions**.
```suggestion
#. Establish a **Title** and click on **Add Permissions**.
```

2023-12-14 21:18 UTC, javimed commented on source/cloud-security/gcp/prerequisites/credentials.rst
> +3. On the search bar, type **Storage Legacy Bucket Writer** and select the following permissions:
```suggestion
#. On the search bar, filter available permissions by typing **Storage Legacy Bucket Writer**. Select the following ones:
```

2023-12-15 19:06 UTC, javimed requested changes

2023-12-15 19:06 UTC, javimed commented on source/cloud-security/gcp/prerequisites/credentials.rst
> +The ``gcp-bucket`` module requires permissions to access storage buckets and objects. These permissions were originally assigned using the **Storage Legacy Bucket Writer** role, but it is no longer a
```suggestion
The ``gcp-bucket`` module requires permissions to access storage buckets and objects. To create a role with the required permissions, follow these steps:
```

2023-12-15 19:06 UTC, javimed commented on source/cloud-security/gcp/prerequisites/credentials.rst
> +To create the new role, follow these steps:
```suggestion
```

2023-12-15 19:06 UTC, javimed commented on source/cloud-security/gcp/prerequisites/credentials.rst
> +
```suggestion
```

2023-12-15 19:32 UTC, javimed approved these changes

2023-12-15 19:33 UTC, merged