Add AWS Security Lake alert visualization in Wazuh dashboard
wazuh/wazuh-documentation pull request #6838
Opened 2023-12-07 17:09 UTC by fdalmaup

## Description

Closes #6477. It adds a new section to the Amazon Security Lake page describing how to visualize the alerts generated by the module in the Wazuh dashboard. Also, highlights in a note how the events fetching time depends on the number of messages present in the queue.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-12-11 14:53 UTC, GGP1 requested changes

2023-12-11 14:53 UTC, GGP1 commented on source/cloud-security/amazon/services/supported-services/security-lake.rst
> +Once you set the configuration and restart the manager, you can visualize the Amazon Security Lake alerts in the Wazuh dashboard. To do this, go to the ``Security events`` module and, for better visu
We should use bold for user interface elements

```suggestion
Once you set the configuration and restart the manager, you can visualize the Amazon Security Lake alerts in the Wazuh dashboard. To do this, go to the **Security events** module and, for better visualization, apply the filter ``rule.groups: amazon_security_lake``:
```

2023-12-12 14:38 UTC, GGP1 approved these changes
LGTM

2023-12-13 08:30 UTC, Selutario requested changes
All good, just a small detail.

2023-12-13 08:30 UTC, Selutario commented on source/images/aws/security-lake-1.png
According to previous reviews, this red box should probably be `#3585F9`:
- https://github.com/wazuh/wazuh-documentation/pull/6694#discussion_r1396226482

2023-12-14 09:07 UTC, Selutario approved these changes

2023-12-14 20:24 UTC, javimed reviewed
I'm leaving some suggestions for your consideration.

2023-12-14 20:24 UTC, javimed commented on source/cloud-security/amazon/services/supported-services/security-lake.rst
> +    The module's time of execution varies depending on the number of notifications present in the queue. This directly influences the time you have to wait to see every alert on the Wazuh dashboard.
```suggestion

   The module execution time varies depending on the number of notifications in the queue. This affects the time to display alerts on the Wazuh dashboard. If the ``<interval>`` value is less than the execution time, the :ref:`Interval overtaken <interval_overtaken_message>` message appears in the ``ossec.log`` file.
```

2023-12-14 20:24 UTC, javimed commented on source/cloud-security/amazon/services/supported-services/security-lake.rst
> +Once you set the configuration and restart the manager, you can visualize the Amazon Security Lake alerts in the Wazuh dashboard. To do this, go to the **Security events** module and, for better visu
```suggestion
Once you set the configuration and restart the manager, you can visualize the Amazon Security Lake alerts in the Wazuh dashboard. To do this, go to the **Security events** module. Apply the filter ``rule.groups: amazon_security_lake`` for an easier visualization.
```

2023-12-15 19:14 UTC, javimed approved these changes

2023-12-15 19:15 UTC, merged