Add deprecation notes to Syscheck and Syscollector related sections
wazuh/wazuh-documentation pull request #6853
Opened 2023-12-14 15:23 UTC by fdalmaup

## Description
Part of https://github.com/wazuh/wazuh/issues/20792. Adds deprecation marks to sections related to the `syscheck` and `syscollector` endpoints.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-12-14 18:17 UTC, EduLeon12 submitted a review, later dismissed
LGTM!

2023-12-15 12:58 UTC, Selutario requested changes
There are two places where `GET /syscollector` is still being mentioned and should add a  deprecation note (and probably updated with the new recommended method, although this will be a core task):
https://github.com/wazuh/wazuh-documentation/blob/c1e5637f11656a597e231404065f8fff06e4ec6d/source/user-manual/capabilities/system-inventory/viewing-system-inventory-data.rst?plain=1#L37-L206

https://github.com/wazuh/wazuh-documentation/blob/c1e5637f11656a597e231404065f8fff06e4ec6d/source/user-manual/capabilities/vulnerability-detection/cpe-helper.rst?plain=1#L166-L596

2023-12-18 08:48 UTC, Selutario approved these changes

2023-12-18 14:28 UTC, javimed requested changes

2023-12-18 14:28 UTC, javimed commented on source/development/wazuh-cluster.rst
> +Imagine a cluster with two nodes, where there is an agent reporting to the worker node with id *020*. The following diagram shows the process of requesting ``GET/sca/020`` API endpoint:
```suggestion
Imagine a cluster with two nodes, where there is an agent reporting to the worker node with id *020*. The following diagram shows the process of running a distributed API request by requesting the ``GET/sca/020`` API endpoint:
```

2023-12-18 14:28 UTC, javimed commented on source/user-manual/api/rbac/reference.rst
> +.. deprecated:: 4.9
```suggestion

.. deprecated:: 4.9
```

2023-12-18 14:28 UTC, javimed commented on source/user-manual/api/rbac/reference.rst
> +.. deprecated:: 4.9
```suggestion

.. deprecated:: 4.9
```

2023-12-18 14:28 UTC, javimed commented on source/user-manual/api/rbac/reference.rst
> +.. deprecated:: 4.9
```suggestion

.. deprecated:: 4.9
```

2024-02-21 15:22 UTC, javimed approved these changes

2024-02-21 15:23 UTC, merged