Whodata 3.1+ & Alpine Linux support
wazuh/wazuh-documentation pull request #6871
Opened 2023-12-19 22:49 UTC by ncvicchi

## Description

Closes [19585](https://github.com/wazuh/wazuh/issues/19585), [6833](https://github.com/wazuh/wazuh-documentation/issues/6833), and [19412](https://github.com/wazuh/wazuh/issues/19412)

## Checks
### Docs building
- [X] Compiles without warnings.
### Code formatting and web optimization
- [X] Uses three spaces indentation.
- [X] Adds or updates meta descriptions accordingly.
- [X] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [X] Uses present tense, active voice, and semi-formal registry.
- [X] Uses short, simple sentences.
- [X] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2023-12-20 08:34 UTC, mjcr99 requested changes
Review plugin name

2023-12-20 08:34 UTC, mjcr99 commented on source/user-manual/capabilities/file-integrity/advanced-settings.rst
> +      In Red Hat based systems, use the following command to install the audspd af_unix plugin:
```suggestion
      In Red Hat based systems, use the following command to install the audispd af_unix plugin:
```

2023-12-20 08:34 UTC, mjcr99 commented on source/user-manual/capabilities/file-integrity/advanced-settings.rst
> +      For Debian based systems, use the following command to install the audspd af_unix plugin:
```suggestion
      For Debian based systems, use the following command to install the audispd af_unix plugin:
```

2023-12-21 08:31 UTC, mjcr99 approved these changes
LGTM

2023-12-21 13:15 UTC, javimed requested changes
I would rather have it in this way using tabs. And why `service auditd restart`? Isn't `systemctl restart service` preferred?

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/7f182400-df67-4680-8f52-5f1c3c8058a1)

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/f45d0102-ee0d-4db1-982a-331458eff71b)

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/a9fba047-e79b-4a0b-a52e-0c0de810f49d)

I can commit this suggestions is accepted.

2023-12-21 13:58 UTC, ncvicchi commented
> I would rather have it in this way using tabs. And why `service auditd restart`? Isn't `systemctl restart service` preferred?
> 
> ![imagen](https://private-user-images.githubusercontent.com/47069802/292213635-7f182400-df67-4680-8f52-5f1c3c8058a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjcyOTcsIm5iZiI6MTcwMzE2Njk5NywicGF0aCI6Ii80NzA2OTgwMi8yOTIyMTM2MzUtN2YxODI0MDAtZGY2Ny00NjgwLThmNTItNWYxYzNjODA1OGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEzNTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMWUyMjQ3NWYwYjk5NDdiZGFkMzYzMmYxYjg5MjkxMzA1N2FlMDc1MjRkNGFkNGUxMjU0NTU3NjdjNjNmYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UZTpcrIDaiMzWCH1yZgxFIjKZ1ESn-yS59ugIFN9TWE)
> 
> ![imagen](https://private-user-images.githubusercontent.com/47069802/292213742-f45d0102-ee0d-4db1-982a-331458eff71b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjcyOTcsIm5iZiI6MTcwMzE2Njk5NywicGF0aCI6Ii80NzA2OTgwMi8yOTIyMTM3NDItZjQ1ZDAxMDItZWUwZC00ZGIxLTk4MmEtMzMxNDU4ZWZmNzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEzNTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YWVlZmEwZTRjZjA2MzI3MGI0NDhjOTM5YTZiMWQ3ZTk1Mjc0NGE3NDFhNWE4ZDQ3MWYzY2MwNjJkYzgzYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rMgcVCXSC7qHGATQt6kO6x5ulOLiTXoFfoS6COZ2jMM)
> 
> ![imagen](https://private-user-images.githubusercontent.com/47069802/292213807-a9fba047-e79b-4a0b-a52e-0c0de810f49d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjcyOTcsIm5iZiI6MTcwMzE2Njk5NywicGF0aCI6Ii80NzA2OTgwMi8yOTIyMTM4MDctYTlmYmEwNDctZTc5Yi00YTBiLWE1MmUtMGMwZGU4MTBmNDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEzNTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MjcxZWU2ZWNiZDNjYmI3MDYxYmY2YTlmOTc1NWMxZWFhYzEwMjllYmYyNDY0Y2U0MzQ3YzJjZDYzMTI1YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g6GDMPaznOYB8V1GGPKDeylSln3dT7Xlday7sxcmeo8)
> 
> I can commit this suggestions if accepted.

I just kept the style that was already there. I looks much better as you propose, so please commit it.

2023-12-21 14:17 UTC, javimed approved these changes

2023-12-21 14:21 UTC, merged