Add Pub/Sub configuration warning
wazuh/wazuh-documentation pull request #7004
Opened 2024-01-31 17:41 UTC by GGP1

## Description

Adds a warning message mentioning that multiple `gcp-pubsub` sections are not supported in the same configuration to the files related to the service.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-02-01 19:57 UTC, fdalmaup requested changes
Although I suggested a change in the `source/cloud-security/gcp/prerequisites/pubsub.rst` file, given that the page does not contain any reference or example of the module's configuration, is it necessary to add the warning message there? Maybe it could be added in the `source/cloud-security/gcp/posture-management.rst` file, in the `Wazuh server` section.

2024-02-01 19:57 UTC, fdalmaup commented on source/cloud-security/gcp/prerequisites/pubsub.rst
> +   The Wazuh GCP module does not support multiple Pub/Sub sections in the same configuration. To configure more than one service, deploying multiple agents is required.
```suggestion
   The Wazuh GCP module does not support multiple Pub/Sub sections in the same :ref:`Wazuh configuration file<reference_ossec_conf>`. To configure more than one service, deploying multiple agents is required.
```

2024-02-01 19:57 UTC, fdalmaup commented on source/user-manual/reference/ossec-conf/gcp-pubsub.rst
> +   Only one ``gcp-pubsub`` section is supported in the same configuration. To configure more than one service, deploying multiple agents is required.
```suggestion
   Only one ``gcp-pubsub`` section is supported in the same :ref:`Wazuh configuration file<reference_ossec_conf>`. To configure more than one service, deploying multiple agents is required.
```

2024-02-02 19:37 UTC, fdalmaup submitted a review, later dismissed
LGTM!

2024-02-05 11:17 UTC, Selutario approved these changes

2024-02-15 12:33 UTC, javimed submitted a review, later dismissed

2024-02-15 14:37 UTC, GGP1 commented
> What about turning those warnings into notes? I don't think red warnings are justified. Maybe notes will achieve the purpose just fine. Please, take a look to suuggested review [changes incorporated into a commit](https://github.com/wazuh/wazuh-documentation/pull/7004/commits/b79ba90ea37cb1014a22399d4da11a14d89d2ffb) which I can easily revert.

@javimed I think we can use notes yes. It looks good from my side.

2024-02-16 19:42 UTC, javimed commented
Sorry, maybe we can use `4.7` as the base branch here

2024-02-19 12:47 UTC, GGP1 commented
@javimed No problem. Just rebased to `4.7` 👍🏼

2024-02-20 09:13 UTC, Selutario approved these changes

2024-02-20 15:42 UTC, merged