Add considerations for max_size API options
wazuh/wazuh-documentation pull request #7063
Opened 2024-02-23 14:29 UTC by nico-stefani

## Description

This PR closes #7013. Adds extra considerations for `max_size` sub-fields in API configurations.

![image](https://github.com/wazuh/wazuh-documentation/assets/7127104/cef2d48c-e76f-4724-adac-38da23ab622b)

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-02-23 15:16 UTC, fdalmaup requested changes

2024-02-23 15:16 UTC, fdalmaup commented on source/user-manual/api/configuration.rst
> +| size       | Any positive number followed by a valid unit. | 1M            | Set a file size to trigger log rotation. This value must be equal or greater than 1M.
```suggestion
| size       | Any positive number followed by a valid unit. | 1M            | Set a file size to trigger log rotation. This value must be equal to or greater than 1M.                                      |
```

2024-02-23 19:14 UTC, fdalmaup submitted a review, later dismissed
LGTM

2024-02-26 11:59 UTC, Selutario requested changes

2024-02-26 11:59 UTC, Selutario commented on source/user-manual/api/configuration.rst
> +| size       | Any positive number followed by a valid unit. | 1M            | Set a file size to trigger log rotation. This value must be equal to or greater than 1M.
There are some extra spaces in this table:
![image](https://github.com/wazuh/wazuh-documentation/assets/23361101/3f5c2a86-8fe7-4c00-87b4-9fd7f3e20907)

2024-03-06 13:43 UTC, javimed requested changes
I would limit the `enabled` subfield description while expanding in `/user-manual/api/getting-started` instead. In basic concepts in getting started we could replace "The Wazuh API logs are rotated daily." with:

_The Wazuh API logs are rotated based on time by default. Rotation only occurs after adding a new entry to the log. For instance, time-based rotation triggers when a new entry is added on a different day, not necessarily every midnight._

For the `enabled` subfield description we could then just go with:

_Toggle between time-based and size-based Wazuh API log rotation. Enabling this option disables time-based rotation, enabling rotation based on file size instead._

And for the `size` subfield description with something like

_Set the maximum file size to not trigger size-based log rotation. Lower than 1 M values are considered as 1 M._

2024-03-08 13:58 UTC, javimed approved these changes

2024-03-11 08:49 UTC, Selutario approved these changes

2024-03-11 12:09 UTC, merged