Fix puppet config steps
wazuh/wazuh-documentation pull request #7120
Opened 2024-03-13 09:40 UTC by vcerenu

## Description

This PR fixes puppet configuration on installation steps.
Related issue https://github.com/wazuh/wazuh-documentation/issues/7027
## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-03-13 09:53 UTC, vcerenu commented
## Tests
I installed and configured Puppet Server and Agent with the new steps:

## Steps
1 - Install and configure Puppet Server:

``` console
root@ip-172-31-39-49:~# vi /etc/hosts
root@ip-172-31-39-49:~# cat /etc/hosts
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

172.31.39.49 puppet puppet-master
172.31.47.96 puppet-agent
root@ip-172-31-39-49:~# apt-get update

apt-get install curl apt-transport-https lsb-release wget
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [14.1 MB]
Get:6 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/universe Translation-en [5652 kB]
Get:7 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/universe amd64 c-n-f Metadata [286 kB]
Get:8 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [217 kB]
Get:9 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse Translation-en [112 kB]
Get:10 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse amd64 c-n-f Metadata [8372 B]
Get:11 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1462 kB]
Get:12 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [285 kB]
Get:13 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1559 kB]
Get:14 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [259 kB]
Get:15 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1056 kB]
Get:16 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [238 kB]
Get:17 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [22.1 kB]
Get:18 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [42.1 kB]
Get:19 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [10.1 kB]
Get:20 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 c-n-f Metadata [472 B]
Get:21 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [67.1 kB]
Get:22 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/main Translation-en [11.0 kB]
Get:23 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/main amd64 c-n-f Metadata [388 B]
Get:24 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/restricted amd64 c-n-f Metadata [116 B]
Get:25 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [28.4 kB]
Get:26 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe Translation-en [16.6 kB]
Get:27 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 c-n-f Metadata [644 B]
Get:28 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/multiverse amd64 c-n-f Metadata [116 B]
Get:29 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1245 kB]
Get:30 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [223 kB]
Get:31 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1531 kB]
Get:32 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [255 kB]
Get:33 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [849 kB]
Get:34 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [162 kB]
Get:35 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [16.8 kB]
Get:36 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [37.1 kB]
Get:37 http://security.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [7476 B]
Get:38 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 c-n-f Metadata [260 B]
Fetched 30.1 MB in 6s (5324 kB/s)                                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
lsb-release is already the newest version (11.1.0ubuntu4).
lsb-release set to manually installed.
wget is already the newest version (1.21.2-2ubuntu1).
wget set to manually installed.
curl is already the newest version (7.81.0-1ubuntu1.15).
curl set to manually installed.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 39 not upgraded.
Need to get 1510 B of archives.
After this operation, 170 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.11 [1510 B]
Fetched 1510 B in 0s (66.8 kB/s)              
Selecting previously unselected package apt-transport-https.
(Reading database ... 64801 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.4.11_all.deb ...
Unpacking apt-transport-https (2.4.11) ...
Setting up apt-transport-https (2.4.11) ...
Scanning processes...                                                                                                                                                                                      
Scanning linux images...                                                                                                                                                                                   

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
root@ip-172-31-39-49:~# wget https://apt.puppet.com/puppet7-release-jammy.deb
dpkg -i puppet7-release-jammy.deb
apt-get update
apt-get install -y puppetserver
--2024-03-13 09:21:43--  https://apt.puppet.com/puppet7-release-jammy.deb
Resolving apt.puppet.com (apt.puppet.com)... 18.165.83.58, 18.165.83.21, 18.165.83.25, ...
Connecting to apt.puppet.com (apt.puppet.com)|18.165.83.58|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11324 (11K) [application/x-debian-package]
Saving to: ‘puppet7-release-jammy.deb’

puppet7-release-jammy.deb                          100%[===============================================================================================================>]  11.06K  --.-KB/s    in 0s      

2024-03-13 09:21:43 (72.4 MB/s) - ‘puppet7-release-jammy.deb’ saved [11324/11324]

Selecting previously unselected package puppet7-release.
(Reading database ... 64805 files and directories currently installed.)
Preparing to unpack puppet7-release-jammy.deb ...
Unpacking puppet7-release (7.0.0-16jammy) ...
Setting up puppet7-release (7.0.0-16jammy) ...
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Get:5 http://apt.puppet.com jammy InRelease [113 kB] 
Get:6 http://apt.puppet.com jammy/puppet7 all Packages [5315 B]
Get:7 http://apt.puppet.com jammy/puppet7 amd64 Packages [11.7 kB]
Fetched 130 kB in 1s (97.6 kB/s)     
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ca-certificates-java fontconfig-config fonts-dejavu-core java-common libavahi-client3 libavahi-co [...]

2024-03-13 09:54 UTC, vcerenu commented
### Compiles all Documentation

``` console
$ make html clean && make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v7.1.2
loading translations [en-US]... not available for built-in messages
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent
Copying static files for wazuh-doc-images...[100%] img/loading.gif
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] index
generating indices... done
writing additional pages... not_found moved-content search done
dumping search index in English (code: en)... done
dumping object inventory... done
Copying tabs assets
build succeeded.

The HTML pages are in build/html.

Build finished. The HTML pages are in build/html.

rm -rf build/*
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v7.1.2
loading translations [en-US]... not available for built-in messages
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 698 source files that are out of date
updating environment: [new config] 698 added, 0 changed, 0 removed
reading sources... [100%] user-manual/wazuh-indexer/wazuh-indexer-tuning
Copying static files for wazuh-doc-images...[100%] img/loading.gif
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] user-manual/wazuh-indexer/wazuh-indexer-tuning
generating indices... done
writing additional pages... not_found moved-content search done
copying images... [100%] images/manual/wazuh-indexer/indexer-cluster-with-shard-replicas-diagram.png
dumping search index in English (code: en)... done
dumping object inventory... done
Copying tabs assets
build succeeded.

The HTML pages are in build/html.

Build finished. The HTML pages are in build/html.
```

2024-03-13 09:57 UTC, davidcr01 approved these changes

2024-03-13 13:08 UTC, teddytpc1 submitted a review, later dismissed

2024-03-14 12:07 UTC, javimed requested changes

2024-03-14 12:07 UTC, javimed commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst
> +Add the server value to the ``[main]`` section of the node ``/etc/puppetlabs/puppet/puppet.conf`` (Linux) or  ``C:\ProgramData\PuppetLabs\puppet\etc\puppet.conf`` (Windows) file, replacing ``puppet-m
```suggestion
To configure the Puppet agent, edit the configuration file in the node.

-  ``/etc/puppetlabs/puppet/puppet.conf`` for Linux systems
-  ``C:\ProgramData\PuppetLabs\puppet\etc\puppet.conf`` for Windows systems

Add the ``server`` setting to the ``[main]`` section of the file.  If you have set up your own DNS, replace ``puppet-master`` with the Fully Qualified Domain Name (FQDN) of your Puppet server.
```

2024-03-14 12:07 UTC, javimed commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst
>     [main]
```suggestion
   .. code-block:: none

      [main]
```

2024-03-14 12:07 UTC, javimed commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst
> +   server = puppet-master
```suggestion
      server = puppet-master
```

2024-03-19 13:18 UTC, vcerenu commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
> +Edit the ``/etc/puppetlabs/puppet/puppet.conf`` file, adding these lines to the ``[main]`` section (create the section if it does not exist), and replacing ``puppet,puppet-master`` with your own FQDN
done

2024-03-19 13:18 UTC, vcerenu commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
>    ::
done

2024-03-19 13:18 UTC, vcerenu commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
>      [main]
done

2024-03-19 13:19 UTC, vcerenu commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
> +    server = puppet-master
done

2024-03-19 13:19 UTC, vcerenu commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
> +    dns_alt_names = puppet, puppet-master
done

2024-03-19 13:19 UTC, vcerenu commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst
> +Add the server value to the ``[main]`` section of the node ``/etc/puppetlabs/puppet/puppet.conf`` (Linux) or  ``C:\ProgramData\PuppetLabs\puppet\etc\puppet.conf`` (Windows) file, replacing ``puppet-m
done

2024-03-19 13:19 UTC, vcerenu commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst
>     [main]
done

2024-03-19 13:19 UTC, vcerenu commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst
> +   server = puppet-master
done

2024-03-22 12:35 UTC, javimed requested changes

2024-03-22 12:35 UTC, javimed commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst
> +-  ``/etc/puppetlabs/puppet/puppet.conf`` for Linux systems
```suggestion

-  ``/etc/puppetlabs/puppet/puppet.conf`` for Linux systems
```

2024-03-22 12:35 UTC, javimed commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst
> +Add the ``server`` setting to the ``[main]`` section of the file.  If you have set up your own DNS, replace ``puppet-master`` with the Fully Qualified Domain Name (FQDN) of your Puppet server.
```suggestion

Add the ``server`` setting to the ``[main]`` section of the file.  If you have set up your own DNS, replace ``puppet-master`` with the Fully Qualified Domain Name (FQDN) of your Puppet server.
```

2024-03-22 12:40 UTC, davidcr01 submitted a review, later dismissed

2024-03-22 12:41 UTC, c-bordon approved these changes

2024-03-22 12:47 UTC, javimed approved these changes

2024-03-22 12:48 UTC, merged