Add the indexer configuration option
wazuh/wazuh-documentation pull request #7164
Opened 2024-04-03 17:56 UTC by GGP1

## Description

Adds the `indexer -> allow` value to the API configuration section of the documentation.

## Checks
### Docs building
- [x] Compiles without warnings.

![image](https://github.com/wazuh/wazuh-documentation/assets/51374959/f55a4313-958e-4e94-a268-dbf37f33ac31)

### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-04-03 20:20 UTC, fdalmaup requested changes

2024-04-03 20:20 UTC, fdalmaup commented on source/user-manual/api/configuration.rst
> +| allow      | yes, true, no, false | true          | Allow uploading configurations with modified indexer values through the Wazuh API. Setting this option to ``false`` prevents uploading ``ossec.co
I would add a link to the `indexer` tag reference (`user-manual/reference/ossec-conf/indexer.html`).

2024-04-04 20:29 UTC, fdalmaup submitted a review, later dismissed
LGTM!

2024-04-10 11:10 UTC, Selutario approved these changes

2024-04-10 15:09 UTC, javimed requested changes

2024-04-10 15:09 UTC, javimed commented on source/user-manual/api/configuration.rst
> +| allow      | yes, true, no, false | true          | Allow uploading configurations with modified indexer values through the Wazuh API. Setting this option to ``false`` prevents uploading ``ossec.co
```suggestion
| allow      | yes, true, no, false | true          | Allows uploading an updated :doc:`indexer configuration section </user-manual/reference/ossec-conf/indexer>` through the Wazuh API. Setting this option to ``false`` prevents updating the indexer configuration when uploading ``ossec.conf``.                                                                                             |
```

2024-04-10 15:09 UTC, javimed commented on source/user-manual/reference/ossec-conf/indexer.rst
> +
```suggestion
```

2024-04-10 15:09 UTC, javimed commented on source/user-manual/reference/ossec-conf/indexer.rst
> +.. _reference_ossec_indexer:
```suggestion
```

2024-04-10 17:43 UTC, javimed approved these changes

2024-04-15 11:39 UTC, merged