Update VD POC
wazuh/wazuh-documentation pull request #7199
Opened 2024-04-15 22:42 UTC by GabrielEValenzuela

_WIP_

2024-04-16 18:40 UTC, MiguelazoDS reviewed
GJ!

2024-04-16 18:40 UTC, MiguelazoDS commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +Visualizing the alerts
This section appears outside the vulnerability detection main section in the left panel 
![image](https://github.com/wazuh/wazuh-documentation/assets/13010397/00a46efa-2a23-4ec4-8a05-56bb7c4fc695)

2024-04-16 18:40 UTC, MiguelazoDS commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
The Infrastructure table seems outdated now after the inclusion of new endpoints.

2024-04-16 18:40 UTC, MiguelazoDS commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +Visualizing the alerts
What is shown in the images below are indexed vulnerabilities among other sections. Vulnerability alerts heading is related to the "events" section. Couldn't that confuse a little bit the readers?

2024-04-16 18:50 UTC, sebasfalcone commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +- **Total Number of Vulnerabilities**: Get an overview of the total number of vulnerabilities grouped by their severity levels.
Order them as they appear on the dashboard
- Distribution of Vulnerabilities by Severity Levels
- Summary of Top 5 Vulnerabilities
- Most common vulnerabilities

"Total Number of Vulnerabilities" is not present on this section

2024-04-16 18:50 UTC, sebasfalcone commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +Events
Add a note explaining that this works with events after the first scan that works as a baseline

2024-04-16 20:39 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +Events
Done!

2024-04-16 20:39 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +- **Total Number of Vulnerabilities**: Get an overview of the total number of vulnerabilities grouped by their severity levels.
Done!

2024-04-16 20:39 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +Visualizing the alerts
Done!

2024-04-16 20:39 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +Visualizing the alerts
Done!

2024-04-16 20:40 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
I think is fixed!

2024-04-16 21:15 UTC, sebasfalcone submitted a review, later dismissed

2024-04-17 19:58 UTC, javimed requested changes
In general, the PoCs in our documentation follow a shared structure as follows:

- Infrastructure
- Configuration
- Attack emulation / Test the configuration
- Alerts visualization

PoC's are not meant to describe a capability but to show a practical and specific use case, to convey the idea of one of the product possibilities. Why are we describing the Vulnerability detection module as describing  a capability, in the same way done for, for example the FIM capability here?:
- https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/interpreting-fim-module-analysis.html

In this vulnerability detection PoC, if we're using an Ubuntu 22 endpoint and a Windows 11 endpoint as the infrastructure we should provide steps to visualize vulnerability alerts and findings for Ubuntu 22 and Windows 11 vulnerable packages, and optimally their remediations, specifically.

Having steps to test the configuration by installing some vulnerable packages and upgrading or removing them and steps to visualize alerts and findings would comply with other PoCs in the Proof of concept guide.

2024-04-18 19:03 UTC, rauldpm requested changes
We cannot merge this PR as it is, is this PR a `bug` or an `enhancement`? Fix branch type or label (based on your description it is an enhancement, not a bug) and yet, the issue is classified as a bug

Also, fix the branch typo: 

>bug/7183_`imrpove`-poc-vd

2024-04-18 19:26 UTC, javimed requested changes

2024-04-18 19:26 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +The infrastructure setup for this PoC includes a Wazuh Manager hosted on Ubuntu 22.04 and multiple Agents deployed across various operating systems. These Agents continuously monitor and evaluate the
Let's better keep the same format across all PoCs in this guide. "Infrastructure" sub-section uses just a table and no introductory text. The table lists the endpoints used in the use case. This listed endpoints correspond to the alerts showed in the "Visualize the alerts" section. These are very specific endpoints. The ones particularly used to later display alerts. For example:

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/8ecc541e-0285-418c-9c7d-a57fcc2a03b9)

2024-04-18 19:26 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +
The Test the configuration sub-section lists steps required to test the configuration carried out above. For example:

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/5b405be7-fcf4-42cd-9677-4b4be1602d56)

In the case of vulnerability detection module maybe this could involve installing specific vulnerable packages or checking they are present in the specific system(s) selected that are listed in the infrastructure section above. It might also involve patching or uninstalling them in the case we are showing solved vulnerabilities as part of the proof of concept.

2024-04-18 19:26 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +3. **Result Visualization**:
Visualization of results is what we need to show in the "Visualize the alerts" sub-section below.

2024-04-18 19:26 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +Dashboard
The "Visualize the alerts" sub-section should show the results of testing the configuration. This is where the reader visualizes the alerts that were triggered and maybe some dashboards with specific findings for the previous tests.

This sub-section isn't meant to describe a capability. Describing a capability is appropriate for a user manual section such as this one: https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/interpreting-fim-module-analysis.html

2024-04-18 19:47 UTC, closed without merging