Enhancement/7184 update documentation after package migration
wazuh/wazuh-documentation pull request #7204
Opened 2024-04-16 21:45 UTC by lchico

## Description

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-05-21 10:28 UTC, MarcelKemp requested changes
GJ, just a few minor changes.

2024-05-21 10:28 UTC, MarcelKemp commented on source/development/packaging/generate-deb-rpm-package.rst
> +Download our wazuh repository from GitHub and go to the debs directory.
```suggestion
Download our wazuh repository from GitHub and go to the packages directory.
```

2024-05-21 10:28 UTC, MarcelKemp commented on source/development/packaging/generate-osx-package.rst
> +      -b, --branch <branch>         [Optional] Select Git branch [].
```suggestion
      -b, --branch <branch>         [Optional] Select Git branch.
```

2024-05-21 11:54 UTC, mjcr99 commented on source/development/packaging/generate-deb-rpm-package.rst
> +Download our wazuh repository from GitHub and go to the debs directory.
Fixed by https://github.com/wazuh/wazuh-documentation/pull/7204/commits/3c3c3c0809054b5d51d713c6668fe71ea8525c21.

2024-05-21 11:54 UTC, mjcr99 commented on source/development/packaging/generate-osx-package.rst
> +      -b, --branch <branch>         [Optional] Select Git branch [].
Fixed by https://github.com/wazuh/wazuh-documentation/pull/7204/commits/3c3c3c0809054b5d51d713c6668fe71ea8525c21.

2024-05-21 12:07 UTC, MarcelKemp submitted a review, later dismissed

2024-05-21 15:06 UTC, MarcelKemp approved these changes

2024-05-30 16:36 UTC, javimed requested changes

2024-05-30 16:36 UTC, javimed commented on source/development/packaging/generate-aix-package.rst
> +=========
```suggestion
```

2024-05-30 16:36 UTC, javimed commented on source/development/packaging/generate-aix-package.rst
> +=========
To keep consistency with other files, please remove overlining which is just optional. Same comment for the other occurrences.

2024-05-30 16:36 UTC, javimed commented on source/development/packaging/generate-deb-package.rst
Please add an entry in removedUrls in `redirects.js` file. For example

```
removedUrls['4.9'] = [
  '/deployment-options/offline-installation.html',
  '/development/packaging/generate-deb-package.html',
];
```

Add a redirection between 4.8 and 4.9 versions in redirections.push for this file in `redirects.js` as well. For example

```
/* Redirections from 4.8 to 4.9  */

redirections.push(
  ...
  {
    'target': ['4.8=>4.9'],
    '4.8': '/development/packaging/generate-deb-package.html',
    '4.9': '/development/packaging/generate-deb-rpm-package.html',
  },
  ...
);

/* Pages added in 4.9 */
```

2024-05-30 16:36 UTC, javimed commented on source/development/packaging/generate-rpm-package.rst
Same as before. Please update `redirects.js` with file removal and page redirection.

2024-05-30 16:36 UTC, javimed commented on source/development/packaging/generate-deb-rpm-package.rst
Please add an entry in newUrls in `redirects.js` file.

2024-05-31 18:55 UTC, merged