Add information for hotfixes option
wazuh/wazuh-documentation pull request #7206
Opened 2024-04-17 14:25 UTC by MiguelazoDS

## Description

This PR adds a brief description of the hidden option `hotfixes` for system inventory. 
![2024-04-17_11-17](https://github.com/wazuh/wazuh-documentation/assets/13010397/bc6e6e3f-f6c0-46b0-9984-7cf07b8fc27c)
![2024-04-17_11-21](https://github.com/wazuh/wazuh-documentation/assets/13010397/e9d93e12-2aaf-46c6-a800-2ea7cccd4271)

## Checks
### Docs building
- [x] Compiles without warnings.
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.

2024-04-17 14:42 UTC, sebasfalcone commented on source/user-manual/capabilities/system-inventory/configuration.rst
> +- ``<hotfixes>`` option hidden by default, enables or disables the scanning of hotfixes for Windows systems only. The default value is ``yes``. The allowed values are ``yes`` and ``no``. This option
I think the first part is a bit confusing

```suggestion
- ``<hotfixes>`` enables or disables the scanning of hotfixes for Windows systems only. The default value is ``yes``. The allowed values are ``yes`` and ``no``. This option is ignored for other systems.
```

The "for windows systems only" part implies that for other systems this applies

```suggestion
- ``<hotfixes>`` option hidden by default, enables or disables the scanning of hotfixes for Windows systems. The default value is ``yes``. The allowed values are ``yes`` and ``no``. This option is ignored for other systems.
```

Full suggestions
```suggestion
- ``<hotfixes>`` enables or disables the scanning of hotfixes for Windows systems. The default value is ``yes``. The allowed values are ``yes`` and ``no``. This option is ignored for other systems.
```

2024-04-17 14:58 UTC, sebasfalcone submitted a review, later dismissed
LGMT!

2024-04-17 15:00 UTC, GabrielEValenzuela submitted a review, later dismissed
GJ Migue!

2024-04-18 15:17 UTC, sebasfalcone approved these changes

2024-04-18 15:42 UTC, GabrielEValenzuela approved these changes

2024-04-18 20:51 UTC, javimed requested changes
While documentation for the `<hotfixes>` isn't "hidden" and it's visible in the Reference guide:

- https://github.com/wazuh/wazuh-documentation/blob/4.7/source/user-manual/reference/ossec-conf/wodle-syscollector.rst?plain=1#L168-L184

it is hidden in the default configuration block though enabled by default.

2024-04-18 21:10 UTC, javimed commented on source/user-manual/capabilities/system-inventory/configuration.rst
> +- ``<hotfixes>`` enables or disables the scanning of hotfixes for Windows systems. The default value is ``yes``. The allowed values are ``yes`` and ``no``. This option is ignored for systems other th
An alternative would be moving it out of the list into a new paragraph or note specific for Windows systems.

2024-04-19 13:37 UTC, MiguelazoDS commented on source/user-manual/capabilities/system-inventory/configuration.rst
> +- ``<hotfixes>`` enables or disables the scanning of hotfixes for Windows systems. The default value is ``yes``. The allowed values are ``yes`` and ``no``. This option is ignored for systems other th
I moved the description using the same explanation used in the reference section. 

When I mentioned the option as hidden I meant that there's no visible in the default configuration block, but the option exists and has its effects.

2024-04-19 14:16 UTC, MiguelazoDS commented on source/user-manual/capabilities/system-inventory/configuration.rst
> +- ``<hotfixes>`` enables or disables the scanning of hotfixes for Windows systems. The default value is ``yes``. The allowed values are ``yes`` and ``no``. This option is ignored for systems other th
As we discussed I removed the note and a reference link was added. Please take a look now.

2024-04-19 15:52 UTC, javimed requested changes

2024-04-19 15:52 UTC, javimed commented on source/user-manual/capabilities/system-inventory/configuration.rst
> +For Windows systems there is also a :ref:`wodle_syscollector_hotfixes` option available.
```suggestion
In Windows systems, you can use the ``<hotfixes>`` option. Check :ref:`wodle_syscollector_hotfixes` for the details.
```

2024-04-19 16:12 UTC, merged