Update VD POC
wazuh/wazuh-documentation pull request #7215
Opened 2024-04-18 19:51 UTC by GabrielEValenzuela

# Objective
This PR aims to enhance the precision and usability of the Proof of Concept (POC) documentation for our Vulnerability Detection system. By expanding the documentation to include more detailed sections and illustrative examples, we intend to provide clearer guidance and better support for users engaging with our vulnerability detection tools.

## Description
- Feedback on our existing POC documentation for the Vulnerability Detection system indicated that QA/users often encounter ambiguities and lack sufficient detail to effectively utilize the system. To address these concerns, we have undertaken a comprehensive enhancement of the documentation.
- Key improvements include:
  - **Expanded Sections**: Each section of the documentation now contains a more detailed description, outlining the purpose and functionality with greater clarity. This includes elaborating on the system's architecture, configuration options, and operational procedures.
  - **Illustrative Examples**: We've added practical examples to demonstrate common use cases and scenarios. These examples are designed to help users better understand how to configure and use the system for optimal vulnerability detection.
  - **Enhanced Formatting**: The documentation is formatted in Markdown for improved readability and easier navigation. This includes the use of headers, lists, code blocks, and tables where appropriate, making the content more accessible and user-friendly.

2024-04-18 21:56 UTC, javimed requested changes
The related #7183 issue requires steps to install vulnerable packages in order to trigger alerts. We're not installing a vulnerable Firefox version but using one installed by default. We're not patching or uninstalling Firefox to show solved vulnerabilities either. Are we ok with this approach? Aren't we going to explain in the "Test the configuration" sub-section that installing Firefox 116 or similar is required to see the alerts?

2024-04-18 21:56 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +You don’t have to perform any action. It performs vulnerability detection scans periodically for applications and operating systems on each monitored endpoint. In this example we use the installed pa
```suggestion
You don’t have to perform any action. Wazuh detects the vulnerable packages installed in the Ubuntu endpoint automatically. The time it takes to detect vulnerabilities depends on the Syscollector update interval configured in the ``ossec.conf`` file.
```

2024-04-18 21:56 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +
```suggestion
```

2024-04-18 21:56 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +.. note::
```suggestion
```

2024-04-18 21:56 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +   The time it takes to detect vulnerabilities depends on the syscollector update interval configured in the ``ossec.conf`` file.
```suggestion
```

2024-04-18 21:56 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +You don’t have to perform any action. It performs vulnerability detection scans periodically for applications and operating systems on each monitored endpoint. In this example we use the installed pa
Consider adding a link to the interval syscolletor option referred.

2024-04-18 21:56 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +You can visualize the alert data in the Wazuh dashboard. To do this, go to the Vulnerability Detection module, select Inventory, and see all vulnerable packages. Use the search bar to filter the resu
```suggestion
You can visualize detected vulnerabilities data in the Wazuh dashboard. Go to **Vulnerability Detection** and select **Inventory** to see a list of all vulnerable packages detected. Add ``firefox`` in the search bar to filter vulnerable Firefox packages.
```

2024-04-18 21:56 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +   :title: Detected vulnerabilities on Ubuntu, firefox example
```suggestion
   :title: Detected vulnerabilities on Ubuntu. Vulnerable Firefox packages example
```

2024-04-19 01:48 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +
Done!

2024-04-19 01:49 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +You can visualize the alert data in the Wazuh dashboard. To do this, go to the Vulnerability Detection module, select Inventory, and see all vulnerable packages. Use the search bar to filter the resu
Done!

2024-04-19 01:50 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +   :title: Detected vulnerabilities on Ubuntu, firefox example
Done!

2024-04-19 01:50 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +   The time it takes to detect vulnerabilities depends on the syscollector update interval configured in the ``ossec.conf`` file.
Done!

2024-04-19 01:50 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +.. note::
Done!

2024-04-19 01:50 UTC, GabrielEValenzuela commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +You don’t have to perform any action. It performs vulnerability detection scans periodically for applications and operating systems on each monitored endpoint. In this example we use the installed pa
Done!

2024-04-19 11:36 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +#. Wait until the syscollector runs a new scan.
```suggestion
```

2024-04-19 11:42 UTC, javimed commented on source/proof-of-concept-guide/poc-vulnerability-detection.rst
> +#. Delete the package with ``sudo apt purge vim -y``.
```suggestion
#. Delete the package with ``sudo apt purge vim -y`` to fix the vulnerability.
```

2024-04-19 19:30 UTC, javimed approved these changes

2024-04-19 19:53 UTC, MiguelazoDS approved these changes

2024-04-19 20:01 UTC, merged