Wazuh Cloud - Cold Storage Documentation
wazuh/wazuh-documentation pull request #7223
Opened 2024-04-22 20:16 UTC by sultanovich

## Description

This PR details the process of downloading files en cold storage in Wazuh Cloud.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-04-29 13:53 UTC, sultanovich commented
Hi @JavierBejMen , this PRis ready to be applied, could you check it please?

2024-05-10 19:27 UTC, javimed requested changes

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
Please highlight the relevant information lines with `:emphasize-lines:`, for example

```
   .. code-block:: console
      :class: output
      :emphasize-lines: 7-9

      {
         "environment_cloud_id": "012345678ab",
         "aws": {
            "s3_path": "wazuh-cloud-cold-us-east-1/012345678ab",
            "region": "us-east-1",
            "credentials": {
               "access_key_id": "mUdT2dBjlHd...Gh7Ni1yZKR5If",
               "secret_access_key": "qEzCk63a224...5aB+e4fC1BR0G",
               "session_token": "MRg3t7HIuoA...4o4BXSAcPfUD8",
               "expires_in": 3600
            }
         }
      }
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
Highlight the relevant lines with `:emphasize-lines:`.

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +To obtain the api key token it is necessary to execute this step described in the `Wazuh Cloud CLI </cloud-service/cli/index>` section.
```suggestion
Getting your API key and the AWS token
--------------------------------------

#. Obtain your Wazuh Cloud API key by following the steps outlined in the API :doc:`Authentication </cloud-service/apis/authentication>` section.
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +
```suggestion
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +Use the ``POST /storage/token`` endpoint of the :cloud-api-ref:`Wazuh Cloud API <tag/storage>` to get the AWS token and access the archive data of a specific environment. In this example, we generate
```suggestion
#. Use the :cloud-api-ref:`POST /storage/token <tag/storage>` API endpoint with your key to get a temporary AWS token. For example, the following request generates an AWS token valid for ``3600`` seconds that grants access to the environment archive data with ID ``012345678ab``.
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +----------------------------------------
```suggestion
Generating the AWS `wazuh_cloud_storage` profile
------------------------------------------------
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
```suggestion
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +  # aws --profile wazuh_cloud_storage --region us-east-1 s3 ls --recursive s3://wazuh-cloud-cold-us-east-1/012345678ab/
```suggestion
   # aws --profile wazuh_cloud_storage --region us-east-1 s3 ls --recursive s3://wazuh-cloud-cold-us-east-1/012345678ab/
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +  2024-04-19 18:00:05      77759 012345678ab/output/alerts/2024/04/19/012345678ab_output_alerts_20240419T2100_kdBY42OvE9QJuiia.json.gz
```suggestion
   :class: output

   2024-04-19 17:50:06        493 012345678ab/output/alerts/2024/04/19/012345678ab_output_alerts_20240419T2050_VqaWCpX9oPfDkRpD.json.gz
   2024-04-19 18:00:05      77759 012345678ab/output/alerts/2024/04/19/012345678ab_output_alerts_20240419T2100_kdBY42OvE9QJuiia.json.gz
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
Downloading archive data – Multiple files
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +This command downloads in the `/home/test` directory the archive data files of the environment `012345678ab`.
```suggestion
This command downloads the archive data files of the environment ``012345678ab`` into the ``/home/test/`` directory.
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +  # aws --profile wazuh_cloud_storage --region us-east-1 s3 cp --recursive s3://wazuh-cloud-cold-us-east-1/012345678ab/ /home/test/
```suggestion
   # aws --profile wazuh_cloud_storage --region us-east-1 s3 cp --recursive s3://wazuh-cloud-cold-us-east-1/012345678ab/ /home/test/
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +  download: s3://wazuh-cloud-cold-us-east-1/012345678ab/output/alerts/2024/04/19/012345678ab_output_alerts_20240419T2100_kdBY42OvE9QJuiia.json.gz to output/alerts/2024/04/19/012345678ab_output_alerts
Use three-spaces tabulation

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
Downloading archive data – Single file
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +This command downloads in the directory `/home/test` the file `012345678ab_output_alerts_20240419T2050_VqaWCpX9oPfDkRpD.json.gz` from the environment `012345678ab`.
```suggestion
This command downloads the ``012345678ab_output_alerts_20240419T2050_VqaWCpX9oPfDkRpD.json.gz`` file of the environment ``012345678ab`` into the directory ``/home/test``.
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +  # aws --profile wazuh_cloud_storage --region us-east-1 s3 cp --recursive s3://wazuh-cloud-cold-us-east-1/012345678ab/012345678ab_output_alerts_20240419T2050_VqaWCpX9oPfDkRpD.json.gz /home/test/
```suggestion
   # aws --profile wazuh_cloud_storage --region us-east-1 s3 cp --recursive s3://wazuh-cloud-cold-us-east-1/012345678ab/012345678ab_output_alerts_20240419T2050_VqaWCpX9oPfDkRpD.json.gz /home/test/
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +  :class: output
```suggestion
   :class: output
```

2024-05-10 19:27 UTC, javimed commented on source/cloud-service/archive-data/access.rst
> +  download: s3://wazuh-cloud-cold-us-east-1/012345678ab/output/alerts/2024/04/19/012345678ab_output_alerts_20240419T2050_VqaWCpX9oPfDkRpD.json.gz to ./012345678ab_output_alerts_20240419T2050_VqaWCpX9
```suggestion
   download: s3://wazuh-cloud-cold-us-east-1/012345678ab/output/alerts/2024/04/19/012345678ab_output_alerts_20240419T2050_VqaWCpX9oPfDkRpD.json.gz to ./012345678ab_output_alerts_20240419T2050_VqaWCpX9oPfDkRpD.json.gz
```

2024-05-20 20:38 UTC, javimed approved these changes

2024-05-20 20:40 UTC, javimed commented
Added commit and merged changes on demand from @dariommr

2024-05-20 20:40 UTC, merged