Changed API configuration step in offline documentation
wazuh/wazuh-documentation pull request #7234
Opened 2024-04-25 11:38 UTC by davidcr01

## Description

Closes: https://github.com/wazuh/wazuh-documentation/issues/7225

The aim of this to change the `localhost` value of the `/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml` file of the Wazuh offline documentation and the Step-by-step documentation of the Wazuh dashboard installation.

This change is done because we do not support the `localhost` value in that file due to https://github.com/wazuh/wazuh-packages/issues/2771. This also implies to remove the `Only for distributed deployments` note.
 
Also, I flxed a typo in the Offline documentation.

![Screenshot from 2024-04-25 12-25-05](https://github.com/wazuh/wazuh-documentation/assets/72193239/e2a4a1d7-b7e4-4cc6-8287-e7ac8e55e178)
![Screenshot from 2024-04-25 12-25-16](https://github.com/wazuh/wazuh-documentation/assets/72193239/7ea77456-9ae4-47fe-89f2-5ec468400c89)

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-04-29 12:17 UTC, teddytpc1 approved these changes

2024-04-29 14:14 UTC, javimed requested changes
And what about all the user administration documents? For example password management document or the Google SSO as administrator

- https://github.com/wazuh/wazuh-documentation/blob/bed6341c3c4f0e319756eee1496de0341e4b912a/source/user-manual/user-administration/password-management.rst?plain=1#L243
- https://github.com/wazuh/wazuh-documentation/blob/bed6341c3c4f0e319756eee1496de0341e4b912a/source/user-manual/user-administration/single-sign-on/administrator/google.rst?plain=1#L253

same for LDAP occurrences. Or for example these lines?

- https://github.com/wazuh/wazuh-documentation/blob/bed6341c3c4f0e319756eee1496de0341e4b912a/source/user-manual/wazuh-dashboard/troubleshooting.rst?plain=1#L87
- https://github.com/wazuh/wazuh-documentation/blob/bed6341c3c4f0e319756eee1496de0341e4b912a/source/user-manual/wazuh-dashboard/config-file.rst?plain=1#L57
-

2024-04-29 14:17 UTC, javimed commented on source/deployment-options/offline-installation.rst
> +                     url: https://<wazuh_server_ip>
We use uppercase and underscores for placeholders.

2024-04-30 16:54 UTC, davidcr01 commented on source/installation-guide/wazuh-dashboard/step-by-step.rst
Changed.

2024-04-30 16:54 UTC, davidcr01 commented on source/deployment-options/offline-installation.rst
Changed.

2024-04-30 16:54 UTC, davidcr01 commented on source/installation-guide/wazuh-dashboard/step-by-step.rst
> +               url: https://<wazuh_server_ip>
Done

2024-04-30 16:54 UTC, davidcr01 commented on source/installation-guide/wazuh-dashboard/step-by-step.rst
Done

2024-04-30 16:54 UTC, davidcr01 commented on source/installation-guide/wazuh-dashboard/step-by-step.rst
> +
Done

2024-04-30 16:54 UTC, davidcr01 commented on source/deployment-options/offline-installation.rst
> +    -   URL: *https://<wazuh_dashboard_ip>*
Done

2024-04-30 20:11 UTC, javimed approved these changes

2024-05-02 12:21 UTC, teddytpc1 approved these changes

2024-05-02 14:17 UTC, merged