Update WPK documentation: adapt new names and paths
wazuh/wazuh-documentation pull request #7246
Opened 2024-04-29 20:54 UTC by TomasTurina

## Description

Related: https://github.com/wazuh/wazuh/issues/21152

This PR includes the changes necessary to the documentation after the latest improvements introduced in the WPK upgrade mechanism.

Changes required are detailed in this issue: https://github.com/wazuh/wazuh/issues/22672

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-04-29 21:10 UTC, jr0me commented on source/user-manual/agent/agent-management/remote-upgrading/wpk-list.rst
> +| Distribution | Version         | Architecture | WPK Package                   |
The tables in this file look a bit odd, maybe we could re format them since we are here.

2024-04-29 21:11 UTC, jr0me approved these changes
LGTM

2024-04-30 19:08 UTC, TomasTurina commented on source/user-manual/agent/agent-management/remote-upgrading/custom-repository.rst
> +    - Y is the machine's architecture, and
Not necessary in Windows right now, but will be in the future.

2024-04-30 19:09 UTC, TomasTurina commented on source/user-manual/agent/agent-management/remote-upgrading/custom-repository.rst
> +    - Z is the type of package included in the WPK file.
For macOS yes, for Windows not right now but it will in the future (same as architecture).

2024-04-30 19:10 UTC, TomasTurina commented on source/user-manual/agent/agent-management/remote-upgrading/wpk-list.rst
>  .. |WPK_Windows| replace:: `wazuh_agent_v|WAZUH_CURRENT_WINDOWS|_windows.wpk <https://packages.wazuh.com/4.x/wpk/windows/wazuh_agent_v|WAZUH_CURRENT_WINDOWS|_windows.wpk>`__ (`sha512 <https://package
That information is not necessary for Windows right now.

2024-04-30 19:16 UTC, javimed commented on source/user-manual/agent/agent-management/remote-upgrading/custom-repository.rst
> +    - Y is the machine's architecture, and
Then I would rather say `-  ``Y`` indicates the machine architecture. Empty for Windows`

2024-04-30 19:16 UTC, javimed commented on source/user-manual/agent/agent-management/remote-upgrading/custom-repository.rst
> +    - Z is the type of package included in the WPK file.
Then I would rather say `-  ``Z`` represents the package type included in the WPK file. Empty for Windows`

2024-04-30 21:08 UTC, javimed requested changes

2024-04-30 21:08 UTC, javimed commented on source/user-manual/agent/agent-management/remote-upgrading/agent-upgrade-module.rst
> +    |                 | **package_type**  | string        | no       | Manager-inferred             | Specify the type of package to use to upgrade the agents (rpm, deb),             |
```suggestion
    |                 | **package_type**  | string        | no       | Manager-inferred             | Specifies the package type for upgrading agents. For example rpm and deb.        |
```

2024-04-30 21:08 UTC, javimed commented on source/user-manual/agent/agent-management/remote-upgrading/agent-upgrade-module.rst
> +    |                 |                   |               |          |                              | especially useful for upgrading unrecognized system platforms                    |
```suggestion
    |                 |                   |               |          |                              | Especially useful for upgrading unrecognized system platforms                    |
```

2024-04-30 21:08 UTC, javimed commented on source/user-manual/agent/agent-management/remote-upgrading/custom-repository.rst
>  Where:
We can create lists without indentation. We use three-spaces tabulation. For example `-  `

```
Where:

-  ``W`` represents the release version.
-  ``X`` denotes the target operating system.
-  ``Y`` indicates the machine architecture. Empty for Windows.
-  ``Z`` represents the package type included in the WPK file. Empty for Windows.
```

2024-05-02 14:46 UTC, javimed approved these changes

2024-05-02 14:47 UTC, merged