Minimum syscollector scan interval set to 60 seconds.
wazuh/wazuh-documentation pull request #7247
Opened 2024-04-29 22:13 UTC by MiguelazoDS

## Description

As part of this implementation https://github.com/wazuh/wazuh/pull/23145/checks, the minimum value for syscollector scan is 60 seconds. 

![image](https://github.com/wazuh/wazuh-documentation/assets/13010397/abcb69eb-55a3-4b0c-bae9-4a1df18e24f0)

## Checks
### Docs building
- [x] Compiles without warnings.

2024-04-30 00:20 UTC, GabrielEValenzuela approved these changes
LGTM!

2024-04-30 02:17 UTC, sebasfalcone approved these changes

2024-05-09 14:03 UTC, javimed requested changes

2024-05-09 14:03 UTC, javimed commented on source/user-manual/reference/ossec-conf/wodle-syscollector.rst
```
+--------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **Default value**  | 1h                                                                                                                          |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **Allowed values** | A positive number with a suffix character for the time unit. Use ``s`` for seconds, ``m`` for minutes, ``h`` for hours, and |
|                    | ``d`` for days. If a value lower than 60 seconds is configured, it automatically adjusts it to 60 seconds.                  |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------+
```

2024-05-09 14:18 UTC, javimed requested changes

2024-05-09 14:18 UTC, javimed commented on source/user-manual/reference/ossec-conf/wodle-syscollector.rst
> +|                    | ``d`` for days. If a value lower than 60 seconds is configured, it automatically adjusts it to 60 seconds.                  |
```suggestion
|                    | ``d`` for days. If the configured value is lower than 60 seconds, it automatically adjusts it to 60 seconds.                |
```

2024-05-09 14:22 UTC, javimed approved these changes

2024-05-09 14:33 UTC, sebasfalcone approved these changes

2024-05-09 14:36 UTC, merged