Add note for apt installations
wazuh/wazuh-documentation pull request #7273
Opened 2024-04-30 16:02 UTC by Tostti

## Description
This PR adds a note to the upgrade central components section, for apt installations noting that if the `opensearch_dashboards.yml` was modified, the system will ask to either keep the modified version or replace it with the updated one, meaning that the user will have to manually add the changes later. 

![image](https://github.com/wazuh/wazuh-documentation/assets/42900763/201de67e-f43c-4688-b6c3-6f50633c2c1d)

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-05-02 06:52 UTC, Desvelao submitted a review, later dismissed
LGTM!

2024-05-02 21:26 UTC, javimed requested changes

2024-05-02 21:26 UTC, javimed commented on source/upgrade-guide/upgrading-central-components.rst
We can place the note before the command. We can expand it as follows


```
         .. note::

            Configuration options might differ across versions. Running the command below prompts you to choose between two options if you modify ``/etc/opensearch_dashboards.yml``:
            
            -  Replace the file with the updated version.
            -  Keep the modified file.
            
            To ensure a smooth update, follow these steps.
            
            #. Backup the file.
            #. Run the command below, choosing to replace the file with the updated version.
            #. Manually reapply any changes.

```

2024-05-03 15:09 UTC, javimed approved these changes

2024-05-03 15:32 UTC, javimed commented
Added a commit with a new suggestion. What about the yum upgrade? Should we remove the file before upgrading to force updating the file?

2024-05-03 15:37 UTC, Tostti commented
> Added a commit with a new suggestion which I can easily revert. 
LGTM

>And what about the yum upgrade? Should we remove the file before upgrading to force updating the file?
I think that it should. In that case we'll be sure that the file is completely replaced

2024-05-03 15:39 UTC, javimed submitted a review, later dismissed

2024-05-03 18:57 UTC, javimed approved these changes

2024-05-06 13:22 UTC, asteriscos approved these changes
LGTM :heavy_check_mark: 

![image](https://github.com/wazuh/wazuh-documentation/assets/9343732/624e03e4-a99d-4a8c-acdc-3eedf86d7060)

2024-05-06 17:45 UTC, javimed commented
@Tostti and @Desvelao have agreed to merge these changes.

2024-05-06 17:45 UTC, merged