Add documentation for Wazuh Indexer Packages generation
wazuh/wazuh-documentation pull request #7297
Opened 2024-05-08 19:12 UTC by f-galland

## Description
This PR adds documentation for the generation of Wazuh Indexer packages.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-05-10 15:29 UTC, AlexRuiz7 requested changes
We should guide the user towards the `wazuh-indexer` repo, instructing them to clone the repo and lead them to the appropriate folder containing the tools to build packages.

2024-05-13 10:57 UTC, AlexRuiz7 requested changes

2024-05-13 10:57 UTC, AlexRuiz7 commented on source/development/packaging/generate-indexer-package.rst
> +==================================
These 2 sentences are interpreted as a title and merged together, causing rendering issues.

![image](https://github.com/wazuh/wazuh-documentation/assets/15186973/4d8b2a32-19e6-45a6-b065-89d9abf3adb3)

![image](https://github.com/wazuh/wazuh-documentation/assets/15186973/3247eabc-69be-40c9-83e4-f1820cc0e0da)

2024-05-13 10:57 UTC, AlexRuiz7 commented on source/development/packaging/generate-indexer-package.rst
Remove the tailing `:` from the headings. Also, let's rework the headings, so the documentation is easy to follow. For example, there are too many  `DEB, RPM, TAR` headings, which makes the document's schema confusing.

For example, we could use:

1. Introduction. Explain the process, scripts, build phase, assembly phase, ...
2. Prerequisites. Docker, repo setup, ...
3. Build phase. This one is common for all packages.
4. Assembly phase. 
5. Scripts reference.

![image](https://github.com/wazuh/wazuh-documentation/assets/15186973/71891a02-e574-462a-bdfd-62175d15d7b2)

2024-05-13 15:49 UTC, AlexRuiz7 submitted a review, later dismissed

2024-05-13 15:49 UTC, AlexRuiz7 commented on source/development/packaging/generate-indexer-package.rst
>  The packages' generation process is launched from two scripts, which are
I'd use "orchestrated by"

2024-05-13 15:55 UTC, AlexRuiz7 approved these changes

2024-05-30 15:20 UTC, javimed requested changes

2024-05-30 15:20 UTC, javimed commented on source/development/packaging/generate-indexer-package.rst
> +**Note:** set the environment variable ``TEST=true`` to assemble a
You can use the directive `.. note::` for notes. For example:

```
.. note::
   
   Set the environment variable.

```

2024-05-30 15:20 UTC, javimed commented on source/development/packaging/generate-indexer-package.rst
> +            It creates the {BUILD,RPMS,SOURCES,SRPMS,SPECS,TMP} folders and
`{BUILD,RPMS,SOURCES,SRPMS,SPECS,TMP}` seems to need text formatting such as code font style.

2024-05-30 15:20 UTC, javimed commented on source/development/packaging/generate-indexer-package.rst
Use `.. code-block:: none` rather than simply `::` for consistency and clarity

2024-05-30 15:20 UTC, javimed commented on source/development/packaging/generate-indexer-package.rst
> +      .. _rpm-1:
What's the purpose of `.. _rpm-1:` here?

2024-05-30 15:20 UTC, javimed commented on source/development/packaging/generate-indexer-package.rst
> +      .. _deb-1:
Same comment here

2024-05-30 15:20 UTC, javimed commented on source/development/packaging/generate-indexer-package.rst
> +.. code:: console
This block doesn't seem to be for the terminal (console). Use proper syntax highlighting or `none` for just a code style formatted block.

2024-05-31 11:27 UTC, rauldpm commented
Please use the correct branch convention, and create a new PR with the correct branch naming, check the following documentation:

- https://sites.google.com/wazuh.com/devel/tools/github/branches

2024-05-31 11:28 UTC, rauldpm requested changes
Wrong branch naming

2024-05-31 11:57 UTC, closed without merging

2024-05-31 11:59 UTC, f-galland commented
@javimed, @rauldpm, @AlexRuiz7:

I'm renaming the branch which closes this PR. I'll create a new one with your suggested changes.