Add documentation for Wazuh as a custom source ASL integration
wazuh/wazuh-documentation pull request #7310
Opened 2024-05-14 16:07 UTC by AlexRuiz7

## Description

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-05-16 15:12 UTC, f-galland submitted a review, later dismissed

2024-05-30 13:19 UTC, javimed requested changes

2024-05-30 13:19 UTC, javimed commented on source/cloud-security/amazon/services/supported-services/amazon-security-lake/security-lake-source.rst
> +The integration maps Wazuh Security Events to the **OCSF v1.1.0** `Security Finding (2001) <https://schema.ocsf.io/classes/security_finding>`__ Class.
Use italics for for emphasis. For example `*OCSF v1.1.0*`. Use bold font style for UI elements.

2024-05-30 13:19 UTC, javimed commented on source/cloud-security/amazon/services/supported-services/amazon-security-lake/security-lake-source.rst
Consider using code font style in tables for attribute names, attribute values, class names, data types, etc. For example ` ``200101`` `, ` ``type_uid`` `, ` ``Wazuh, Inc.`` `, ` ``time`` ` (if we mean a key, field, etc. named "time")

2024-05-30 13:19 UTC, javimed commented on source/cloud-security/amazon/services/supported-services/amazon-security-lake/security-lake-source.rst
`wazuh-indexer` is the service name, if we mean the component we say `the Wazuh indexer`.

2024-05-30 13:19 UTC, javimed commented on source/cloud-security/amazon/services/supported-services/amazon-security-lake/security-lake-source.rst
You can specify the prompt symbol. For example

```
   .. code-block:: console

      $ sudo /usr/share/logstash/bin/logstash-plugin install logstash-input-opensearch
```

Copy-to-clipboard discards leading `$` and `#` so no worries about that.

2024-05-31 20:02 UTC, merged