Added warning message in changing passwords in Docker and Kubernetes
wazuh/wazuh-documentation pull request #7321
Opened 2024-05-22 08:04 UTC by davidcr01

## Description

Closes: https://github.com/wazuh/wazuh-documentation/issues/7319
The aim of this PR is to add a warning message in the Docker and Kubernetes change password documentation:
- https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#change-the-password-of-wazuh-users
- https://documentation.wazuh.com/current/deployment-options/deploying-with-kubernetes/kubernetes-deployment.html#change-the-password-of-wazuh-users

The message informs the user not to specify the `&` and the `$` characters in the new passwords, as they can break the deployment.

The final result is the following:
![Screenshot from 2024-05-22 00-15-10](https://github.com/wazuh/wazuh-documentation/assets/72193239/f0307cb0-fedd-4f79-a9da-6ad779c7bb49)

2024-05-22 08:08 UTC, vcerenu approved these changes

2024-05-22 11:36 UTC, c-bordon approved these changes

2024-05-22 17:11 UTC, javimed requested changes

2024-05-23 12:24 UTC, javimed approved these changes

2024-05-23 12:25 UTC, javimed commented
## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [X] Adds or updates meta descriptions accordingly.
- [X] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [X] Uses present tense, active voice, and semi-formal registry.
- [X] Uses short, simple sentences.
- [X] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-05-23 12:36 UTC, merged