Add debian and ubuntu supported versions
wazuh/wazuh-documentation pull request #7331
Opened 2024-05-24 09:59 UTC by vcerenu

## Description

This Pr adds supported versions of Debian and Ubuntu into Puppet install process.
Related issue https://github.com/wazuh/wazuh-puppet/issues/958
## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-05-24 11:20 UTC, teddytpc1 approved these changes

2024-05-24 11:53 UTC, javimed requested changes

2024-05-24 11:53 UTC, javimed commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
> ++------------+---------+--------+---------+--------+----------+----------+------------------------------+
```suggestion
The manifest supports the following releases to install wazuh.

**Ubuntu**

-  Jammy Jellyfish
-  Focal Fossa
-  Bionic Beaver
-  Yakkety Yak
-  Xenial Xerus
-  Wily Werewolf
-  Vivid Vervet
-  Trusty Tahr
-  Precise Pangolin

**Debian**

-  bookworm
-  bullseye
-  buster
-  stretch
-  jessie
-  wheezy
```

2024-05-24 11:53 UTC, javimed commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
>  .. note::
```suggestion
```

2024-05-24 11:53 UTC, javimed commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
```suggestion
```

2024-05-24 12:30 UTC, vcerenu commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
> ++------------+---------+--------+---------+--------+----------+----------+------------------------------+
done
![image](https://github.com/wazuh/wazuh-documentation/assets/56500015/21fae729-6b32-42ad-8672-c02c8f42896e)

2024-05-24 12:31 UTC, vcerenu commented on source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
>  .. note::
Done
![image](https://github.com/wazuh/wazuh-documentation/assets/56500015/3b13613e-a80e-40be-97f4-71ff5226bba9)

2024-05-24 13:15 UTC, rauldpm requested changes
This does not seem consistent with 4.8.0 as wazuh-puppet does not specify Debian bookworm as a supported OS 

https://github.com/wazuh/wazuh-puppet/blob/4.8.0/metadata.json

2024-06-03 15:15 UTC, teddytpc1 commented
@javimed, I agreed with @davidjiglesias to add this change to 4.8.0 RC4. We can merge this PR.

2024-06-03 15:56 UTC, javimed approved these changes

2024-06-03 15:56 UTC, merged