Add custom Filebeat user information and delete obsolete information about ossec.conf file on Wazuh server.
wazuh/wazuh-documentation pull request #7382
Opened 2024-06-11 12:27 UTC by CarlosALgit

Related issue: https://github.com/wazuh/wazuh-packages/issues/1369
Related PR: https://github.com/wazuh/wazuh-packages/pull/2989 
## Description

The aim of this PR is to add information to the use if he wants to use a custom user for Filebeat. He will have to update it manually through the Filebeat Keystore tool.

## Checks
### Docs building
The doc has been builded without problems. A screenshot of how it would result:
![Captura desde 2024-06-11 14-19-12](https://github.com/wazuh/wazuh-documentation/assets/93655331/2059a3b1-f78f-4a9c-b419-51c34f781454)

2024-06-11 14:27 UTC, c-bordon requested changes

2024-06-11 14:27 UTC, c-bordon commented on source/user-manual/user-administration/password-management.rst
>        # echo <ADMIN_PASSWORD> | filebeat keystore add password --stdin --force
This step would not be necessary in this part. This command should be executed if the user configured a custom user for Filebeat

` # echo <CUSTOM_USER_PASSWORD> | filebeat keystore add password --stdin --force`

2024-06-13 11:19 UTC, c-bordon submitted a review, later dismissed

2024-06-13 21:00 UTC, javimed approved these changes

2024-06-13 21:02 UTC, merged