Add https related configuration for the HAProxy section
wazuh/wazuh-documentation pull request #7403
Opened 2024-06-14 14:50 UTC by fdalmaup

## Description

Closes https://github.com/wazuh/wazuh/issues/23997. Adds the necessary configuration for the HAProxy Dataplane API and the `haproxy_helper` section to use `https` as the communication protocol.

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-06-18 18:33 UTC, GGP1 requested changes

2024-06-18 18:33 UTC, GGP1 commented on source/user-manual/manager/configuring-cluster/advanced-settings.rst
> +         If you use HTTPS as the Dataplane API communication protocol, you need to add the ``tls`` field and related subfields, being ``tls_port``, ``tls_certificate`` and ``tls_key`` mandatory for t
```suggestion
         If you use HTTPS as the Dataplane API communication protocol, it is mandatory to set the ``tls`` field and related subfields ``tls_port``, ``tls_certificate`` and ``tls_key`` in the configuration. The ``tls_ca`` field is only necessary when using Client Side Certificates.
```

2024-06-19 09:07 UTC, fdalmaup commented on source/user-manual/manager/configuring-cluster/advanced-settings.rst
> +            - insecure: true
This modification raises the following: `configuration error: configuration file /etc/haproxy/dataplaneapi.yml not valid (only yaml format is supported): yaml: line 14: did not find expected '-' indicator`
The suggested configuration follows the alignment mentioned in the [official Dataplane repo example](https://github.com/haproxytech/dataplaneapi/blob/e2389be328814290ef8e92ad4e3242d75e6a1a00/configuration/examples/example-full.yaml#L34-L37).

2024-06-19 09:09 UTC, fdalmaup commented on source/user-manual/manager/configuring-cluster/advanced-settings.rst
> +      -  :ref:`haproxy_protocol <haproxy_protocol>`: HTTPS protocol to use for the HAProxy Dataplane API communication.
Changing the last sentence to `It is recommended to be set to https` since `http` is also allowed.

2024-06-19 12:30 UTC, GGP1 commented on source/user-manual/manager/configuring-cluster/advanced-settings.rst
> +      -  :ref:`haproxy_protocol <haproxy_protocol>`: HTTPS protocol to use for the HAProxy Dataplane API communication.
I used `must` because this is the HTTPS tab, so in order to use an encrypted connection, setting HTTP doesn't work

2024-06-19 12:32 UTC, GGP1 approved these changes

2024-06-20 14:01 UTC, Selutario submitted a review, later dismissed

2024-06-26 15:10 UTC, merged