Change azure-storage-blob version
wazuh/wazuh-documentation pull request #7443
Opened 2024-06-21 10:31 UTC by javiersanchz

## Description

In this PR, the version of `azure-storage-blob` is modified, which was updated in https://github.com/wazuh/wazuh/issues/24061 in `4.9.0`.

2024-06-24 13:08 UTC, GGP1 requested changes

2024-06-24 13:08 UTC, GGP1 commented on source/cloud-security/azure/activity-services/prerequisites/dependencies.rst
> +         # pip3 install azure-storage-blob==12.20.0 azure-storage-common==2.1.0 azure-common==1.1.25 cryptography==3.3.2 cffi==1.14.4 pycparser==2.20 six==1.14.0 python-dateutil==2.8.1 requests==2.25
Related to [this](https://github.com/wazuh/wazuh/pull/24129#pullrequestreview-2135764083) comment.

```suggestion
         # pip3 install azure-storage-blob==12.19.1 azure-storage-common==2.1.0 azure-common==1.1.25 cryptography==3.3.2 cffi==1.14.4 pycparser==2.20 six==1.14.0 python-dateutil==2.8.1 requests==2.25.1 certifi==2022.12.07 chardet==3.0.4 idna==2.9 urllib3==1.26.18 SQLAlchemy==2.0.23 pytz==2020.1
```

2024-06-24 13:08 UTC, GGP1 commented on source/cloud-security/azure/activity-services/prerequisites/dependencies.rst
> +         # pip3 install --break-system-packages azure-storage-blob==12.20.0 azure-storage-common==2.1.0 azure-common==1.1.25 cryptography==3.3.2 cffi==1.14.4 pycparser==2.20 six==1.14.0 python-dateut
Related to [this](https://github.com/wazuh/wazuh/pull/24129#pullrequestreview-2135764083) comment.

```suggestion
         # pip3 install --break-system-packages azure-storage-blob==12.19.1 azure-storage-common==2.1.0 azure-common==1.1.25 cryptography==3.3.2 cffi==1.14.4 pycparser==2.20 six==1.14.0 python-dateutil==2.8.1 requests==2.25.1 certifi==2022.12.07 chardet==3.0.4 idna==2.9 urllib3==1.26.18 SQLAlchemy==2.0.23 pytz==2020.1
```

2024-06-24 14:44 UTC, GGP1 approved these changes

2024-06-26 10:22 UTC, Selutario approved these changes

2024-06-26 13:30 UTC, merged