Change IPs into Ansible Doc
wazuh/wazuh-documentation pull request #7447
Opened 2024-06-24 14:04 UTC by vcerenu

## Description

This PR fix IPs used into Ansible Documentation.
Related Issue https://github.com/wazuh/wazuh-documentation/issues/7295
## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-06-24 14:07 UTC, c-bordon submitted a review, later dismissed

2024-06-26 18:21 UTC, teddytpc1 approved these changes

2024-07-15 12:22 UTC, javimed requested changes
Are the changes in this PR really specific to 5.0.0? Aren't they useful in earlier branches or even in current `4.8` branch as well? Maybe we could change the base branch here.

2024-07-15 12:22 UTC, javimed commented on source/deployment-options/deploying-with-ansible/guide/install-ansible.rst
> +      ``<ENDPOINT_IP> ansible_ssh_user=<SSH_USER>``
```suggestion
      ``<ENDPOINT_IP_ADDRESS> ansible_ssh_user=<SSH_USER>``
```

2024-07-15 15:05 UTC, closed without merging