Add AWS WAF native
wazuh/wazuh-documentation pull request #7511
Opened 2024-07-11 12:20 UTC by javiersanchz

## Description

The native AWS WAF documentation has been added to master (`5.0.0`) for the issue https://github.com/wazuh/wazuh/issues/23364.

2024-07-12 12:37 UTC, GGP1 requested changes
We are repeating the `and click on *Next*` phrase on almost every step, perhaps it's not necessary since it's implied that the user should continue after having performed the action.

2024-07-12 12:37 UTC, GGP1 commented on source/cloud-security/amazon/services/supported-services/waf.rst
> +#. Click *Create web ACL*
```suggestion
#. Click on *Create web ACL*:
```

2024-07-12 12:37 UTC, GGP1 commented on source/cloud-security/amazon/services/supported-services/waf.rst
> +#. Go to Services > Security, Identity, & Compliance > WAF & Shield
```suggestion
#. Go to Services > Security, Identity, & Compliance > WAF & Shield:
```

2024-07-12 12:37 UTC, GGP1 commented on source/cloud-security/amazon/services/supported-services/waf.rst
> +#. Put a name to your web ACL and click on the *Next* button at the bottom of the page:
```suggestion
#. Choose a name for your Web ACL and click on *Next*:
```

The next button is not shown in the image, perhaps we could do a little of zoom out and include it to be clear.

2024-07-12 12:37 UTC, GGP1 commented on source/cloud-security/amazon/services/supported-services/waf.rst
> +#. Click *Add rules* to *add managed rule groups* or *add my own rules and groups* and click on the *Next* button at the bottom of the page.:
```suggestion
#. Click on *Add rules* and select which type of rule to add, then click on *Next*:
```

We are instructing the user to add a rule but we do not specify which or what to put in the form, is this expected?

2024-07-12 12:37 UTC, GGP1 commented on source/cloud-security/amazon/services/supported-services/waf.rst
> +#. Set rule priority and click on the *Next* button at the bottom of the page:
```suggestion
#. Set the rules priority and click on *Next*:
```

2024-07-12 12:37 UTC, GGP1 commented on source/cloud-security/amazon/services/supported-services/waf.rst
> +#. Put a name to your CloudWatch metric and click on the *Next* button at the bottom of the page:
```suggestion
#. Choose a name for your CloudWatch metric and click on *Next*:
```

Where did we create this metric? If it is required we should instruct the user how to do it.

2024-07-12 12:37 UTC, GGP1 commented on source/cloud-security/amazon/services/supported-services/waf.rst
> +#. Review the ACL web and click on the *Create web ACL* button at the bottom of the page to create it
```suggestion
#. Review the Web ACL fields and click on *Create web ACL*  to create it:
```

2024-07-15 12:42 UTC, GGP1 requested changes
There are some requested changes from the previous review that weren't applied yet, please make sure to resolve them

2024-07-15 13:06 UTC, javiersanchz commented on source/cloud-security/amazon/services/supported-services/waf.rst
> +#. Click *Add rules* to *add managed rule groups* or *add my own rules and groups* and click on the *Next* button at the bottom of the page.:
Regarding the rules to implement, it was decided to keep it simple, showing the user where to add them because there are many ways to implement them.

Under "Add managed rule groups":

AWS managed rule groups
Cloudbric Corp. managed rule groups
Cyber Security Cloud Inc. managed rule groups
...
And under "Add my own rules":

Rule JSON editor
Rule visual editor
...
Therefore, adding a specific way of doing it didn't seem like the best option.

2024-07-15 14:21 UTC, GGP1 submitted a review, later dismissed
LGTM

2024-08-30 10:54 UTC, javiersanchz commented
## Update

- Rebased with `master` to stay up to date
- Added a note in the WAF documentation about the new `waf_acls` parameter
- Ran without warnings
- The documentation is ready but will remain on hold until https://github.com/wazuh/wazuh/issues/23363 is resolved, in case we need to make any additional modifications

2024-09-23 07:25 UTC, fdalmaup requested changes
The directory in which the images must be located is `/images/cloud-security/aws`.

2024-09-23 07:25 UTC, fdalmaup commented on source/cloud-security/amazon/services/supported-services/index.rst
> +| Amazon       | :doc:`WAF <waf>`                                                              | bucket                | waf            | <bucket_name>/<prefix>/AWSLogs/<suffix>/<account_id>/WAFLogs/
```suggestion
| Amazon       | :doc:`WAF <waf>`                                                              | bucket                | waf            | <bucket_name>/<prefix>/AWSLogs/<suffix>/<account_id>/WAFLogs/<region>/<acl_name>/<year>/<month>/<day>/<hh>/<mm>  |
```

2024-09-25 09:39 UTC, fdalmaup requested changes

2024-09-25 09:39 UTC, fdalmaup commented on source/cloud-security/amazon/services/supported-services/waf.rst
Given that the `Amazon configuration with Kinesis` will be deprecated, we should modify the `Wazuh configuration` section to contain the `waf_acls` parameter as part of the example.

2024-09-30 09:02 UTC, fdalmaup approved these changes
LGTM

2024-10-01 13:19 UTC, merged