Add new config block anti_tampering
wazuh/wazuh-documentation pull request #7580
Opened 2024-07-26 07:42 UTC by jotacarma90

## Description
In this PR we will add the corresponding entry for the new anti_tampering configuration block, explaining its package_uninstallation label and giving an example.

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-08-29 11:56 UTC, jotacarma90 commented
# Check compiled section

![image](https://github.com/user-attachments/assets/a3cf008f-bbb8-45a7-813a-c379fa79e0ce)

2024-09-02 11:24 UTC, MarcelKemp requested changes

2024-09-02 11:24 UTC, MarcelKemp commented on source/user-manual/reference/ossec-conf/anti_tampering.rst
> +Anti tampering configuration is used to prevent Linux agent package uninstallation without validation from manager.
```suggestion
The anti-tampering configuration is used to prevent uninstallation of the Linux agent package without manager validation.
```

2024-09-02 11:24 UTC, MarcelKemp commented on source/user-manual/reference/ossec-conf/anti_tampering.rst
> +   - ``VALIDATION_HOST``: Host and port where the manager API is installed (host:port). It's required.
Could we restructure these options or correct typos, such as capital letters at the beginning of parentheses?

2024-09-02 14:15 UTC, MarcelKemp submitted a review, later dismissed

2024-09-04 10:03 UTC, vikman90 submitted a review, later dismissed

2024-09-05 20:42 UTC, javimed approved these changes
Replaced `API` mentions with `Wazuh server API` mentions.

2024-09-05 20:42 UTC, merged