Add support for Python 3.12
wazuh/wazuh-documentation pull request #7673
Opened 2024-08-15 19:56 UTC by nico-stefani

## Description

This PR closes wazuh/wazuh#25075. Add support to run the AWS wodle with Python 3.12

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-08-21 07:31 UTC, javiersanchz approved these changes
## Review 

- The changes added to the documentation are correct.

- AWS Cloudwatch is functioning properly after the change.

- The rest of the tests with integrations are correct in the different versions of Python.

From my side, LGTM!

2024-08-26 10:13 UTC, fdalmaup requested changes

2024-08-26 10:13 UTC, fdalmaup commented on source/cloud-security/amazon/services/prerequisites/dependencies.rst
This file has unresolved conflicts with the base branch due to the upward merge that added the `numpy` dependency from https://github.com/wazuh/wazuh-documentation/pull/7589

2024-08-26 11:50 UTC, fdalmaup approved these changes
LGTM!

2024-08-27 12:11 UTC, javimed approved these changes

2024-08-27 12:11 UTC, merged