Change/7941 identify and update references new agent management section
wazuh/wazuh-documentation pull request #7944
Opened 2024-10-29 21:20 UTC by guidomodarelli

## Description

Identify and update all references to the new section category Agent management

#7941

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-11-04 08:50 UTC, Desvelao commented
There are some unchanged references to `Endpoints Summary` that should be changed.

```
./source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst:   :title: Navigating the Wazuh dashboard: Endpoints Summary
./source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst:   :alt: Navigating the Wazuh dashboard: Endpoints Summary
./source/user-manual/agent/agent-management/agent-connection.rst:   :title: Wazuh dashboard Endpoints Summary menu option
./source/user-manual/agent/agent-management/agent-connection.rst:   :alt: Wazuh dashboard Endpoints Summary menu option
./source/user-manual/agent/agent-management/agent-connection.rst:   :title: Wazuh Endpoints Summary dashboard
./source/user-manual/agent/agent-management/agent-connection.rst:   :alt: Wazuh Endpoints Summary dashboard

```

2024-11-04 08:53 UTC, Desvelao requested changes
There are some unchanged references to `Endpoints Summary` that should be changed.

```
./source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst:   :title: Navigating the Wazuh dashboard: Endpoints Summary
./source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst:   :alt: Navigating the Wazuh dashboard: Endpoints Summary
./source/user-manual/agent/agent-management/agent-connection.rst:   :title: Wazuh dashboard Endpoints Summary menu option
./source/user-manual/agent/agent-management/agent-connection.rst:   :alt: Wazuh dashboard Endpoints Summary menu option
./source/user-manual/agent/agent-management/agent-connection.rst:   :title: Wazuh Endpoints Summary dashboard
./source/user-manual/agent/agent-management/agent-connection.rst:   :alt: Wazuh Endpoints Summary dashboard

```

2024-11-04 14:24 UTC, guidomodarelli commented
> There are some unchanged references to `Endpoints Summary` that should be changed.
> 
> ```
> ./source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst:   :title: Navigating the Wazuh dashboard: Endpoints Summary
> ./source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst:   :alt: Navigating the Wazuh dashboard: Endpoints Summary
> ./source/user-manual/agent/agent-management/agent-connection.rst:   :title: Wazuh dashboard Endpoints Summary menu option
> ./source/user-manual/agent/agent-management/agent-connection.rst:   :alt: Wazuh dashboard Endpoints Summary menu option
> ./source/user-manual/agent/agent-management/agent-connection.rst:   :title: Wazuh Endpoints Summary dashboard
> ./source/user-manual/agent/agent-management/agent-connection.rst:   :alt: Wazuh Endpoints Summary dashboard
> ```

![image](https://github.com/user-attachments/assets/d2ea2954-c749-4499-ac15-12cc4a871cda)

I won't change these lines because removing the word "Endpoints" means the "Summary" won't convey any information.
I think replacing "Endpoints" with "Agents" could provide more clarity.

2024-11-04 15:16 UTC, Desvelao submitted a review, later dismissed
LGTM!

2024-11-04 20:22 UTC, chantal-kelm approved these changes
LGTM

2024-11-06 13:46 UTC, javimed commented on source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst
> +Wazuh agents management offers options for managing agents, agent groups, and agent configurations. It also includes options for managing Wazuh agents installed on monitored endpoints.
```suggestion
Wazuh agents management offers options for managing agents, agent groups, and agent configurations.
```

2024-11-06 13:46 UTC, javimed commented on source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst
> +Wazuh server management offers options for managing rules, decoders, CDB lists, clusters, security configurations such as user, roles, policies and more. It also includes options for managing Wazuh a
```suggestion
Wazuh server management offers options for managing rules, decoders, CDB lists, clusters, security configurations such as user, roles, policies and more.
```

2024-11-06 13:57 UTC, javimed approved these changes

2024-11-06 13:57 UTC, merged