Remove VirusTotal references
wazuh/wazuh-documentation pull request #7946
Opened 2024-10-30 09:59 UTC by JuanGarriuz

## Description

## Checks
### Docs building
- [ ] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-11-05 12:58 UTC, guidomodarelli requested changes

2024-11-05 12:58 UTC, guidomodarelli commented on source/compliance/nist/malware-detection.rst
> -- VirusTotal integration for malware detection.
Do not remove this; it is related to the issue: "Update Malware detection documentation to include VirusTotal."

2024-11-05 12:58 UTC, guidomodarelli commented on source/compliance/hipaa/malware-detection.rst
> -  This section of the HIPAA standard requires you to have procedures to detect and remove malicious software. The Wazuh malware detection capability implements this HIPAA section with the aid of out-
Do not remove this; it is related to the issue: "Update Malware detection documentation to include VirusTotal."

2024-11-05 12:58 UTC, guidomodarelli commented on source/getting-started/index.rst
> +          :alt: Endpoints Summary
Why were these lines changed to "Endpoints summary"?
> [!NOTE]
> The "Endpoints Summary" no longer exists; it has been replaced by "Agents Management » Summary."

2024-11-05 12:58 UTC, guidomodarelli commented on source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst
> --  :doc:`VirusTotal </user-manual/capabilities/malware-detection/virus-total-integration>`
Do not remove this; it is related to the issue: "Update Malware detection documentation to include VirusTotal."

2024-11-05 19:05 UTC, javimed requested changes
Hi @JuanGarriuz . Please consider this:

- There's a compilation warning about a broken reference that needs to be fixed: `source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst:43: WARNING: unknown document: '/user-manual/capabilities/malware-detection/virus-total-integration'`
- Virustotal related documentation stays for older versions. Therefore, you souldn't remove redirectioning in older versions, just adapt redirections concerning 4.10 <-> 4.9. Check the code block below. I can help twith it.
- Your teammates must approve the PR once they consider it's ready for merging.

```
...
/* *** RELEASE 4.10 ****/

/* Redirections from 4.9 to 4.10  */

redirections.push(
  {
    'target': ['4.9=>4.10', '4.10=>4.9'],
    ...
  }

/* Pages no longer available in 4.10 */

removedUrls['4.10'] = [
...
]
...
```

2024-11-07 10:17 UTC, chantal-kelm approved these changes
CR: ✅ 
TEST: ✅ 

<img width="1792" alt="Captura de pantalla 2024-11-07 a la(s) 7 16 04 a  m" src="https://github.com/user-attachments/assets/72ac4f89-d6c5-46e2-ae6a-c0b63a2974f3">

2024-11-07 10:26 UTC, JuanGarriuz commented
> Hi @JuanGarriuz . Please consider this:
> 
> * There's a compilation warning about a broken reference that needs to be fixed: `source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst:43: WARNING: unknown document: '/user-manual/capabilities/malware-detection/virus-total-integration'`
> * Virustotal related documentation stays for older versions. Therefore, you souldn't remove redirectioning in older versions, just adapt redirections concerning 4.10 <-> 4.9. Check the code block below. I can help twith it.
> * Your teammates must approve the PR once they consider it's ready for merging.
.....
> ```

After discussing it with the team, those changes will be added to the " Update Malware detection documentation to include VirusTotal" issue.

2024-11-07 14:36 UTC, javimed approved these changes

2024-11-07 14:36 UTC, merged