Change the Python version and `urllib3` to `1.26.20`
wazuh/wazuh-documentation pull request #7978
Opened 2024-11-20 12:54 UTC by javiersanchz

This PR closes https://github.com/wazuh/wazuh/issues/26695, by modifying the Python version to `3.8` and changing the `urllib3` dependency version to `1.26.20`

## Checks
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

2024-11-20 21:24 UTC, nico-stefani submitted a review, later dismissed
LGTM

2024-11-21 10:09 UTC, fdalmaup requested changes
Changes LGTM, nevertheless we should show proof that the DockerListener is working as expected in Amazon Linux 2

2024-11-21 15:55 UTC, fdalmaup submitted a review, later dismissed
LGTM

2024-11-21 20:42 UTC, javimed submitted a review, later dismissed
- What about lines [#43](https://github.com/wazuh/wazuh-documentation/blob/8d12342a6cff2bac8e44b1980cb50c6c70bab27c/source/proof-of-concept-guide/monitoring-docker.rst?plain=1#L43), [#48](https://github.com/wazuh/wazuh-documentation/blob/8d12342a6cff2bac8e44b1980cb50c6c70bab27c/source/proof-of-concept-guide/monitoring-docker.rst?plain=1#L48), and [#55](https://github.com/wazuh/wazuh-documentation/blob/8d12342a6cff2bac8e44b1980cb50c6c70bab27c/source/proof-of-concept-guide/monitoring-docker.rst?plain=1#L55) in `source/proof-of-concept-guide/monitoring-docker.rst`?

2024-11-22 11:37 UTC, javimed approved these changes

2024-11-22 11:38 UTC, merged